#!/bin/sh
set -e
echo "=== [Pre-Commit Gate] 1/3: make format ==="
make format
echo "=== [Pre-Commit Gate] 2/3: make static_analysis ==="
make static_analysis
echo "=== [Pre-Commit Gate] 3/3: make test ==="
make test
