;;; =======================================================================
;;; ULisp Compiler Pass 4: Native x86-64 Code Generation Pass
;;; Conforms to DSN-33 Architecture Specification
;;; =======================================================================

(define (immediate? expr)
  (or (integer? expr)
      (boolean? expr)
      (char? expr)
      (null? expr)
      (string? expr)))

(define (emit-immediate expr)
  (cond
    ((integer? expr)
     (emit (string-append "    mov rax, " (number->string (* expr 4)))))
    ((boolean? expr)
     (if expr
         (emit "    mov rax, 0x6F")   ; #t
         (emit "    mov rax, 0x2F")))  ; #f
    ((char? expr)
     (let ((code (+ (* (char->integer expr) 256) 14)))
       (emit (string-append "    mov rax, " (number->string code)))))
    ((null? expr)
     (emit "    mov rax, 0x3F"))      ; '()
    ((string? expr)
     (emit-string-literal expr))))

(define (compile-zero-arg op si env)
  (let ((frame-shift (align-frame-shift (- si))))
    (case op
      ((read-char)
       (emit (string-append "    sub rsp, " (number->string frame-shift)))
       (emit "    call ulisp_read_char")
       (emit (string-append "    add rsp, " (number->string frame-shift))))
      ((peek-char)
       (emit (string-append "    sub rsp, " (number->string frame-shift)))
       (emit "    call ulisp_peek_char")
       (emit (string-append "    add rsp, " (number->string frame-shift)))))))

(define (compile-unary op arg si env)
  (compile-expr arg si env #f)
  (case op
    ((-)
     (emit "    neg rax"))
    ((fxadd1)
     (emit "    add rax, 4"))
    ((fxsub1)
     (emit "    sub rax, 4"))
    ((fixnum->char integer->char)
     (emit "    shl rax, 6")
     (emit "    or rax, 14"))
    ((char->fixnum char->integer)
     (emit "    shr rax, 6"))
    ((integer->symbol)
     (emit "    shl rax, 6")
     (emit "    or rax, 2"))
    ((symbol->integer)
     (emit "    shr rax, 6"))
    ((zero?)
     (emit "    cmp rax, 0")
     (emit-boolean))
    ((fixnum? integer? number?)
     (emit "    and al, 3")
     (emit "    cmp al, 0")
     (emit-boolean))
    ((boolean?)
     (emit "    mov rdx, rax")
     (emit "    xor rdx, 0x2F")
     (emit "    and rdx, -65")
     (emit "    cmp rdx, 0")
     (emit-boolean))
    ((char?)
     (emit "    and al, 0xFF")
     (emit "    cmp al, 14")
     (emit-boolean))
    ((null?)
     (emit "    cmp rax, 0x3F")
     (emit-boolean))
    ((not)
     (emit "    cmp rax, 0x2F")
     (emit-boolean))
    ((symbol?)
     (emit "    and al, 0xFF")
     (emit "    cmp al, 2")
     (emit-boolean))
    ((car)
     (emit "    mov rax, [rax - 1]"))
    ((cdr)
     (emit "    mov rax, [rax + 7]"))
    ((pair?)
     (emit "    and al, 3")
     (emit "    cmp al, 1")
     (emit-boolean))
    ((procedure?)
     ;; Heap object (tag 1)
     (emit "    and al, 3")
     (emit "    cmp al, 1")
     (emit-boolean))
    ((string?)
     (emit "    and al, 3")
     (emit "    cmp al, 3")
     (emit-boolean))
    ((write-char)
     (let ((frame-shift (align-frame-shift (- si))))
       (emit "    mov rdi, rax")
       (emit (string-append "    sub rsp, " (number->string frame-shift)))
       (emit "    call ulisp_write_char")
       (emit (string-append "    add rsp, " (number->string frame-shift)))))
    ((eof-object?)
     (emit "    cmp rax, 0x4F")
     (emit-boolean))

    ((make-string)
     (emit "    sar rax, 2")
     (emit "    mov rcx, rax")
     (emit "    add rax, 8")
     (emit "    and rax, -8")
     (emit "    mov rdx, r12")
     (emit "    add r12, rax")
     (emit "    mov byte ptr [rdx + rcx], 0")
     (emit "    lea rax, [rdx + 3]"))
    ((string-length)
     (let ((l-loop (unique-label "strlen_loop"))
           (l-done (unique-label "strlen_done")))
       (emit "    mov rdx, rax")
       (emit "    sub rdx, 3")
       (emit "    xor rax, rax")
       (emit (string-append l-loop ":"))
       (emit "    cmp byte ptr [rdx + rax], 0")
       (emit (string-append "    je " l-done))
       (emit "    inc rax")
       (emit (string-append "    jmp " l-loop))
       (emit (string-append l-done ":"))
       (emit "    shl rax, 2")))))

(define (compile-binop op e1 e2 si env)
  (compile-expr e1 si env #f)
  (emit (string-append "    mov [rsp " (offset->string si) "], rax"))
  (compile-expr e2 (- si 8) env #f)
  (case op
    ((+)
     (emit (string-append "    add rax, [rsp " (offset->string si) "]")))
    ((-)
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    sub rdx, rax")
     (emit "    mov rax, rdx"))
    ((*)
     (emit "    sar rax, 2")
     (emit (string-append "    imul rax, [rsp " (offset->string si) "]")))
    ((modulo)
     (emit "    mov rcx, rax")
     (emit (string-append "    mov rax, [rsp " (offset->string si) "]"))
     (emit "    sar rax, 2")
     (emit "    sar rcx, 2")
     (emit "    cqo")
     (emit "    idiv rcx")
     (emit "    mov rax, rdx")
     (emit "    shl rax, 2"))
    ((quotient /)
     (emit "    mov rcx, rax")
     (emit (string-append "    mov rax, [rsp " (offset->string si) "]"))
     (emit "    sar rax, 2")
     (emit "    sar rcx, 2")
     (emit "    cqo")
     (emit "    idiv rcx")
     (emit "    shl rax, 2"))
    ((string-ref)
     (emit "    sar rax, 2")
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    sub rdx, 3")
     (emit "    movzx rax, byte ptr [rdx + rax]")
     (emit "    shl rax, 8")
     (emit "    or rax, 14"))
    ((=)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "sete"))
    ((<)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setl"))
    ((<=)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setle"))
    ((>)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setg"))
    ((>=)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setge"))
    ((cons)
     (emit (string-append "    mov [rsp " (offset->string (- si 8)) "], rax"))
     (emit (string-append "    mov rax, [rsp " (offset->string si) "]"))
     (emit "    mov [r12], rax")
     (emit (string-append "    mov rax, [rsp " (offset->string (- si 8)) "]"))
     (emit "    mov [r12 + 8], rax")
     (emit "    lea rax, [r12 + 1]")
     (emit "    add r12, 16"))
    ((set-car!)
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    mov [rdx - 1], rax")
     (emit "    mov rax, 0x3F"))
    ((set-cdr!)
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    mov [rdx + 7], rax")
     (emit "    mov rax, 0x3F"))
    ((eq? char=?)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean))))

(define (compile-triop op e1 e2 e3 si env)
  (compile-expr e1 si env #f)
  (emit (string-append "    mov [rsp " (offset->string si) "], rax"))
  (compile-expr e2 (- si 8) env #f)
  (emit (string-append "    mov [rsp " (offset->string (- si 8)) "], rax"))
  (compile-expr e3 (- si 16) env #f)
  (case op
    ((string-set!)
     (emit "    shr rax, 8")
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    sub rdx, 3")
     (emit (string-append "    mov rcx, [rsp " (offset->string (- si 8)) "]"))
     (emit "    sar rcx, 2")
     (emit "    mov [rdx + rcx], al")
     (emit "    mov rax, 0x3F"))))

(define (compile-lambda-named name params body si env)
  (let* ((label (unique-label "L_lambda"))
         (bound-vars (if name (cons name params) params))
         (frees (free-vars body bound-vars))
         (num-frees (length frees))
         (num-params (length params))
         (closure-size (* (+ num-frees 1) 8))
         (aligned-size (if (= (modulo closure-size 16) 0) closure-size (+ closure-size 8))))
    ;; 1. Compile and save lambda procedure body into *lambdas*
    (set-car! *lambdas*
              (cons (lambda ()
                      (emit "    .p2align 3")
                      (emit (string-append label ":"))
                      ;; Callee prologue: self closure pointer was in r10
                      ;; Store self closure pointer at [rsp - 8]
                      (let ((self-offset -8))
                        (emit "    mov [rsp - 8], r10")
                        ;; Build callee env:
                        ;; params at [rsp + 8 * (num-params - i)] for i = 0..(num-params - 1)
                        (let* ((param-env
                                (let loop ((ps params) (i 0) (acc '()))
                                  (if (null? ps) acc
                                      (let ((offset (* 8 (- num-params i))))
                                        (loop (cdr ps) (+ i 1)
                                              (cons (cons (car ps) (cons 'param offset)) acc))))))
                               ;; free vars accessed via self closure saved at [rsp - 8]
                               (free-env
                                (let loop ((fs frees) (f-idx 1) (acc '()))
                                  (if (null? fs) acc
                                      (loop (cdr fs) (+ f-idx 1)
                                            (cons (cons (car fs) (cons 'free (cons self-offset (* f-idx 8)))) acc)))))
                               (self-binding (if name (list (cons name (cons 'self self-offset))) '()))
                               (callee-env (cons (cons '%num-params num-params)
                                                 (append self-binding (append param-env free-env))))
                               (callee-si -16))
                          (compile-expr body callee-si callee-env #t)
                          (emit "    ret"))))
                    (car *lambdas*)))

    ;; 2. Allocate closure on heap at runtime (r12)
    ;; Store code pointer label into [r12]
    (emit (string-append "    lea rax, [rip + " label "]"))
    (emit "    mov [r12], rax")
    ;; Store captured free variables into [r12 + 8 * i]
    (let loop ((fs frees) (idx 1))
      (if (not (null? fs))
          (let ((f (car fs)))
            (compile-variable f env)
            (emit (string-append "    mov [r12 + " (number->string (* idx 8)) "], rax"))
            (loop (cdr fs) (+ idx 1)))))
    ;; Tag closure pointer with 0x01 (Heap object)
    (emit "    lea rax, [r12 + 1]")
    (emit (string-append "    add r12, " (number->string aligned-size)))))

(define (compile-lambda params body si env)
  (compile-lambda-named #f params body si env))

(define (compile-variable var env)
  (let ((binding (assq var env)))
    (if (not binding)
        (error "Unbound variable:" var)
        (let ((info (cdr binding)))
          (cond
            ((number? info)
             ;; Standard stack offset
             (emit (string-append "    mov rax, [rsp " (offset->string info) "]")))
            ((and (pair? info) (eq? (car info) 'param))
             ;; Lambda param offset (positive: +8, +16, ...)
             (emit (string-append "    mov rax, [rsp + " (number->string (cdr info)) "]")))
            ((and (pair? info) (eq? (car info) 'self))
             ;; Self closure reference in recursion
             (emit (string-append "    mov rax, [rsp " (offset->string (cdr info)) "]")))
            ((and (pair? info) (eq? (car info) 'free))
             ;; Free variable accessed via self-closure slot on stack
             (let ((self-offset (cadr info))
                   (free-idx (cddr info)))
                (emit (string-append "    mov rdx, [rsp " (offset->string self-offset) "]"))
                (emit (string-append "    mov rax, [rdx + " (number->string (- free-idx 1)) "]"))))
            (else
             (error "Invalid binding format:" binding)))))))

(define (compile-let bindings body si env tail?)
  (let loop ((bs bindings)
             (curr-si si)
             (new-env env))
    (if (null? bs)
        (compile-expr body curr-si new-env tail?)
        (let* ((b (car bs))
               (var (car b))
               (val (cadr b)))
          (compile-expr val curr-si env #f)
          (emit (string-append "    mov [rsp " (offset->string curr-si) "], rax"))
          (loop (cdr bs)
                (- curr-si 8)
                (cons (cons var curr-si) new-env))))))

(define (compile-letrec bindings body si env tail?)
  (let* ((vars (map car* bindings))
         (slots (let loop ((vs vars) (curr-si si) (acc '()))
                  (if (null? vs) acc
                      (loop (cdr vs) (- curr-si 8)
                            (cons (cons (car vs) curr-si) acc)))))
         (extended-env (append slots env))
         (end-si (- si (* (length vars) 8))))
    ;; 1. Evaluate and store each closure into its stack slot
    (let loop ((bs bindings))
      (if (not (null? bs))
          (let* ((b (car bs))
                 (var (car b))
                 (val (cadr b))
                 (slot (cdr (assq var extended-env))))
            (if (and (pair? val) (eq? (car val) 'lambda))
                ;; Named lambda for recursion
                (compile-lambda-named var (cadr val) (make-body-expr (cddr val)) end-si extended-env)
                (compile-expr val end-si extended-env #f))
            (emit (string-append "    mov [rsp " (offset->string slot) "], rax"))
            (loop (cdr bs)))))
    ;; 2. Backpatch mutual references between closures on the heap!
    (let loop-b ((bs bindings))
      (if (not (null? bs))
          (let* ((b (car bs))
                 (var (car b))
                 (val (cadr b))
                 (c-slot (cdr (assq var extended-env))))
            (if (and (pair? val) (eq? (car val) 'lambda))
                (let* ((params (cadr val))
                       (lbody (make-body-expr (cddr val)))
                       (frees (free-vars lbody (cons var params))))
                  ;; Check each free variable of this lambda
                  (let loop-f ((fs frees) (idx 1))
                    (if (not (null? fs))
                        (let* ((f (car fs))
                               (target-entry (assq f slots)))
                          (if target-entry
                              ;; f is one of the letrec-bound variables!
                              (let ((target-slot (cdr target-entry))
                                    (heap-offset (- (* idx 8) 1)))
                                (emit (string-append "    mov rax, [rsp " (offset->string target-slot) "]"))
                                (emit (string-append "    mov rdx, [rsp " (offset->string c-slot) "]"))
                                (emit (string-append "    mov [rdx + " (number->string heap-offset) "], rax"))))
                          (loop-f (cdr fs) (+ idx 1)))))))
            (loop-b (cdr bs)))))
    ;; 3. Compile body
    (compile-expr body end-si extended-env tail?)))

(define (compile-if test then else-opt si env tail?)
  (let ((else-label (unique-label "L_else"))
        (end-label (unique-label "L_end")))
    (compile-expr test si env #f)
    (emit "    cmp rax, 0x2F")
    (emit (string-append "    je " else-label))
    (compile-expr then si env tail?)
    (emit (string-append "    jmp " end-label))
    (emit (string-append else-label ":"))
    (if (null? else-opt)
        (emit "    mov rax, 0x2F")
        (compile-expr (car else-opt) si env tail?))
    (emit (string-append end-label ":"))))

(define (compile-begin exprs si env tail?)
  (if (null? exprs)
      (emit "    mov rax, 0x3F")
      (let loop ((es exprs))
        (if (null? (cdr es))
            (compile-expr (car es) si env tail?)
            (begin
              (compile-expr (car es) si env #f)
              (loop (cdr es)))))))

(define (compile-quote datum si env)
  (cond
    ((immediate? datum)
     (emit-immediate datum))
    ((symbol? datum)
     (compile-expr (list 'string->symbol (symbol->string datum)) si env #f))
    ((pair? datum)
     (compile-expr (list 'cons
                         (list 'quote (car datum))
                         (list 'quote (cdr datum)))
                   si env #f))
    (else
     (error "Unknown quoted datum:" datum))))

;;; General Procedure Call (Tail Call vs Non-tail Call)
(define (compile-call proc args si env tail?)
  (let* ((num-args (length args))
         (cur-params-entry (assq '%num-params env))
         (cur-num-params (if cur-params-entry (cdr cur-params-entry) #f))
         (can-tco? (and tail? (if cur-num-params (= cur-num-params num-args) #f)))
         (frame-shift (align-frame-shift (if (= num-args 0)
                                             (- 0 si)
                                             (- (* 8 (- num-args 1)) si))))
         (aligned-si (if (= num-args 0)
                         (- 0 frame-shift)
                         (- (* 8 (- num-args 1)) frame-shift))))
    ;; 1. Evaluate arguments sequentially and place into temporary stack slots
    (let loop ((as args) (curr-si aligned-si))
      (if (not (null? as))
          (begin
            (compile-expr (car as) curr-si env #f)
            (emit (string-append "    mov [rsp " (offset->string curr-si) "], rax"))
            (loop (cdr as) (- curr-si 8)))))

    (let ((end-args-si (- aligned-si (* num-args 8))))
      ;; 2. Evaluate procedure expression -> RAX
      (compile-expr proc end-args-si env #f)
      (emit "    mov r10, rax") ; closure pointer into r10

      (if can-tco?
          ;; --- TAIL CALL OPTIMIZATION (TCO) ---
          ;; Overwrite current frame's parameter slots [rsp + 8 * (num-args - i)]
          (begin
            (let loop ((i 0))
              (if (< i num-args)
                  (let ((temp-offset (- aligned-si (* i 8)))
                        (param-offset (* 8 (- num-args i))))
                    (emit (string-append "    mov rdx, [rsp " (offset->string temp-offset) "]"))
                    (emit (string-append "    mov [rsp + " (number->string param-offset) "], rdx"))
                    (loop (+ i 1)))))
            (emit "    mov rdx, [r10 - 1]") ; extract code pointer from closure
            (emit "    jmp rdx"))          ; tail jump without new stack frame!

          ;; --- NON-TAIL CALL ---
          (begin
            (if (> frame-shift 0)
                (emit (string-append "    sub rsp, " (number->string frame-shift))))
            (emit "    mov rdx, [r10 - 1]")
            (emit "    call rdx")
            (if (> frame-shift 0)
                (emit (string-append "    add rsp, " (number->string frame-shift)))))))))

(define (compile-expr expr si env tail?)
  (cond
    ((immediate? expr)
     (emit-immediate expr))
    ((symbol? expr)
     (compile-variable expr env))
    ((pair? expr)
     (let ((op (car expr)))
       (cond
         ((zero-arg-prim? op)
          (compile-zero-arg op si env))
         ((eq? op '-)
          (if (null? (cddr expr))
              (compile-unary '- (cadr expr) si env)
              (compile-binop '- (cadr expr) (caddr expr) si env)))
         ((unary-prim? op)
          (compile-unary op (cadr expr) si env))
         ((binop-prim? op)
          (compile-binop op (cadr expr) (caddr expr) si env))
         ((triop-prim? op)
          (compile-triop op (cadr expr) (caddr expr) (cadddr expr) si env))
         ((eq? op 'cond)
          (compile-expr (desugar-cond (cdr expr)) si env tail?))
         ((eq? op 'case)
          (compile-expr (desugar-case (cadr expr) (cddr expr)) si env tail?))
         ((eq? op 'string-append)
          (compile-expr (desugar-string-append (cdr expr)) si env tail?))
         ((eq? op 'list)
          (compile-expr (desugar-list (cdr expr)) si env tail?))
         ((eq? op 'let*)
          (compile-expr (desugar-let* (cadr expr) (cddr expr)) si env tail?))
         ((eq? op 'let)
          (if (symbol? (cadr expr))
              (compile-expr (desugar-named-let expr) si env tail?)
              (compile-let (cadr expr) (make-body-expr (cddr expr)) si env tail?)))
         ((eq? op 'letrec)
          (compile-letrec (cadr expr) (make-body-expr (cddr expr)) si env tail?))
         ((eq? op 'lambda)
          (compile-lambda (cadr expr) (make-body-expr (cddr expr)) si env))
         ((eq? op 'if)
          (compile-if (cadr expr) (caddr expr) (cdddr expr) si env tail?))
         ((eq? op 'begin)
          (compile-begin (cdr expr) si env tail?))
         ((eq? op 'and)
          (compile-expr (desugar-and (cdr expr)) si env tail?))
         ((eq? op 'or)
          (compile-expr (desugar-or (cdr expr)) si env tail?))
         ((eq? op 'quote)
          (compile-quote (cadr expr) si env))
         (else
          ;; General procedure call
          (compile-call op (cdr expr) si env tail?)))))
    (else
     (error "Invalid syntax:" expr))))

(define (compile-program expr)
  (set-car! *label-counter* 0)
  (set-car! *symbol-counter* 0)
  (set-car! *symbol-table* '())
  (set-car! *string-counter* 0)
  (set-car! *strings* '())
  (set-car! *lambdas* '())
  (emit "    .intel_syntax noprefix")
  (emit "    .text")
  (emit "    .globl scheme_entry")
  (emit "    .type scheme_entry, @function")
  (emit "scheme_entry:")
  (emit "    push r12")
  (emit "    sub rsp, 8")
  (emit "    mov r12, rdi")          ; rdi contains heap_base from C runtime
  (compile-expr expr -8 '() #f)
  (emit "    add rsp, 8")
  (emit "    pop r12")
  (emit "    ret")
  ;; Emit all compiled lambda procedures (including nested ones)
  (let loop ()
    (if (not (null? (car *lambdas*)))
        (let ((fn (car (car *lambdas*))))
          (set-car! *lambdas* (cdr (car *lambdas*)))
          (fn)
          (loop))))
  ;; Emit all string literals in .rodata section
  (if (not (null? (car *strings*)))
      (begin
        (emit "    .section .rodata")
        (let loop ((ss (reverse (car *strings*))))
          (if (not (null? ss))
              (let ((entry (car ss)))
                (emit "    .p2align 3")
                (emit (string-append (car entry) ":"))
                (emit (string-append "    .asciz \"" (escape-gas-string (cdr entry)) "\""))
                (loop (cdr ss)))))))
  (emit "    .section .note.GNU-stack,\"\",@progbits"))
