;;; =======================================================================
;;; ULisp Compiler Pass 5: Native x86-64 Code Generation Pass
;;; Conforms to DSN-33 Architecture Specification
;;; Note: Codegen is purely a straightforward instruction emitter for flat
;;;       %function definitions and canonical primitive expressions.
;;; =======================================================================

(define (immediate? expr)
  (or (integer? expr)
      (boolean? expr)
      (char? expr)
      (null? expr)
      (string? expr)))

(define (emit-immediate expr)
  (cond
    ((integer? expr)
     (emit (string-append "    mov rax, " (number->string (* expr 4)))))
    ((boolean? expr)
     (if expr
         (emit "    mov rax, 0x6F")   ; #t
         (emit "    mov rax, 0x2F")))  ; #f
    ((char? expr)
     (let ((code (+ (* (char->integer expr) 256) 14)))
       (emit (string-append "    mov rax, " (number->string code)))))
    ((null? expr)
     (emit "    mov rax, 0x3F"))      ; '()
    ((string? expr)
     (emit-string-literal expr))))

(define (compile-zero-arg op si env)
  (let ((frame-shift (align-frame-shift (- si))))
    (case op
      ((read-char)
       (emit (string-append "    sub rsp, " (number->string frame-shift)))
       (emit "    call ulisp_read_char")
       (emit (string-append "    add rsp, " (number->string frame-shift))))
      ((peek-char)
       (emit (string-append "    sub rsp, " (number->string frame-shift)))
       (emit "    call ulisp_peek_char")
       (emit (string-append "    add rsp, " (number->string frame-shift)))))))

(define (compile-unary op arg si env)
  (compile-expr arg si env #f)
  (case op
    ((-)
     (emit "    neg rax"))
    ((fxadd1)
     (emit "    add rax, 4"))
    ((fxsub1)
     (emit "    sub rax, 4"))
    ((fixnum->char integer->char)
     (emit "    shl rax, 6")
     (emit "    or rax, 14"))
    ((char->fixnum char->integer)
     (emit "    shr rax, 6"))
    ((integer->symbol)
     (emit "    shl rax, 6")
     (emit "    or rax, 2"))
    ((symbol->integer)
     (emit "    shr rax, 6"))
    ((zero?)
     (emit "    cmp rax, 0")
     (emit-boolean))
    ((fixnum? integer? number?)
     (emit "    and al, 3")
     (emit "    cmp al, 0")
     (emit-boolean))
    ((boolean?)
     (emit "    mov rdx, rax")
     (emit "    xor rdx, 0x2F")
     (emit "    and rdx, -65")
     (emit "    cmp rdx, 0")
     (emit-boolean))
    ((char?)
     (emit "    and al, 0xFF")
     (emit "    cmp al, 14")
     (emit-boolean))
    ((null?)
     (emit "    cmp rax, 0x3F")
     (emit-boolean))
    ((not)
     (emit "    cmp rax, 0x2F")
     (emit-boolean))
    ((symbol?)
     (emit "    and al, 0xFF")
     (emit "    cmp al, 2")
     (emit-boolean))
    ((car)
     (emit "    mov rax, [rax - 1]"))
    ((cdr)
     (emit "    mov rax, [rax + 7]"))
    ((pair?)
     (emit "    and al, 3")
     (emit "    cmp al, 1")
     (emit-boolean))
    ((procedure?)
     ;; Heap object (tag 1)
     (emit "    and al, 3")
     (emit "    cmp al, 1")
     (emit-boolean))
    ((string?)
     (emit "    and al, 3")
     (emit "    cmp al, 3")
     (emit-boolean))
    ((write-char)
     (let ((frame-shift (align-frame-shift (- si))))
       (emit "    mov rdi, rax")
       (emit (string-append "    sub rsp, " (number->string frame-shift)))
       (emit "    call ulisp_write_char")
       (emit (string-append "    add rsp, " (number->string frame-shift)))))
    ((eof-object?)
     (emit "    cmp rax, 0x4F")
     (emit-boolean))

    ((make-string)
     (emit "    sar rax, 2")
     (emit "    mov rcx, rax")
     (emit "    add rax, 8")
     (emit "    and rax, -8")
     (emit "    mov rdx, r12")
     (emit "    add r12, rax")
     (emit "    mov byte ptr [rdx + rcx], 0")
     (emit "    lea rax, [rdx + 3]"))
    ((string-length)
     (let ((l-loop (unique-label "strlen_loop"))
           (l-done (unique-label "strlen_done")))
       (emit "    mov rdx, rax")
       (emit "    sub rdx, 3")
       (emit "    xor rax, rax")
       (emit (string-append l-loop ":"))
       (emit "    cmp byte ptr [rdx + rax], 0")
       (emit (string-append "    je " l-done))
       (emit "    inc rax")
       (emit (string-append "    jmp " l-loop))
       (emit (string-append l-done ":"))
       (emit "    shl rax, 2")))))

(define (compile-binop op e1 e2 si env)
  (compile-expr e1 si env #f)
  (emit (string-append "    mov [rsp " (offset->string si) "], rax"))
  (compile-expr e2 (- si 8) env #f)
  (case op
    ((+)
     (emit (string-append "    add rax, [rsp " (offset->string si) "]")))
    ((-)
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    sub rdx, rax")
     (emit "    mov rax, rdx"))
    ((*)
     (emit "    sar rax, 2")
     (emit (string-append "    imul rax, [rsp " (offset->string si) "]")))
    ((modulo)
     (emit "    mov rcx, rax")
     (emit (string-append "    mov rax, [rsp " (offset->string si) "]"))
     (emit "    sar rax, 2")
     (emit "    sar rcx, 2")
     (emit "    cqo")
     (emit "    idiv rcx")
     (emit "    mov rax, rdx")
     (emit "    shl rax, 2"))
    ((quotient /)
     (emit "    mov rcx, rax")
     (emit (string-append "    mov rax, [rsp " (offset->string si) "]"))
     (emit "    sar rax, 2")
     (emit "    sar rcx, 2")
     (emit "    cqo")
     (emit "    idiv rcx")
     (emit "    shl rax, 2"))
    ((string-ref)
     (emit "    sar rax, 2")
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    sub rdx, 3")
     (emit "    movzx rax, byte ptr [rdx + rax]")
     (emit "    shl rax, 8")
     (emit "    or rax, 14"))
    ((=)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "sete"))
    ((<)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setl"))
    ((<=)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setle"))
    ((>)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setg"))
    ((>=)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setge"))
    ((cons)
     (emit (string-append "    mov [rsp " (offset->string (- si 8)) "], rax"))
     (emit (string-append "    mov rax, [rsp " (offset->string si) "]"))
     (emit "    mov [r12], rax")
     (emit (string-append "    mov rax, [rsp " (offset->string (- si 8)) "]"))
     (emit "    mov [r12 + 8], rax")
     (emit "    lea rax, [r12 + 1]")
     (emit "    add r12, 16"))
    ((set-car!)
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    mov [rdx - 1], rax")
     (emit "    mov rax, 0x3F"))
    ((set-cdr!)
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    mov [rdx + 7], rax")
     (emit "    mov rax, 0x3F"))
    ((eq? char=?)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean))
    ((%closure-ref)
     (let ((idx e2))
       (let ((offset (- (* idx 8) 1)))
         (emit (string-append "    mov rax, [rsp " (offset->string si) "]"))
         (emit (string-append "    mov rax, [rax + " (number->string offset) "]")))))))

(define (compile-triop op e1 e2 e3 si env)
  (compile-expr e1 si env #f)
  (emit (string-append "    mov [rsp " (offset->string si) "], rax"))
  (compile-expr e2 (- si 8) env #f)
  (emit (string-append "    mov [rsp " (offset->string (- si 8)) "], rax"))
  (compile-expr e3 (- si 16) env #f)
  (case op
    ((string-set!)
     (emit "    shr rax, 8")
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    sub rdx, 3")
     (emit (string-append "    mov rcx, [rsp " (offset->string (- si 8)) "]"))
     (emit "    sar rcx, 2")
     (emit "    mov [rdx + rcx], al")
     (emit "    mov rax, 0x3F"))
    ((%closure-set!)
     (let ((idx-offset (- (* e2 8) 1)))
       (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
       (emit (string-append "    mov [rdx + " (number->string idx-offset) "], rax"))
       (emit "    mov rax, 0x3F")))))

(define (compile-make-closure expr si env)
  (let* ((label-arg (cadr expr))
         (label-str (if (and (pair? label-arg) (eq? (car label-arg) 'quote))
                        (symbol->string (cadr label-arg))
                        (if (symbol? label-arg)
                            (symbol->string label-arg)
                            (error "Invalid closure label:" label-arg))))
         (args (cddr expr))
         (num-args (length args))
         (closure-size (* (+ num-args 1) 8))
         (aligned-size (if (= (modulo closure-size 16) 0) closure-size (+ closure-size 8))))
    ;; 1. Evaluate arguments sequentially and place into temporary stack slots
    (let loop ((as args) (curr-si si))
      (if (not (null? as))
          (begin
            (compile-expr (car as) curr-si env #f)
            (emit (string-append "    mov [rsp " (offset->string curr-si) "], rax"))
            (loop (cdr as) (- curr-si 8)))))
    ;; 2. Allocate closure on heap at runtime (r12)
    ;; Store code pointer label into [r12]
    (emit (string-append "    lea rax, [rip + " label-str "]"))
    (emit "    mov [r12], rax")
    ;; 3. Copy captured arguments from stack to heap [r12 + 8 * i]
    (let loop ((i 1) (curr-si si))
      (if (<= i num-args)
          (begin
            (emit (string-append "    mov rax, [rsp " (offset->string curr-si) "]"))
            (emit (string-append "    mov [r12 + " (number->string (* i 8)) "], rax"))
            (loop (+ i 1) (- curr-si 8)))))
    ;; 4. Tag closure pointer with 0x01 (Heap object tag)
    (emit "    lea rax, [r12 + 1]")
    (emit (string-append "    add r12, " (number->string aligned-size)))))

(define (compile-closure-ref-expr expr si env)
  (let ((c-expr (cadr expr))
        (idx (caddr expr)))
    (compile-expr c-expr si env #f)
    (let ((offset (- (* idx 8) 1)))
      (emit (string-append "    mov rax, [rax + " (number->string offset) "]")))))

(define (compile-closure-set-expr expr si env)
  (let ((c-expr (cadr expr))
        (idx (caddr expr))
        (val-expr (cadddr expr)))
    ;; 1. Evaluate closure expression -> stack
    (compile-expr c-expr si env #f)
    (emit (string-append "    mov [rsp " (offset->string si) "], rax"))
    ;; 2. Evaluate val-expr -> rax
    (compile-expr val-expr (- si 8) env #f)
    ;; 3. Store into closure heap slot
    (let ((offset (- (* idx 8) 1)))
      (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
      (emit (string-append "    mov [rdx + " (number->string offset) "], rax"))
      (emit "    mov rax, 0x3F"))))

(define (compile-variable var env)
  (let ((binding (assq var env)))
    (if (not binding)
        (error "Unbound variable:" var)
        (let ((info (cdr binding)))
          (cond
            ((number? info)
             ;; Standard stack offset
             (emit (string-append "    mov rax, [rsp " (offset->string info) "]")))
            ((and (pair? info) (eq? (car info) 'param))
             ;; Lambda param offset (positive: +8, +16, ...)
             (emit (string-append "    mov rax, [rsp + " (number->string (cdr info)) "]")))
            ((and (pair? info) (eq? (car info) 'self))
             ;; Self closure reference in recursion
             (emit (string-append "    mov rax, [rsp " (offset->string (cdr info)) "]")))
            (else
             (error "Invalid binding format:" binding)))))))

(define (compile-let bindings body si env tail?)
  (let loop ((bs bindings)
             (curr-si si)
             (new-env env))
    (if (null? bs)
        (compile-expr body curr-si new-env tail?)
        (let* ((b (car bs))
               (var (car b))
               (val (cadr b)))
          (compile-expr val curr-si env #f)
          (emit (string-append "    mov [rsp " (offset->string curr-si) "], rax"))
          (loop (cdr bs)
                (- curr-si 8)
                (cons (cons var curr-si) new-env))))))

(define (compile-if test then else-opt si env tail?)
  (let ((else-label (unique-label "L_else"))
        (end-label (unique-label "L_end")))
    (compile-expr test si env #f)
    (emit "    cmp rax, 0x2F")
    (emit (string-append "    je " else-label))
    (compile-expr then si env tail?)
    (emit (string-append "    jmp " end-label))
    (emit (string-append else-label ":"))
    (if (null? else-opt)
        (emit "    mov rax, 0x2F")
        (compile-expr (car else-opt) si env tail?))
    (emit (string-append end-label ":"))))

(define (compile-begin exprs si env tail?)
  (if (null? exprs)
      (emit "    mov rax, 0x3F")
      (let loop ((es exprs))
        (if (null? (cdr es))
            (compile-expr (car es) si env tail?)
            (begin
              (compile-expr (car es) si env #f)
              (loop (cdr es)))))))

(define (compile-quote datum si env)
  (cond
    ((immediate? datum)
     (emit-immediate datum))
    ((pair? datum)
     (compile-expr (list 'cons
                         (list 'quote (car datum))
                         (list 'quote (cdr datum)))
                   si env #f))
    (else
     (error "Invalid quoted datum in codegen:" datum))))

;;; General Procedure Call (Tail Call vs Non-tail Call)
(define (compile-call proc args si env tail?)
  (let* ((num-args (length args))
         (cur-params-entry (assq '%num-params env))
         (cur-num-params (if cur-params-entry (cdr cur-params-entry) #f))
         (can-tco? (and tail? (if cur-num-params (= cur-num-params num-args) #f)))
         (frame-shift (align-frame-shift (if (= num-args 0)
                                             (- 0 si)
                                             (- (* 8 (- num-args 1)) si))))
         (aligned-si (if (= num-args 0)
                         (- 0 frame-shift)
                         (- (* 8 (- num-args 1)) frame-shift))))
    ;; 1. Evaluate arguments sequentially and place into temporary stack slots
    (let loop ((as args) (curr-si aligned-si))
      (if (not (null? as))
          (begin
            (compile-expr (car as) curr-si env #f)
            (emit (string-append "    mov [rsp " (offset->string curr-si) "], rax"))
            (loop (cdr as) (- curr-si 8)))))

    (let ((end-args-si (- aligned-si (* num-args 8))))
      ;; 2. Evaluate procedure expression -> RAX
      (compile-expr proc end-args-si env #f)
      (emit "    mov r10, rax") ; closure pointer into r10

      (if can-tco?
          ;; --- TAIL CALL OPTIMIZATION (TCO) ---
          ;; Overwrite current frame's parameter slots [rsp + 8 * (num-args - i)]
          (begin
            (let loop ((i 0))
              (if (< i num-args)
                  (let ((temp-offset (- aligned-si (* i 8)))
                        (param-offset (* 8 (- num-args i))))
                    (emit (string-append "    mov rdx, [rsp " (offset->string temp-offset) "]"))
                    (emit (string-append "    mov [rsp + " (number->string param-offset) "], rdx"))
                    (loop (+ i 1)))))
            (emit "    mov rdx, [r10 - 1]") ; extract code pointer from closure
            (emit "    jmp rdx"))          ; tail jump without new stack frame!

          ;; --- NON-TAIL CALL ---
          (begin
            (if (> frame-shift 0)
                (emit (string-append "    sub rsp, " (number->string frame-shift))))
            (emit "    mov rdx, [r10 - 1]")
            (emit "    call rdx")
            (if (> frame-shift 0)
                (emit (string-append "    add rsp, " (number->string frame-shift)))))))))

(define (compile-expr expr si env tail?)
  (cond
    ((immediate? expr)
     (emit-immediate expr))
    ((symbol? expr)
     (compile-variable expr env))
    ((pair? expr)
     (let ((op (car expr)))
       (cond
         ((zero-arg-prim? op)
          (compile-zero-arg op si env))
         ((eq? op '-)
          (if (null? (cddr expr))
              (compile-unary '- (cadr expr) si env)
              (compile-binop '- (cadr expr) (caddr expr) si env)))
         ((unary-prim? op)
          (compile-unary op (cadr expr) si env))
         ((binop-prim? op)
          (compile-binop op (cadr expr) (caddr expr) si env))
         ((triop-prim? op)
          (compile-triop op (cadr expr) (caddr expr) (cadddr expr) si env))
         ((eq? op '%make-closure)
          (compile-make-closure expr si env))
         ((eq? op '%closure-ref)
          (compile-closure-ref-expr expr si env))
         ((eq? op '%closure-set!)
          (compile-closure-set-expr expr si env))
         ((eq? op 'let)
          (compile-let (cadr expr) (caddr expr) si env tail?))
         ((eq? op 'if)
          (compile-if (cadr expr) (caddr expr) (cdddr expr) si env tail?))
         ((eq? op 'begin)
          (compile-begin (cdr expr) si env tail?))
         ((eq? op 'quote)
          (compile-quote (cadr expr) si env))
         (else
          ;; General procedure call
          (compile-call op (cdr expr) si env tail?)))))
    (else
     (error "Invalid syntax:" expr))))

;;; Compiles a single lifted %function definition
(define (compile-function fn)
  (let* ((label (cadr fn))
         (label-str (if (symbol? label) (symbol->string label) label))
         (params (caddr fn))
         (body (cadddr fn))
         (num-params (length params)))
    (emit "    .p2align 3")
    (emit (string-append label-str ":"))
    ;; Callee prologue: self closure pointer was in r10
    ;; Store self closure pointer at [rsp - 8]
    (emit "    mov [rsp - 8], r10")
    ;; Build callee env:
    ;; %self at [rsp - 8]
    ;; params at [rsp + 8 * (num-params - i)]
    (let* ((self-env (list (cons '%self (cons 'self -8))))
           (param-env
            (let loop ((ps params) (i 0) (acc '()))
              (if (null? ps) acc
                  (let ((offset (* 8 (- num-params i))))
                    (loop (cdr ps) (+ i 1)
                          (cons (cons (car ps) (cons 'param offset)) acc))))))
           (callee-env (cons (cons '%num-params num-params)
                             (append self-env param-env)))
           (callee-si -16))
      (compile-expr body callee-si callee-env #t)
      (emit "    ret"))))

(define (compile-program prog)
  (let ((funcs (cadr prog))
        (main-expr (caddr prog)))
    (set-car! *label-counter* 0)
    (set-car! *symbol-counter* 0)
    (set-car! *symbol-table* '())
    (set-car! *string-counter* 0)
    (set-car! *strings* '())
    (emit "    .intel_syntax noprefix")
    (emit "    .text")
    (emit "    .globl scheme_entry")
    (emit "    .type scheme_entry, @function")
    (emit "scheme_entry:")
    (emit "    push r12")
    (emit "    sub rsp, 8")
    (emit "    mov r12, rdi")          ; rdi contains heap_base from C runtime
    (compile-expr main-expr -8 '() #f)
    (emit "    add rsp, 8")
    (emit "    pop r12")
    (emit "    ret")
    ;; Emit all lifted procedure definitions in sequence
    (for-each compile-function funcs)
    ;; Emit all string literals in .rodata section
    (if (not (null? (car *strings*)))
        (begin
          (emit "    .section .rodata")
          (let loop ((ss (reverse (car *strings*))))
            (if (not (null? ss))
                (let ((entry (car ss)))
                  (emit "    .p2align 3")
                  (emit (string-append (car entry) ":"))
                  (emit (string-append "    .asciz \"" (escape-gas-string (cdr entry)) "\""))
                  (loop (cdr ss)))))))
    (emit "    .section .note.GNU-stack,\"\",@progbits")))
