#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: GraphQuery
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

from typing import Any

from core.structures.peg import (
    Choice,
    Lit,
    OneOrMore,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
    ZeroOrMore,
)
from graph.query_dsl import (
    EdgePattern,
    FilterCondition,
    GraphDSLQuery,
    NodePattern,
    _create_paren_node,
    _fold_graph_filter,
    _fold_graph_path,
)

# User header code


class GraphQueryParser(Parser[Any]):
    """Packrat PEG Parser for GraphQuery grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_query = RuleRef("query")
        self._r_path_query = RuleRef("path_query")
        self._r_filter_query = RuleRef("filter_query")
        self._r_path_pattern = RuleRef("path_pattern")
        self._r_node_pattern = RuleRef("node_pattern")
        self._r_simple_node = RuleRef("simple_node")
        self._r_paren_node = RuleRef("paren_node")
        self._r_node_body = RuleRef("node_body")
        self._r_label_part = RuleRef("label_part")
        self._r_edge_pattern = RuleRef("edge_pattern")
        self._r_arrow_bracket_arrow = RuleRef("arrow_bracket_arrow")
        self._r_bracket_out = RuleRef("bracket_out")
        self._r_bracket_in = RuleRef("bracket_in")
        self._r_bracket_both = RuleRef("bracket_both")
        self._r_arrow_out = RuleRef("arrow_out")
        self._r_arrow_in = RuleRef("arrow_in")
        self._r_arrow_both = RuleRef("arrow_both")
        self._r_colon_label = RuleRef("colon_label")
        self._r_filter_expr = RuleRef("filter_expr")
        self._r_filter_item = RuleRef("filter_item")
        self._r_and_kw = RuleRef("and_kw")
        self._r_ident = RuleRef("ident")
        self._r_ws = RuleRef("ws")
        self._r_opt_ws = RuleRef("opt_ws")

        self._r_query.define(
            Seq(
                self._r_opt_ws,
                Choice(self._r_path_query, self._r_filter_query),
                self._r_opt_ws,
            ).map(self._action_query_0)
        )
        self._r_path_query.define(self._r_path_pattern.map(self._action_path_query_1))
        self._r_filter_query.define(
            self._r_filter_expr.map(self._action_filter_query_2)
        )
        self._r_path_pattern.define(
            Seq(
                self._r_node_pattern,
                OneOrMore(
                    Seq(
                        self._r_opt_ws,
                        self._r_edge_pattern,
                        self._r_opt_ws,
                        self._r_node_pattern,
                    ).map(self._action_path_pattern_3)
                ),
            ).map(self._action_path_pattern_4)
        )
        self._r_node_pattern.define(Choice(self._r_paren_node, self._r_simple_node))
        self._r_simple_node.define(self._r_ident.map(self._action_simple_node_5))
        self._r_paren_node.define(
            Seq(
                Lit("("),
                self._r_opt_ws,
                Opt(self._r_node_body),
                self._r_opt_ws,
                Lit(")"),
            ).map(self._action_paren_node_6)
        )
        self._r_node_body.define(
            Seq(Opt(self._r_ident), Opt(self._r_label_part)).map(
                self._action_node_body_7
            )
        )
        self._r_label_part.define(
            Seq(Lit(":"), self._r_ident).map(self._action_label_part_8)
        )
        self._r_edge_pattern.define(
            Choice(
                self._r_arrow_bracket_arrow,
                self._r_bracket_out,
                self._r_bracket_in,
                self._r_bracket_both,
                self._r_arrow_out,
                self._r_arrow_in,
                self._r_arrow_both,
            )
        )
        self._r_arrow_bracket_arrow.define(
            Seq(
                Lit("->"),
                self._r_opt_ws,
                Lit("["),
                self._r_opt_ws,
                Opt(self._r_colon_label),
                self._r_opt_ws,
                Lit("]"),
                self._r_opt_ws,
                Lit("->"),
            ).map(self._action_arrow_bracket_arrow_9)
        )
        self._r_bracket_out.define(
            Seq(
                Lit("-["),
                self._r_opt_ws,
                Opt(self._r_colon_label),
                self._r_opt_ws,
                Lit("]->"),
            ).map(self._action_bracket_out_10)
        )
        self._r_bracket_in.define(
            Seq(
                Lit("<-["),
                self._r_opt_ws,
                Opt(self._r_colon_label),
                self._r_opt_ws,
                Lit("]-"),
            ).map(self._action_bracket_in_11)
        )
        self._r_bracket_both.define(
            Seq(
                Lit("-["),
                self._r_opt_ws,
                Opt(self._r_colon_label),
                self._r_opt_ws,
                Lit("]-"),
            ).map(self._action_bracket_both_12)
        )
        self._r_arrow_out.define(Lit("->").map(self._action_arrow_out_13))
        self._r_arrow_in.define(Lit("<-").map(self._action_arrow_in_14))
        self._r_arrow_both.define(Lit("--").map(self._action_arrow_both_15))
        self._r_colon_label.define(
            Seq(Opt(Lit(":")), self._r_ident).map(self._action_colon_label_16)
        )
        self._r_filter_expr.define(
            Seq(
                self._r_filter_item,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws,
                        self._r_and_kw,
                        self._r_opt_ws,
                        self._r_filter_item,
                    ).map(self._action_filter_expr_17)
                ),
            ).map(self._action_filter_expr_18)
        )
        self._r_filter_item.define(
            Seq(self._r_ident, Lit(":"), self._r_ident).map(self._action_filter_item_19)
        )
        self._r_and_kw.define(Reg("(?i)\\bAND\\b"))
        self._r_ident.define(Reg("[a-zA-Z0-9_\\-]+"))
        self._r_ws.define(Reg("[ \\t\\r\\n]+"))
        self._r_opt_ws.define(Reg("[ \\t\\r\\n]*"))

        self.root_parser: Parser[Any] = self._r_query

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_query_0(val: Any) -> Any:
        q = val[1]
        return q

    @staticmethod
    def _action_path_query_1(val: Any) -> Any:
        path = val
        return GraphDSLQuery(kind="path", path=path)

    @staticmethod
    def _action_filter_query_2(val: Any) -> Any:
        f = val
        return GraphDSLQuery(kind="filter", filter_q=f)

    @staticmethod
    def _action_path_pattern_3(val: Any) -> Any:
        edge = val[1]
        n = val[3]
        return (edge, n)

    @staticmethod
    def _action_path_pattern_4(val: Any) -> Any:
        start = val[0]
        rest = val[1]
        return _fold_graph_path(start, rest)

    @staticmethod
    def _action_simple_node_5(val: Any) -> Any:
        name = val
        return NodePattern(name_or_id=name)

    @staticmethod
    def _action_paren_node_6(val: Any) -> Any:
        body = val[2]
        return _create_paren_node(body)

    @staticmethod
    def _action_node_body_7(val: Any) -> Any:
        alias = val[0]
        lbl = val[1]
        return (alias, lbl)

    @staticmethod
    def _action_label_part_8(val: Any) -> Any:
        id = val[1]
        return id

    @staticmethod
    def _action_arrow_bracket_arrow_9(val: Any) -> Any:
        lbl = val[4]
        return EdgePattern(label=lbl, direction="out")

    @staticmethod
    def _action_bracket_out_10(val: Any) -> Any:
        lbl = val[2]
        return EdgePattern(label=lbl, direction="out")

    @staticmethod
    def _action_bracket_in_11(val: Any) -> Any:
        lbl = val[2]
        return EdgePattern(label=lbl, direction="in")

    @staticmethod
    def _action_bracket_both_12(val: Any) -> Any:
        lbl = val[2]
        return EdgePattern(label=lbl, direction="both")

    @staticmethod
    def _action_arrow_out_13(val: Any) -> Any:
        return EdgePattern(direction="out")

    @staticmethod
    def _action_arrow_in_14(val: Any) -> Any:
        return EdgePattern(direction="in")

    @staticmethod
    def _action_arrow_both_15(val: Any) -> Any:
        return EdgePattern(direction="both")

    @staticmethod
    def _action_colon_label_16(val: Any) -> Any:
        id = val[1]
        return id

    @staticmethod
    def _action_filter_expr_17(val: Any) -> Any:
        itm = val[3]
        return itm

    @staticmethod
    def _action_filter_expr_18(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return _fold_graph_filter(first, rest)

    @staticmethod
    def _action_filter_item_19(val: Any) -> Any:
        k = val[0]
        v = val[2]
        return FilterCondition(key=k, value=v)
