#!/usr/bin/env python3
"""
Search Subsystem for arXiv Security Papers.
Architected into 2 decoupled paradigms:
- engine: Embedded Core Search Engine (Analysis, Inverted Index, VByte, BM25, Queries, Sorter, SpellCheck)
- platform: Enterprise Search Platform (ManagedSchema, Handlers, Elevation, Facets, Caches, Distributed)
- eval / vector / utils: Search evaluation, vector storage integration, and profiler
"""

# 2-Tier Modular Subpackages
from . import engine, eval, platform, utils, vector
from .engine import (
    Analyzer,
    BM25Similarity,
    BooleanClause,
    BooleanQuery,
    BoostQuery,
    CharFilter,
    CJKAnalyzer,
    CJKBigramTokenizer,
    DeletedDocsBitset,
    Directory,
    DocValues,
    FSDirectory,
    FuzzyQuery,
    HTMLStripCharFilter,
    IndexInput,
    IndexOutput,
    LowerCaseFilter,
    MappingCharFilter,
    MatchAllDocsQuery,
    Occur,
    PhraseQuery,
    PorterStemFilter,
    PostingEntry,
    PostingsList,
    Query,
    RAMDirectory,
    ScoreDoc,
    Segment,
    Similarity,
    Sorter,
    SortField,
    SortOrder,
    SpellChecker,
    StandardAnalyzer,
    StandardTokenizer,
    StopFilter,
    StoredFields,
    SynonymFilter,
    TermQuery,
    TieredMergePolicy,
    TokenFilter,
    Tokenizer,
    TopDocs,
    TopDocsCollector,
    WildcardQuery,
    decode_gap_vbyte,
    decode_vbyte,
    encode_gap_vbyte,
    encode_vbyte,
)
from .platform import (
    CopyField,
    CoreAdmin,
    DistributedSearcher,
    DocumentCache,
    DynamicField,
    DynamicHighlighter,
    ElevationRule,
    FacetEngine,
    FastVectorHighlighter,
    FieldDefinition,
    FieldFacet,
    FieldType,
    FilterCache,
    IndexSnapshot,
    LRUCache,
    ManagedSchema,
    QueryElevationComponent,
    QueryResultCache,
    RangeFacet,
    SelectHandler,
    ShardHandler,
    ShardResponse,
    SolrCache,
    UpdateHandler,
)
from .vector_engine import VectorEngine

__all__ = [
    # Top-level packages
    "engine",
    "platform",
    "vector",
    "eval",
    "utils",
    # Engine (Lucene Paradigm)
    "CharFilter",
    "HTMLStripCharFilter",
    "MappingCharFilter",
    "Tokenizer",
    "StandardTokenizer",
    "CJKBigramTokenizer",
    "TokenFilter",
    "LowerCaseFilter",
    "StopFilter",
    "PorterStemFilter",
    "SynonymFilter",
    "Analyzer",
    "StandardAnalyzer",
    "CJKAnalyzer",
    "encode_vbyte",
    "decode_vbyte",
    "encode_gap_vbyte",
    "decode_gap_vbyte",
    "PostingEntry",
    "PostingsList",
    "DocValues",
    "StoredFields",
    "DeletedDocsBitset",
    "Segment",
    "TieredMergePolicy",
    "Similarity",
    "BM25Similarity",
    "Occur",
    "Query",
    "BoostQuery",
    "MatchAllDocsQuery",
    "TermQuery",
    "PhraseQuery",
    "WildcardQuery",
    "FuzzyQuery",
    "BooleanClause",
    "BooleanQuery",
    "SpellChecker",
    "SortOrder",
    "SortField",
    "Sorter",
    "ScoreDoc",
    "TopDocs",
    "TopDocsCollector",
    "IndexOutput",
    "IndexInput",
    "Directory",
    "RAMDirectory",
    "FSDirectory",
    # Platform (Solr Paradigm)
    "FieldType",
    "FieldDefinition",
    "DynamicField",
    "CopyField",
    "ManagedSchema",
    "SelectHandler",
    "UpdateHandler",
    "ElevationRule",
    "QueryElevationComponent",
    "FieldFacet",
    "RangeFacet",
    "FacetEngine",
    "DynamicHighlighter",
    "FastVectorHighlighter",
    "LRUCache",
    "FilterCache",
    "QueryResultCache",
    "DocumentCache",
    "SolrCache",
    "ShardResponse",
    "ShardHandler",
    "DistributedSearcher",
    "IndexSnapshot",
    "CoreAdmin",
    # Integrated Hybrid Facade
    "VectorEngine",
]
