#!/usr/bin/env python3
"""
Search Package for arXiv Security Papers.
Modularized 2-tier search architecture:
- core: Lucene-equivalent core search engine (analysis, store, index, search)
- server: Solr-equivalent enterprise search server (schema, handler, facet, highlight, cache)
- legacy functional subpackages: ingestion, query, ranking, presentation, vector_engine
"""

# Subpackages
from . import core, ingestion, presentation, query, ranking, server, vector
from .core import (
    Analyzer,
    BM25Similarity,
    BooleanClause,
    BooleanQuery,
    CharFilter,
    DeletedDocsBitset,
    Directory,
    DocValues,
    FSDirectory,
    FuzzyQuery,
    HTMLStripCharFilter,
    LowerCaseFilter,
    PhraseQuery,
    PostingsList,
    PrefixQuery,
    RAMDirectory,
    ScoreDoc,
    SegmentInfo,
    Similarity,
    StandardTokenizer,
    StopWordFilter,
    StoredFields,
    TermQuery,
    Token,
    TokenFilter,
    Tokenizer,
    TopDocs,
    TopDocsCollector,
    UnicodeNormalizeCharFilter,
)
from .ingestion import (
    FacetedIndex,
    FieldType,
    FMIndex,
    MultiFieldPostingsIndex,
    RAPTORTreeIndex,
    SearchAnalyzer,
    TokenOffset,
)
from .presentation import DynamicHighlighter
from .query import (
    EnterpriseQueryParser,
    QueryClause,
    QueryContext,
    QuerySemanticCache,
    SynonymExpander,
)
from .ranking import CitationNetworkIndex, KnowledgeGraphIndex, ProximityGraphIndex
from .server import (
    FacetEngine,
    FastVectorHighlighter,
    FieldDefinition,
    FilterCache,
    LRUCache,
    ManagedIndexSchema,
    QueryResultCache,
    SelectHandler,
)
from .utils import extract_abstract_from_okf
from .vector import (
    DeterministicEmbedding,
    HNSWIndex,
    RRFHybridScorer,
    VectorStorage,
    VectorStorageSecurityError,
)
from .vector_engine import VectorEngine

__all__ = [
    "Analyzer",
    "BM25Similarity",
    "BooleanClause",
    "BooleanQuery",
    "CharFilter",
    "CitationNetworkIndex",
    "DeletedDocsBitset",
    "DeterministicEmbedding",
    "Directory",
    "DocValues",
    "DynamicHighlighter",
    "EnterpriseQueryParser",
    "FacetEngine",
    "FacetedIndex",
    "FastVectorHighlighter",
    "FieldDefinition",
    "FieldType",
    "FilterCache",
    "FMIndex",
    "FSDirectory",
    "FuzzyQuery",
    "HNSWIndex",
    "HTMLStripCharFilter",
    "KnowledgeGraphIndex",
    "LRUCache",
    "LowerCaseFilter",
    "ManagedIndexSchema",
    "MultiFieldPostingsIndex",
    "PhraseQuery",
    "PostingsList",
    "PrefixQuery",
    "ProximityGraphIndex",
    "Query",
    "QueryClause",
    "QueryContext",
    "QueryResultCache",
    "QuerySemanticCache",
    "RAMDirectory",
    "RAPTORTreeIndex",
    "RRFHybridScorer",
    "ScoreDoc",
    "SearchAnalyzer",
    "SegmentInfo",
    "SelectHandler",
    "Similarity",
    "StandardTokenizer",
    "StopWordFilter",
    "StoredFields",
    "SynonymExpander",
    "TermQuery",
    "Token",
    "TokenFilter",
    "TokenOffset",
    "Tokenizer",
    "TopDocs",
    "TopDocsCollector",
    "UnicodeNormalizeCharFilter",
    "VectorEngine",
    "VectorStorage",
    "VectorStorageSecurityError",
    "core",
    "extract_abstract_from_okf",
    "ingestion",
    "presentation",
    "query",
    "ranking",
    "server",
    "vector",
]
