;;; =======================================================================
;;; ULisp (Underlying LISP) Compiler - Self-Hosting Bootstrap Engine
;;; Conforms to DSN-33 Architecture Specification
;;; =======================================================================

;;; Standard Helper Procedures (Self-hosting primitives)
(define (fixnum->char n) (integer->char n))
(define (char->fixnum c) (char->integer c))
(define (safe-car x) (if (pair? x) (car x) '()))
(define (safe-cdr x) (if (pair? x) (cdr x) '()))


(define (car* x) (car x))
(define (cadr x) (safe-car (safe-cdr x)))
(define (cddr x) (safe-cdr (safe-cdr x)))
(define (cdar x) (safe-cdr (safe-car x)))
(define (caar x) (safe-car (safe-car x)))
(define (caddr x) (safe-car (safe-cdr (safe-cdr x))))
(define (cdddr x) (safe-cdr (safe-cdr (safe-cdr x))))
(define (cadar x) (safe-car (safe-cdr (safe-car x))))
(define (cadddr x) (safe-car (safe-cdr (safe-cdr (safe-cdr x)))))

(define (memq item ls)
  (cond
    ((not (pair? ls)) #f)
    ((eq? (car ls) item) ls)
    (else (memq item (cdr ls)))))

(define (assq item ls)
  (cond
    ((not (pair? ls)) #f)
    ((not (pair? (car ls))) (assq item (cdr ls)))
    ((eq? (caar ls) item) (car ls))
    (else (assq item (cdr ls)))))

(define (length ls)
  (let loop ((l ls) (n 0))
    (if (null? l)
        n
        (loop (cdr l) (+ n 1)))))

(define (reverse ls)
  (let loop ((l ls) (acc '()))
    (if (null? l)
        acc
        (loop (cdr l) (cons (car l) acc)))))

(define (append l1 l2)
  (if (null? l1)
      l2
      (cons (car l1) (append (cdr l1) l2))))

(define (map f ls)
  (if (null? ls)
      '()
      (cons (f (car ls)) (map f (cdr ls)))))

(define (error msg val)
  (display msg)
  (display " ")
  (display val)
  (newline)
  val)

(define (desugar-list args)
  (if (null? args)
      ''()
      (cons 'cons (cons (car args) (cons (desugar-list (cdr args)) '())))))

;;; Boxed global counters and tables for closure sharing
(define *label-counter* (cons 0 '()))
(define (unique-label prefix)
  (let ((l (string-append "." prefix "_" (number->string (car *label-counter*)))))
    (set-car! *label-counter* (+ (car *label-counter*) 1))
    l))

(define *symbol-counter* (cons 0 '()))
(define (unique-symbol prefix)
  (let ((s (string->symbol (string-append prefix (number->string (car *symbol-counter*))))))
    (set-car! *symbol-counter* (+ (car *symbol-counter*) 1))
    s))

(define *symbol-table* (cons '() '()))
(define (intern-symbol sym)
  (let ((entry (assq sym (car *symbol-table*))))
    (if entry
        (cdr entry)
        (let ((id (+ (* (length (car *symbol-table*)) 256) 2)))
          (set-car! *symbol-table* (cons (cons sym id) (car *symbol-table*)))
          id))))

(define *string-counter* (cons 0 '()))
(define *strings* (cons '() '()))
(define (intern-string str)
  (let ((label (string-append ".L_str_" (number->string (car *string-counter*)))))
    (set-car! *string-counter* (+ (car *string-counter*) 1))
    (set-car! *strings* (cons (cons label str) (car *strings*)))
    label))

(define (emit-string-literal str)
  (let ((label (intern-string str)))
    (emit (string-append "    lea rax, [rip + " label " + 3]"))))

;;; Accumulated compiled lambda code blocks (boxed list)
(define *lambdas* (cons '() '()))

(define (emit line)
  (display line)
  (newline))

(define (emit-boolean-from-set set-inst)
  (emit (string-append "    " set-inst " al"))
  (emit "    movzx eax, al")
  (emit "    shl rax, 6")
  (emit "    add rax, 0x2F"))

(define (emit-boolean)
  (emit-boolean-from-set "sete"))

(define (offset->string offset)
  (if (< offset 0)
      (string-append "- " (number->string (- 0 offset)))
      (string-append "+ " (number->string offset))))

(define (align-frame-shift needed)
  (if (= (modulo needed 16) 8)
      needed
      (+ needed 8)))

(define (immediate? expr)
  (or (integer? expr)
      (boolean? expr)
      (char? expr)
      (null? expr)
      (string? expr)))

(define (emit-immediate expr)
  (cond
    ((integer? expr)
     (emit (string-append "    mov rax, " (number->string (* expr 4)))))
    ((boolean? expr)
     (if expr
         (emit "    mov rax, 0x6F")   ; #t
         (emit "    mov rax, 0x2F")))  ; #f
    ((char? expr)
     (let ((code (+ (* (char->integer expr) 256) 14)))
       (emit (string-append "    mov rax, " (number->string code)))))
    ((null? expr)
     (emit "    mov rax, 0x3F"))      ; '()
    ((string? expr)
     (emit-string-literal expr))))

(define (zero-arg-prim? op)
  (memq op '(read-char peek-char)))

(define (unary-prim? op)
  (memq op '(fxadd1 fxsub1 fixnum->char char->fixnum integer->char char->integer
             integer->symbol symbol->integer
             zero? fixnum? integer? number? boolean? char? null? not symbol?
             car cdr pair? procedure? string?
             write-char eof-object?
             make-string string-length)))

(define (binop-prim? op)
  (memq op '(+ - * = < <= > >= modulo quotient / string-ref cons set-car! set-cdr! eq? char=?)))


(define (triop-prim? op)
  (memq op '(string-set!)))

(define (compile-zero-arg op si env)
  (let ((frame-shift (align-frame-shift (- si))))
    (case op
      ((read-char)
       (emit (string-append "    sub rsp, " (number->string frame-shift)))
       (emit "    call ulisp_read_char")
       (emit (string-append "    add rsp, " (number->string frame-shift))))
      ((peek-char)
       (emit (string-append "    sub rsp, " (number->string frame-shift)))
       (emit "    call ulisp_peek_char")
       (emit (string-append "    add rsp, " (number->string frame-shift)))))))


(define (compile-unary op arg si env)
  (compile-expr arg si env #f)
  (case op
    ((-)
     (emit "    neg rax"))
    ((fxadd1)
     (emit "    add rax, 4"))
    ((fxsub1)
     (emit "    sub rax, 4"))
    ((fixnum->char integer->char)
     (emit "    shl rax, 6")
     (emit "    or rax, 14"))
    ((char->fixnum char->integer)
     (emit "    shr rax, 6"))
    ((integer->symbol)
     (emit "    shl rax, 6")
     (emit "    or rax, 2"))
    ((symbol->integer)
     (emit "    shr rax, 6"))
    ((zero?)
     (emit "    cmp rax, 0")
     (emit-boolean))
    ((fixnum? integer? number?)
     (emit "    and al, 3")
     (emit "    cmp al, 0")
     (emit-boolean))
    ((boolean?)
     (emit "    mov rdx, rax")
     (emit "    xor rdx, 0x2F")
     (emit "    and rdx, -65")
     (emit "    cmp rdx, 0")
     (emit-boolean))
    ((char?)
     (emit "    and al, 0xFF")
     (emit "    cmp al, 14")
     (emit-boolean))
    ((null?)
     (emit "    cmp rax, 0x3F")
     (emit-boolean))
    ((not)
     (emit "    cmp rax, 0x2F")
     (emit-boolean))
    ((symbol?)
     (emit "    and al, 0xFF")
     (emit "    cmp al, 2")
     (emit-boolean))
    ((car)
     (emit "    mov rax, [rax - 1]"))
    ((cdr)
     (emit "    mov rax, [rax + 7]"))
    ((pair?)
     (emit "    and al, 3")
     (emit "    cmp al, 1")
     (emit-boolean))
    ((procedure?)
     ;; Heap object (tag 1)
     (emit "    and al, 3")
     (emit "    cmp al, 1")
     (emit-boolean))
    ((string?)
     (emit "    and al, 3")
     (emit "    cmp al, 3")
     (emit-boolean))
    ((write-char)
     (let ((frame-shift (align-frame-shift (- si))))
       (emit "    mov rdi, rax")
       (emit (string-append "    sub rsp, " (number->string frame-shift)))
       (emit "    call ulisp_write_char")
       (emit (string-append "    add rsp, " (number->string frame-shift)))))
    ((eof-object?)
     (emit "    cmp rax, 0x4F")
     (emit-boolean))

    ((make-string)
     (emit "    sar rax, 2")
     (emit "    mov rcx, rax")
     (emit "    add rax, 8")
     (emit "    and rax, -8")
     (emit "    mov rdx, r12")
     (emit "    add r12, rax")
     (emit "    mov byte ptr [rdx + rcx], 0")
     (emit "    lea rax, [rdx + 3]"))
    ((string-length)
     (let ((l-loop (unique-label "strlen_loop"))
           (l-done (unique-label "strlen_done")))
       (emit "    mov rdx, rax")
       (emit "    sub rdx, 3")
       (emit "    xor rax, rax")
       (emit (string-append l-loop ":"))
       (emit "    cmp byte ptr [rdx + rax], 0")
       (emit (string-append "    je " l-done))
       (emit "    inc rax")
       (emit (string-append "    jmp " l-loop))
       (emit (string-append l-done ":"))
       (emit "    shl rax, 2")))))

(define (compile-binop op e1 e2 si env)
  (compile-expr e1 si env #f)
  (emit (string-append "    mov [rsp " (offset->string si) "], rax"))
  (compile-expr e2 (- si 8) env #f)
  (case op
    ((+)
     (emit (string-append "    add rax, [rsp " (offset->string si) "]")))
    ((-)
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    sub rdx, rax")
     (emit "    mov rax, rdx"))
    ((*)
     (emit "    sar rax, 2")
     (emit (string-append "    imul rax, [rsp " (offset->string si) "]")))
    ((modulo)
     (emit "    mov rcx, rax")
     (emit (string-append "    mov rax, [rsp " (offset->string si) "]"))
     (emit "    sar rax, 2")
     (emit "    sar rcx, 2")
     (emit "    cqo")
     (emit "    idiv rcx")
     (emit "    mov rax, rdx")
     (emit "    shl rax, 2"))
    ((quotient /)
     (emit "    mov rcx, rax")
     (emit (string-append "    mov rax, [rsp " (offset->string si) "]"))
     (emit "    sar rax, 2")
     (emit "    sar rcx, 2")
     (emit "    cqo")
     (emit "    idiv rcx")
     (emit "    shl rax, 2"))
    ((string-ref)
     (emit "    sar rax, 2")
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    sub rdx, 3")
     (emit "    movzx rax, byte ptr [rdx + rax]")
     (emit "    shl rax, 8")
     (emit "    or rax, 14"))
    ((=)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "sete"))
    ((<)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setl"))
    ((<=)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setle"))
    ((>)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setg"))
    ((>=)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean-from-set "setge"))
    ((cons)
     (emit (string-append "    mov [rsp " (offset->string (- si 8)) "], rax"))
     (emit (string-append "    mov rax, [rsp " (offset->string si) "]"))
     (emit "    mov [r12], rax")
     (emit (string-append "    mov rax, [rsp " (offset->string (- si 8)) "]"))
     (emit "    mov [r12 + 8], rax")
     (emit "    lea rax, [r12 + 1]")
     (emit "    add r12, 16"))
    ((set-car!)
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    mov [rdx - 1], rax")
     (emit "    mov rax, 0x3F"))
    ((set-cdr!)
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    mov [rdx + 7], rax")
     (emit "    mov rax, 0x3F"))
    ((eq? char=?)
     (emit (string-append "    cmp [rsp " (offset->string si) "], rax"))
     (emit-boolean))))



(define (compile-triop op e1 e2 e3 si env)
  (compile-expr e1 si env #f)
  (emit (string-append "    mov [rsp " (offset->string si) "], rax"))
  (compile-expr e2 (- si 8) env #f)
  (emit (string-append "    mov [rsp " (offset->string (- si 8)) "], rax"))
  (compile-expr e3 (- si 16) env #f)
  (case op
    ((string-set!)
     (emit "    shr rax, 8")
     (emit (string-append "    mov rdx, [rsp " (offset->string si) "]"))
     (emit "    sub rdx, 3")
     (emit (string-append "    mov rcx, [rsp " (offset->string (- si 8)) "]"))
     (emit "    sar rcx, 2")
     (emit "    mov [rdx + rcx], al")
     (emit "    mov rax, 0x3F"))))


(define (desugar-string-append args)
  (cond
    ((null? args) "")
    ((null? (cdr args)) (car args))
    (else
     (list 'string-append2 (car args) (desugar-string-append (cdr args))))))

;;; Static free variable analysis
(define (set-diff s1 s2)
  (cond
    ((null? s1) '())
    ((memq (car s1) s2) (set-diff (cdr s1) s2))
    (else (cons (car s1) (set-diff (cdr s1) s2)))))

(define (set-union s1 s2)
  (cond
    ((null? s1) s2)
    ((memq (car s1) s2) (set-union (cdr s1) s2))
    (else (cons (car s1) (set-union (cdr s1) s2)))))

(define (desugar-cond clauses)
  (if (null? clauses)
      #f
      (let ((c (car clauses)))
        (if (eq? (car c) 'else)
            (cons 'begin (cdr c))
            (list 'if (car c)
                  (cons 'begin (cdr c))
                  (desugar-cond (cdr clauses)))))))

(define (desugar-case key clauses)
  (let ((k-var (unique-symbol "case_key_")))
    (list 'let (list (list k-var key))
          (let loop ((cls clauses))
            (if (null? cls)
                #f
                (let ((c (car cls)))
                  (if (eq? (car c) 'else)
                      (cons 'begin (cdr c))
                      (list 'if (list 'memq k-var (list 'quote (car c)))
                            (cons 'begin (cdr c))
                            (loop (cdr cls))))))))))

(define (make-body-expr bodies)
  (cond
    ((null? bodies) (list 'begin))
    ((null? (cdr bodies)) (car bodies))
    (else (cons 'begin bodies))))

(define (desugar-let* bindings bodies)
  (if (null? bindings)
      (make-body-expr bodies)
      (list 'let (list (car bindings))
            (desugar-let* (cdr bindings) bodies))))

(define (desugar-named-let expr)
  (let* ((name (cadr expr))
         (bindings (caddr expr))
         (bodies (cdddr expr))
         (params (map car* bindings))
         (inits (map cadr bindings)))
    (list 'letrec
          (list (list name (cons 'lambda (cons params bodies))))
          (cons name inits))))

(define (has-symbol? datum)
  (cond
    ((symbol? datum) #t)
    ((pair? datum)
     (or (has-symbol? (car datum))
         (has-symbol? (cdr datum))))
    (else #f)))

(define (free-vars expr bound)
  (cond
    ((symbol? expr)
     (if (memq expr bound) '() (list expr)))
    ((pair? expr)
     (let ((op (car expr)))
       (case op
         ((quote)
          (if (has-symbol? (cadr expr))
              (if (memq 'string->symbol bound) '() '(string->symbol))
              '()))
         ((case)
          (free-vars (desugar-case (cadr expr) (cddr expr)) bound))
         ((if)
          (set-union (free-vars (cadr expr) bound)
                     (set-union (free-vars (caddr expr) bound)
                                (if (null? (cdddr expr)) '() (free-vars (cadddr expr) bound)))))
         ((begin and or list)
          (let loop ((es (cdr expr)) (acc '()))
            (if (null? es) acc
                (loop (cdr es) (set-union acc (free-vars (car es) bound))))))
         ((cond)
          (free-vars (desugar-cond (cdr expr)) bound))
         ((string-append)
          (free-vars (desugar-string-append (cdr expr)) bound))
         ((let*)
          (free-vars (desugar-let* (cadr expr) (cddr expr)) bound))
         ((let)
          (if (symbol? (cadr expr))
              (free-vars (desugar-named-let expr) bound)
              (let* ((bindings (cadr expr))
                     (body (make-body-expr (cddr expr)))
                     (new-bound (set-union (map car* bindings) bound))
                     (val-frees (let loop ((bs bindings) (acc '()))
                                  (if (null? bs) acc
                                      (loop (cdr bs) (set-union acc (free-vars (cadar bs) bound)))))))
                (set-union val-frees (free-vars body new-bound)))))
         ((letrec)
          (let* ((bindings (cadr expr))
                 (body (make-body-expr (cddr expr)))
                 (new-bound (set-union (map car* bindings) bound)))
            (let loop ((bs bindings) (acc (free-vars body new-bound)))
              (if (null? bs) acc
                  (loop (cdr bs) (set-union acc (free-vars (cadar bs) new-bound)))))))
         ((lambda)
          (let* ((params (cadr expr))
                 (body (make-body-expr (cddr expr)))
                 (new-bound (set-union params bound)))
            (free-vars body new-bound)))
         (else
          (cond
            ((zero-arg-prim? op) '())
            ((or (unary-prim? op) (or (binop-prim? op) (triop-prim? op)))
             (let loop ((es (cdr expr)) (acc '()))
               (if (null? es) acc
                   (loop (cdr es) (set-union acc (free-vars (car es) bound))))))
            (else
             (let loop ((es expr) (acc '()))
               (if (null? es) acc
                   (loop (cdr es) (set-union acc (free-vars (car es) bound)))))))))))
    (else '())))

(define (compile-lambda-named name params body si env)
  (let* ((label (unique-label "L_lambda"))
         (bound-vars (if name (cons name params) params))
         (frees (free-vars body bound-vars))
         (num-frees (length frees))
         (num-params (length params))
         (closure-size (* (+ num-frees 1) 8))
         (aligned-size (if (= (modulo closure-size 16) 0) closure-size (+ closure-size 8))))
    ;; 1. Compile and save lambda procedure body into *lambdas*
    (set-car! *lambdas*
              (cons (lambda ()
                      (emit "    .p2align 3")
                      (emit (string-append label ":"))
                      ;; Callee prologue: self closure pointer was in r10
                      ;; Store self closure pointer at [rsp - 8]
                      (let ((self-offset -8))
                        (emit "    mov [rsp - 8], r10")
                        ;; Build callee env:
                        ;; params at [rsp + 8 * (num-params - i)] for i = 0..(num-params - 1)
                        (let* ((param-env
                                (let loop ((ps params) (i 0) (acc '()))
                                  (if (null? ps) acc
                                      (let ((offset (* 8 (- num-params i))))
                                        (loop (cdr ps) (+ i 1)
                                              (cons (cons (car ps) (cons 'param offset)) acc))))))
                               ;; free vars accessed via self closure saved at [rsp - 8]
                               (free-env
                                (let loop ((fs frees) (f-idx 1) (acc '()))
                                  (if (null? fs) acc
                                      (loop (cdr fs) (+ f-idx 1)
                                            (cons (cons (car fs) (cons 'free (cons self-offset (* f-idx 8)))) acc)))))
                               (self-binding (if name (list (cons name (cons 'self self-offset))) '()))
                               (callee-env (cons (cons '%num-params num-params)
                                                 (append self-binding (append param-env free-env))))
                               (callee-si -16))
                          (compile-expr body callee-si callee-env #t)
                          (emit "    ret"))))
                    (car *lambdas*)))

    ;; 2. Allocate closure on heap at runtime (r12)
    ;; Store code pointer label into [r12]
    (emit (string-append "    lea rax, [rip + " label "]"))
    (emit "    mov [r12], rax")
    ;; Store captured free variables into [r12 + 8 * i]
    (let loop ((fs frees) (idx 1))
      (if (not (null? fs))
          (let ((f (car fs)))
            (compile-variable f env)
            (emit (string-append "    mov [r12 + " (number->string (* idx 8)) "], rax"))
            (loop (cdr fs) (+ idx 1)))))
    ;; Tag closure pointer with 0x01 (Heap object)
    (emit "    lea rax, [r12 + 1]")
    (emit (string-append "    add r12, " (number->string aligned-size)))))

(define (compile-lambda params body si env)
  (compile-lambda-named #f params body si env))

(define (compile-variable var env)
  (let ((binding (assq var env)))
    (if (not binding)
        (error "Unbound variable:" var)
        (let ((info (cdr binding)))
          (cond
            ((number? info)
             ;; Standard stack offset
             (emit (string-append "    mov rax, [rsp " (offset->string info) "]")))
            ((and (pair? info) (eq? (car info) 'param))
             ;; Lambda param offset (positive: +8, +16, ...)
             (emit (string-append "    mov rax, [rsp + " (number->string (cdr info)) "]")))
            ((and (pair? info) (eq? (car info) 'self))
             ;; Self closure reference in recursion
             (emit (string-append "    mov rax, [rsp " (offset->string (cdr info)) "]")))
            ((and (pair? info) (eq? (car info) 'free))
             ;; Free variable accessed via self-closure slot on stack
             (let ((self-offset (cadr info))
                   (free-idx (cddr info)))
                (emit (string-append "    mov rdx, [rsp " (offset->string self-offset) "]"))
                (emit (string-append "    mov rax, [rdx + " (number->string (- free-idx 1)) "]"))))
            (else
             (error "Invalid binding format:" binding)))))))

(define (compile-let bindings body si env tail?)
  (let loop ((bs bindings)
             (curr-si si)
             (new-env env))
    (if (null? bs)
        (compile-expr body curr-si new-env tail?)
        (let* ((b (car bs))
               (var (car b))
               (val (cadr b)))
          (compile-expr val curr-si env #f)
          (emit (string-append "    mov [rsp " (offset->string curr-si) "], rax"))
          (loop (cdr bs)
                (- curr-si 8)
                (cons (cons var curr-si) new-env))))))

(define (compile-letrec bindings body si env tail?)
  (let* ((vars (map car* bindings))
         (slots (let loop ((vs vars) (curr-si si) (acc '()))
                  (if (null? vs) acc
                      (loop (cdr vs) (- curr-si 8)
                            (cons (cons (car vs) curr-si) acc)))))
         (extended-env (append slots env))
         (end-si (- si (* (length vars) 8))))
    ;; 1. Evaluate and store each closure into its stack slot
    (let loop ((bs bindings))
      (if (not (null? bs))
          (let* ((b (car bs))
                 (var (car b))
                 (val (cadr b))
                 (slot (cdr (assq var extended-env))))
            (if (and (pair? val) (eq? (car val) 'lambda))
                ;; Named lambda for recursion
                (compile-lambda-named var (cadr val) (make-body-expr (cddr val)) end-si extended-env)
                (compile-expr val end-si extended-env #f))
            (emit (string-append "    mov [rsp " (offset->string slot) "], rax"))
            (loop (cdr bs)))))
    ;; 2. Backpatch mutual references between closures on the heap!
    (let loop-b ((bs bindings))
      (if (not (null? bs))
          (let* ((b (car bs))
                 (var (car b))
                 (val (cadr b))
                 (c-slot (cdr (assq var extended-env))))
            (if (and (pair? val) (eq? (car val) 'lambda))
                (let* ((params (cadr val))
                       (lbody (make-body-expr (cddr val)))
                       (frees (free-vars lbody (cons var params))))
                  ;; Check each free variable of this lambda
                  (let loop-f ((fs frees) (idx 1))
                    (if (not (null? fs))
                        (let* ((f (car fs))
                               (target-entry (assq f slots)))
                          (if target-entry
                              ;; f is one of the letrec-bound variables!
                              (let ((target-slot (cdr target-entry))
                                    (heap-offset (- (* idx 8) 1)))
                                (emit (string-append "    mov rax, [rsp " (offset->string target-slot) "]"))
                                (emit (string-append "    mov rdx, [rsp " (offset->string c-slot) "]"))
                                (emit (string-append "    mov [rdx + " (number->string heap-offset) "], rax"))))
                          (loop-f (cdr fs) (+ idx 1)))))))
            (loop-b (cdr bs)))))
    ;; 3. Compile body
    (compile-expr body end-si extended-env tail?)))

(define (compile-if test then else-opt si env tail?)
  (let ((else-label (unique-label "L_else"))
        (end-label (unique-label "L_end")))
    (compile-expr test si env #f)
    (emit "    cmp rax, 0x2F")
    (emit (string-append "    je " else-label))
    (compile-expr then si env tail?)
    (emit (string-append "    jmp " end-label))
    (emit (string-append else-label ":"))
    (if (null? else-opt)
        (emit "    mov rax, 0x2F")
        (compile-expr (car else-opt) si env tail?))
    (emit (string-append end-label ":"))))

(define (compile-begin exprs si env tail?)
  (if (null? exprs)
      (emit "    mov rax, 0x3F")
      (let loop ((es exprs))
        (if (null? (cdr es))
            (compile-expr (car es) si env tail?)
            (begin
              (compile-expr (car es) si env #f)
              (loop (cdr es)))))))

(define (desugar-and args)
  (cond
    ((null? args) #t)
    ((null? (cdr args)) (car args))
    (else
     (list 'if (car args) (desugar-and (cdr args)) #f))))

(define (desugar-or args)
  (cond
    ((null? args) #f)
    ((null? (cdr args)) (car args))
    (else
     (let ((tmp (unique-symbol "or_tmp_")))
       (list 'let (list (list tmp (car args)))
             (list 'if tmp tmp (desugar-or (cdr args))))))))

(define (compile-quote datum si env)
  (cond
    ((immediate? datum)
     (emit-immediate datum))
    ((symbol? datum)
     (compile-expr (list 'string->symbol (symbol->string datum)) si env #f))

    ((pair? datum)
     (compile-expr (list 'cons
                         (list 'quote (car datum))
                         (list 'quote (cdr datum)))
                   si env #f))
    (else
     (error "Unknown quoted datum:" datum))))

;;; General Procedure Call (Tail Call vs Non-tail Call)
(define (compile-call proc args si env tail?)
  (let* ((num-args (length args))
         (cur-params-entry (assq '%num-params env))
         (cur-num-params (if cur-params-entry (cdr cur-params-entry) #f))
         (can-tco? (and tail? (if cur-num-params (= cur-num-params num-args) #f)))
         (frame-shift (align-frame-shift (if (= num-args 0)
                                             (- 0 si)
                                             (- (* 8 (- num-args 1)) si))))
         (aligned-si (if (= num-args 0)
                         (- 0 frame-shift)
                         (- (* 8 (- num-args 1)) frame-shift))))
    ;; 1. Evaluate arguments sequentially and place into temporary stack slots
    (let loop ((as args) (curr-si aligned-si))
      (if (not (null? as))
          (begin
            (compile-expr (car as) curr-si env #f)
            (emit (string-append "    mov [rsp " (offset->string curr-si) "], rax"))
            (loop (cdr as) (- curr-si 8)))))

    (let ((end-args-si (- aligned-si (* num-args 8))))
      ;; 2. Evaluate procedure expression -> RAX
      (compile-expr proc end-args-si env #f)
      (emit "    mov r10, rax") ; closure pointer into r10

      (if can-tco?
          ;; --- TAIL CALL OPTIMIZATION (TCO) ---
          ;; Overwrite current frame's parameter slots [rsp + 8 * (num-args - i)]
          (begin
            (let loop ((i 0))
              (if (< i num-args)
                  (let ((temp-offset (- aligned-si (* i 8)))
                        (param-offset (* 8 (- num-args i))))
                    (emit (string-append "    mov rdx, [rsp " (offset->string temp-offset) "]"))
                    (emit (string-append "    mov [rsp + " (number->string param-offset) "], rdx"))
                    (loop (+ i 1)))))
            (emit "    mov rdx, [r10 - 1]") ; extract code pointer from closure
            (emit "    jmp rdx"))          ; tail jump without new stack frame!

          ;; --- NON-TAIL CALL ---
          (begin
            (if (> frame-shift 0)
                (emit (string-append "    sub rsp, " (number->string frame-shift))))
            (emit "    mov rdx, [r10 - 1]")
            (emit "    call rdx")
            (if (> frame-shift 0)
                (emit (string-append "    add rsp, " (number->string frame-shift)))))))))

(define (compile-expr expr si env tail?)
  (cond
    ((immediate? expr)
     (emit-immediate expr))
    ((symbol? expr)
     (compile-variable expr env))
    ((pair? expr)
     (let ((op (car expr)))
       (cond
         ((zero-arg-prim? op)
          (compile-zero-arg op si env))
         ((eq? op '-)
          (if (null? (cddr expr))
              (compile-unary '- (cadr expr) si env)
              (compile-binop '- (cadr expr) (caddr expr) si env)))
         ((unary-prim? op)
          (compile-unary op (cadr expr) si env))
         ((binop-prim? op)
          (compile-binop op (cadr expr) (caddr expr) si env))
         ((triop-prim? op)
          (compile-triop op (cadr expr) (caddr expr) (cadddr expr) si env))
         ((eq? op 'cond)
          (compile-expr (desugar-cond (cdr expr)) si env tail?))
         ((eq? op 'case)
          (compile-expr (desugar-case (cadr expr) (cddr expr)) si env tail?))
         ((eq? op 'string-append)
          (compile-expr (desugar-string-append (cdr expr)) si env tail?))
         ((eq? op 'list)
          (compile-expr (desugar-list (cdr expr)) si env tail?))
         ((eq? op 'let*)
          (compile-expr (desugar-let* (cadr expr) (cddr expr)) si env tail?))
         ((eq? op 'let)
          (if (symbol? (cadr expr))
              (compile-expr (desugar-named-let expr) si env tail?)
              (compile-let (cadr expr) (make-body-expr (cddr expr)) si env tail?)))
         ((eq? op 'letrec)
          (compile-letrec (cadr expr) (make-body-expr (cddr expr)) si env tail?))
         ((eq? op 'lambda)
          (compile-lambda (cadr expr) (make-body-expr (cddr expr)) si env))
         ((eq? op 'if)
          (compile-if (cadr expr) (caddr expr) (cdddr expr) si env tail?))
         ((eq? op 'begin)
          (compile-begin (cdr expr) si env tail?))
         ((eq? op 'and)
          (compile-expr (desugar-and (cdr expr)) si env tail?))
         ((eq? op 'or)
          (compile-expr (desugar-or (cdr expr)) si env tail?))
         ((eq? op 'quote)
          (compile-quote (cadr expr) si env))
         (else
          ;; General procedure call
          (compile-call op (cdr expr) si env tail?)))))
    (else
     (error "Invalid syntax:" expr))))

(define (compile-program expr)
  (set-car! *label-counter* 0)
  (set-car! *symbol-counter* 0)
  (set-car! *symbol-table* '())
  (set-car! *string-counter* 0)
  (set-car! *strings* '())
  (set-car! *lambdas* '())
  (emit "    .intel_syntax noprefix")
  (emit "    .text")
  (emit "    .globl scheme_entry")
  (emit "    .type scheme_entry, @function")
  (emit "scheme_entry:")
  (emit "    push r12")
  (emit "    sub rsp, 8")
  (emit "    mov r12, rdi")          ; rdi contains heap_base from C runtime
  (compile-expr expr -8 '() #f)
  (emit "    add rsp, 8")
  (emit "    pop r12")
  (emit "    ret")
  ;; Emit all compiled lambda procedures (including nested ones)
  (let loop ()
    (if (not (null? (car *lambdas*)))
        (let ((fn (car (car *lambdas*))))
          (set-car! *lambdas* (cdr (car *lambdas*)))
          (fn)
          (loop))))
  ;; Emit all string literals in .rodata section
  (if (not (null? (car *strings*)))
      (begin
        (emit "    .section .rodata")
        (let loop ((ss (reverse (car *strings*))))
          (if (not (null? ss))
              (let ((entry (car ss)))
                (emit "    .p2align 3")
                (emit (string-append (car entry) ":"))
                (emit (string-append "    .asciz \"" (escape-gas-string (cdr entry)) "\""))
                (loop (cdr ss)))))))
  (emit "    .section .note.GNU-stack,\"\",@progbits"))

(define (rewrite-top-level forms)
  (let loop ((fs forms) (bindings '()) (bodies '()))
    (if (null? fs)
        (if (null? bindings)
            (make-body-expr (reverse bodies))
            (list 'letrec (reverse bindings) (make-body-expr (reverse bodies))))
        (let ((f (car fs)))
          (if (and (pair? f) (eq? (car f) 'define))
              (let ((def-spec (cadr f)))
                (if (pair? def-spec)
                    ;; (define (name . params) . body)
                    (let ((name (car def-spec))
                          (params (cdr def-spec))
                          (lbody (cddr f)))
                      (loop (cdr fs)
                            (cons (list name (cons 'lambda (cons params lbody))) bindings)
                            bodies))
                    ;; (define name val)
                    (let ((name def-spec)
                          (val (caddr f)))
                      (loop (cdr fs)
                            (cons (list name val) bindings)
                            bodies))))
              ;; Normal expression
              (loop (cdr fs) bindings (cons f bodies)))))))

(define (read-all-forms)
  (let loop ((acc '()))
    (let ((expr (read)))
      (if (eof-object? expr)
          (reverse acc)
          (loop (cons expr acc))))))

;;; Entry point: read all S-expressions from standard input and compile
(let ((forms (read-all-forms)))
  (if (not (null? forms))
      (compile-program (rewrite-top-level forms))))
