#!/usr/bin/env python3
"""
Pure-Python Hybrid Relational, Columnar, Vector, and Distributed Database Engine (DSN-14).
Provides zero-dependency binary vector storage, pure Python HNSW graph indexing,
deterministic embeddings, SQLite-inspired 4-tier modular architecture
(VFS, Pager/PageCache, VDBE Bytecode VM, SQL Compiler/CodeGen),
PEP 249 DB-API 2.0 driver, and 100% compatible Python standard `sqlite3` client interfaces.
"""

from .btree import BPlusTree, BTreeNode, ScalarKey
from .buffer_pool import BufferFrame, BufferPool2Q, BufferPoolError
from .client import DatabaseClient, VectorDBClient
from .codegen import CodeGenerator
from .compiler import SQLCompiler
from .cow import CoWBTree, CoWEngine, CoWNode, CoWReadTx, CoWWriteTx, MetaPage, MMapFile
from .distributed import (
    AntiEntropySynchronizer,
    AppendEntriesArgs,
    AppendEntriesReply,
    ConflictResolutionStrategy,
    ConsistentHashRing,
    DistributedDeadlockDetector,
    GlobalDecision,
    GossipNode,
    Hint,
    HintedHandoffManager,
    LogEntry,
    MerkleNode,
    MerkleTree,
    NodeState,
    NodeStatus,
    ORSet,
    PhiAccrualDetector,
    PNCounter,
    QuorumCoordinator,
    QuorumReadError,
    QuorumReplica,
    QuorumWriteError,
    RaftCluster,
    RaftNode,
    RaftRole,
    RequestVoteArgs,
    RequestVoteReply,
    SagaOrchestrator,
    SagaStatus,
    SagaStep,
    ShardManager,
    TwoPCCoordinator,
    TwoPCParticipant,
    TwoPCState,
    TxRecord,
    VectorClock,
    VersionedValue,
    VoteType,
    build_paper_pipeline_saga,
    prune_dominated_versions,
    resolve_conflict,
)
from .driver import Connection, Cursor, DatabaseError, connect
from .embedding import DeterministicEmbedding
from .engine import (
    BatchIterator,
    ColumnBatch,
    FilterIterator,
    HashJoinIterator,
    IndexScanIterator,
    LimitIterator,
    NestedLoopJoinIterator,
    ProjectionIterator,
    SeqScanIterator,
    VectorizedAggregation,
    VectorizedFilter,
    VectorizedProjection,
    VectorizedScan,
    VolcanoIterator,
)
from .index import HNSWIndex
from .lock_manager import (
    DeadlockError,
    LockGrant,
    LockManager,
    LockMode,
    WaitForGraph,
    is_compatible,
)
from .lsm import (
    TOMBSTONE,
    BloomFilter,
    LSMTreeEngine,
    MemTable,
    SSTableReader,
    SSTableWriter,
)
from .mvcc import MVCCManager, TransactionSnapshot, VersionedTuple
from .pager import PAGE_SIZE, Page, PageCache, Pager
from .pax import (
    ColumnDecoder,
    ColumnEncoder,
    ColumnEncodingType,
    PAXPage,
    PAXScanner,
    PAXTable,
)
from .planner import (
    ColumnStats,
    CostModel,
    DPJoinOptimizer,
    EquiDepthBucket,
    EquiDepthHistogram,
    ExecutionPlan,
    HyperLogLog,
    JoinPhysicalOperator,
    JoinPlanNode,
    PlanType,
    QueryPlanner,
    TableStats,
)
from .profiler import DatabaseProfiler, ProfileResult
from .protocol import VectorDBProtocolError, VectorDBProtocolHandler
from .recovery import ARIESRecoveryManager
from .service import DatabaseLifecycleHook, DatabaseService
from .slotted_page import (
    DataType,
    OverflowManager,
    PageCorruptionError,
    PageFullError,
    PageType,
    SlottedPage,
    SlottedPageError,
    TupleSerializer,
)
from .sql import (
    AccessController,
    DCLPermissionDeniedError,
    SQLCommandType,
    SQLExecutionError,
    SQLExecutor,
    SQLParseError,
    SQLParser,
    SQLStatement,
    TableCatalog,
    TransactionError,
    TransactionManager,
)
from .sqlite_bridge import attach_to_sqlite
from .sqlite_engine import (
    SQLiteConnection,
    SQLiteCursor,
    SQLiteError,
    SQLiteOperationalError,
    SQLiteRow,
    count_sqlite_table_rows,
    dump_sqlite_table_records,
    get_sqlite_connection,
    get_sqlite_table_counts,
    get_sqlite_table_names,
    register_vector_functions,
    restore_sqlite_table_records,
    sum_sqlite_table_rows,
    sync_from_vector_storage,
    sync_to_vector_storage,
)
from .storage import VectorStorage, VectorStorageSecurityError
from .vdbe import VDBE, Instruction, OpCode, Statement, StepResult, VDBEProgram
from .vfs import (
    VFS,
    MemoryVFS,
    MemoryVFSFile,
    PosixVFS,
    PosixVFSFile,
    VFSFile,
    get_vfs,
    register_vfs,
)
from .wal import (
    WAL_HEADER_SIZE,
    WAL_MAGIC,
    WAL_VERSION,
    LogRecord,
    LogRecordType,
    WALReader,
    WALWriter,
)

__all__ = [
    # Storage & Indexing
    "VectorStorage",
    "VectorStorageSecurityError",
    "DeterministicEmbedding",
    "HNSWIndex",
    # VFS (OS Abstraction Layer)
    "VFS",
    "VFSFile",
    "PosixVFS",
    "PosixVFSFile",
    "MemoryVFS",
    "MemoryVFSFile",
    "get_vfs",
    "register_vfs",
    # Pager (Storage Backend & Cache)
    "Pager",
    "PageCache",
    "Page",
    "PAGE_SIZE",
    "BufferPool2Q",
    "BufferFrame",
    "BufferPoolError",
    # Write-Ahead Logging & ARIES Recovery
    "LogRecord",
    "LogRecordType",
    "WALWriter",
    "WALReader",
    "WAL_MAGIC",
    "WAL_VERSION",
    "WAL_HEADER_SIZE",
    "ARIESRecoveryManager",
    # MVCC & SS2PL Concurrency Control
    "MVCCManager",
    "TransactionSnapshot",
    "VersionedTuple",
    "LockManager",
    "LockMode",
    "LockGrant",
    "DeadlockError",
    "WaitForGraph",
    "is_compatible",
    # LSM-Tree Ingestion Engine & Bloom Filters
    "LSMTreeEngine",
    "BloomFilter",
    "MemTable",
    "SSTableReader",
    "SSTableWriter",
    "TOMBSTONE",
    # CoW B-Tree & MMap Zero-Copy Engine
    "CoWEngine",
    "CoWReadTx",
    "CoWWriteTx",
    "CoWBTree",
    "CoWNode",
    "MetaPage",
    "MMapFile",
    # PAX Columnar Analytics Storage
    "PAXTable",
    "PAXPage",
    "PAXScanner",
    "ColumnEncoder",
    "ColumnDecoder",
    "ColumnEncodingType",
    # Slotted Page Binary Storage
    "SlottedPage",
    "TupleSerializer",
    "OverflowManager",
    "PageType",
    "DataType",
    "SlottedPageError",
    "PageCorruptionError",
    "PageFullError",
    # B+Tree Engine
    "BPlusTree",
    "BTreeNode",
    "ScalarKey",
    # Cost-Based Query Planner and Optimization
    "ExecutionPlan",
    "PlanType",
    "CostModel",
    "QueryPlanner",
    "ColumnStats",
    "TableStats",
    "EquiDepthBucket",
    "EquiDepthHistogram",
    "HyperLogLog",
    "DPJoinOptimizer",
    "JoinPhysicalOperator",
    "JoinPlanNode",
    # Volcano Streaming Iterators and Vectorized Execution Engine
    "VolcanoIterator",
    "SeqScanIterator",
    "IndexScanIterator",
    "FilterIterator",
    "ProjectionIterator",
    "NestedLoopJoinIterator",
    "HashJoinIterator",
    "LimitIterator",
    "ColumnBatch",
    "BatchIterator",
    "VectorizedScan",
    "VectorizedFilter",
    "VectorizedProjection",
    "VectorizedAggregation",
    # Distributed Coordination, Causality, Gossip, Quorum, and Anti-Entropy
    "VectorClock",
    "VersionedValue",
    "ConflictResolutionStrategy",
    "resolve_conflict",
    "prune_dominated_versions",
    "PhiAccrualDetector",
    "NodeStatus",
    "NodeState",
    "GossipNode",
    "QuorumReplica",
    "QuorumCoordinator",
    "QuorumWriteError",
    "QuorumReadError",
    "Hint",
    "HintedHandoffManager",
    "MerkleNode",
    "MerkleTree",
    "PNCounter",
    "ORSet",
    "AntiEntropySynchronizer",
    # Raft Consensus & SMR
    "RaftRole",
    "LogEntry",
    "RequestVoteArgs",
    "RequestVoteReply",
    "AppendEntriesArgs",
    "AppendEntriesReply",
    "RaftNode",
    "RaftCluster",
    # Distributed 2PC & Deadlock Detection
    "TwoPCState",
    "VoteType",
    "GlobalDecision",
    "TxRecord",
    "TwoPCParticipant",
    "TwoPCCoordinator",
    "DistributedDeadlockDetector",
    # Saga Orchestration & Compensation
    "SagaStatus",
    "SagaStep",
    "SagaOrchestrator",
    "build_paper_pipeline_saga",
    # Consistent Hashing & Sharding
    "ConsistentHashRing",
    "ShardManager",
    # VDBE (Core Virtual Machine)
    "VDBE",
    "VDBEProgram",
    "OpCode",
    "Instruction",
    "Statement",
    "StepResult",
    # Compiler (Frontend)
    "SQLCompiler",
    "CodeGenerator",
    # Protocol & Client & IPC Service
    "VectorDBProtocolHandler",
    "VectorDBProtocolError",
    "VectorDBClient",
    "DatabaseClient",
    "DatabaseService",
    "DatabaseLifecycleHook",
    # SQL AST & Executor
    "SQLCommandType",
    "SQLStatement",
    "SQLParser",
    "SQLParseError",
    "SQLExecutor",
    "SQLExecutionError",
    "TableCatalog",
    "AccessController",
    "DCLPermissionDeniedError",
    "TransactionManager",
    "TransactionError",
    # Drivers & Bridges
    "connect",
    "Connection",
    "Cursor",
    "DatabaseError",
    "attach_to_sqlite",
    "get_sqlite_connection",
    "register_vector_functions",
    "sync_from_vector_storage",
    "sync_to_vector_storage",
    "SQLiteConnection",
    "SQLiteCursor",
    "SQLiteRow",
    "SQLiteError",
    "SQLiteOperationalError",
    "count_sqlite_table_rows",
    "dump_sqlite_table_records",
    "get_sqlite_table_counts",
    "get_sqlite_table_names",
    "restore_sqlite_table_records",
    "sum_sqlite_table_rows",
    # Profiler & Metrics
    "DatabaseProfiler",
    "ProfileResult",
]
