#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: YAMLFrontmatter
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

from typing import Any

from core.structures.peg import (
    Choice,
    Class,
    Dot,
    Lit,
    NotPred,
    OneOrMore,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
    ZeroOrMore,
)
from pipeline.transformer.yaml_helpers import (
    _build_frontmatter_dict,
    _make_kv_pair,
    _parse_scalar,
    _unescape_double_quotes,
    _unescape_single_quotes,
)

# User header code


class YAMLFrontmatterParser(Parser[Any]):
    """Packrat PEG Parser for YAMLFrontmatter grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_document = RuleRef("document")
        self._r_frontmatter = RuleRef("frontmatter")
        self._r_delim = RuleRef("delim")
        self._r_entries = RuleRef("entries")
        self._r_entry_item = RuleRef("entry_item")
        self._r_comment_or_blank = RuleRef("comment_or_blank")
        self._r_scalar_mapping = RuleRef("scalar_mapping")
        self._r_inline_list_mapping = RuleRef("inline_list_mapping")
        self._r_inline_list_items = RuleRef("inline_list_items")
        self._r_list_mapping = RuleRef("list_mapping")
        self._r_block_list_items = RuleRef("block_list_items")
        self._r_block_list_entry = RuleRef("block_list_entry")
        self._r_block_dict_cont = RuleRef("block_dict_cont")
        self._r_inline_dict_entry = RuleRef("inline_dict_entry")
        self._r_nested_mapping = RuleRef("nested_mapping")
        self._r_nested_pairs = RuleRef("nested_pairs")
        self._r_nested_pair_item = RuleRef("nested_pair_item")
        self._r_nested_scalar_mapping = RuleRef("nested_scalar_mapping")
        self._r_nested_list_mapping = RuleRef("nested_list_mapping")
        self._r_key_ident = RuleRef("key_ident")
        self._r_scalar_val = RuleRef("scalar_val")
        self._r_double_quoted_str = RuleRef("double_quoted_str")
        self._r_single_quoted_str = RuleRef("single_quoted_str")
        self._r_unquoted_scalar = RuleRef("unquoted_scalar")
        self._r_opt_comment = RuleRef("opt_comment")
        self._r_newline = RuleRef("newline")
        self._r_opt_newlines = RuleRef("opt_newlines")

        self._r_document.define(
            Seq(
                self._r_opt_newlines,
                self._r_frontmatter,
                self._r_opt_newlines,
                ZeroOrMore(Dot()),
            ).map(self._action_document_0)
        )
        self._r_frontmatter.define(
            Seq(
                self._r_delim,
                self._r_newline,
                self._r_entries,
                Choice(self._r_delim, NotPred(Dot())),
            ).map(self._action_frontmatter_1)
        )
        self._r_delim.define(Seq(Lit("---"), ZeroOrMore(Class(" \\t", inverted=False))))
        self._r_entries.define(
            ZeroOrMore(self._r_entry_item).map(self._action_entries_2)
        )
        self._r_entry_item.define(
            Choice(
                self._r_comment_or_blank,
                self._r_nested_mapping,
                self._r_list_mapping,
                self._r_inline_list_mapping,
                self._r_scalar_mapping,
            )
        )
        self._r_comment_or_blank.define(
            Choice(
                Seq(
                    ZeroOrMore(Class(" \\t", inverted=False)),
                    Lit("#"),
                    ZeroOrMore(Class("\\r\\n", inverted=True)),
                    self._r_newline,
                ).map(self._action_comment_or_blank_3),
                Seq(OneOrMore(Class(" \\t", inverted=False)), self._r_newline).map(
                    self._action_comment_or_blank_4
                ),
                self._r_newline.map(self._action_comment_or_blank_5),
            )
        )
        self._r_scalar_mapping.define(
            Seq(
                self._r_key_ident,
                ZeroOrMore(Class(" \\t", inverted=False)),
                Lit(":"),
                ZeroOrMore(Class(" \\t", inverted=False)),
                self._r_scalar_val,
                self._r_opt_comment,
                self._r_newline,
            ).map(self._action_scalar_mapping_6)
        )
        self._r_inline_list_mapping.define(
            Seq(
                self._r_key_ident,
                ZeroOrMore(Class(" \\t", inverted=False)),
                Lit(":"),
                ZeroOrMore(Class(" \\t", inverted=False)),
                Lit("["),
                ZeroOrMore(Class(" \\t", inverted=False)),
                Opt(self._r_inline_list_items),
                ZeroOrMore(Class(" \\t", inverted=False)),
                Lit("]"),
                self._r_opt_comment,
                self._r_newline,
            ).map(self._action_inline_list_mapping_7)
        )
        self._r_inline_list_items.define(
            Seq(
                self._r_scalar_val,
                ZeroOrMore(
                    Seq(
                        ZeroOrMore(Class(" \\t", inverted=False)),
                        Lit(","),
                        ZeroOrMore(Class(" \\t", inverted=False)),
                        self._r_scalar_val,
                    ).map(self._action_inline_list_items_8)
                ),
            ).map(self._action_inline_list_items_9)
        )
        self._r_list_mapping.define(
            Seq(
                self._r_key_ident,
                ZeroOrMore(Class(" \\t", inverted=False)),
                Lit(":"),
                ZeroOrMore(Class(" \\t", inverted=False)),
                self._r_opt_comment,
                self._r_newline,
                self._r_block_list_items,
            ).map(self._action_list_mapping_10)
        )
        self._r_block_list_items.define(
            OneOrMore(self._r_block_list_entry).map(self._action_block_list_items_11)
        )
        self._r_block_list_entry.define(
            Choice(
                Seq(
                    ZeroOrMore(Class(" \\t", inverted=False)),
                    Lit("-"),
                    OneOrMore(Class(" \\t", inverted=False)),
                    self._r_key_ident,
                    ZeroOrMore(Class(" \\t", inverted=False)),
                    Lit(":"),
                    ZeroOrMore(Class(" \\t", inverted=False)),
                    self._r_scalar_val,
                    self._r_opt_comment,
                    self._r_newline,
                    ZeroOrMore(self._r_block_dict_cont),
                ).map(self._action_block_list_entry_12),
                Seq(
                    ZeroOrMore(Class(" \\t", inverted=False)),
                    Lit("-"),
                    OneOrMore(Class(" \\t", inverted=False)),
                    self._r_inline_dict_entry,
                    self._r_opt_comment,
                    self._r_newline,
                ).map(self._action_block_list_entry_13),
                Seq(
                    ZeroOrMore(Class(" \\t", inverted=False)),
                    Lit("-"),
                    OneOrMore(Class(" \\t", inverted=False)),
                    self._r_scalar_val,
                    self._r_opt_comment,
                    self._r_newline,
                ).map(self._action_block_list_entry_14),
            )
        )
        self._r_block_dict_cont.define(
            Seq(
                OneOrMore(Class(" \\t", inverted=False)),
                NotPred(Seq(Lit("-"), OneOrMore(Class(" \\t", inverted=False)))),
                self._r_key_ident,
                ZeroOrMore(Class(" \\t", inverted=False)),
                Lit(":"),
                ZeroOrMore(Class(" \\t", inverted=False)),
                self._r_scalar_val,
                self._r_opt_comment,
                self._r_newline,
            ).map(self._action_block_dict_cont_15)
        )
        self._r_inline_dict_entry.define(
            Seq(
                self._r_key_ident,
                ZeroOrMore(Class(" \\t", inverted=False)),
                Lit(":"),
                ZeroOrMore(Class(" \\t", inverted=False)),
                self._r_scalar_val,
                ZeroOrMore(
                    Seq(
                        ZeroOrMore(Class(" \\t", inverted=False)),
                        Lit(","),
                        ZeroOrMore(Class(" \\t", inverted=False)),
                        self._r_key_ident,
                        ZeroOrMore(Class(" \\t", inverted=False)),
                        Lit(":"),
                        ZeroOrMore(Class(" \\t", inverted=False)),
                        self._r_scalar_val,
                    ).map(self._action_inline_dict_entry_16)
                ),
            ).map(self._action_inline_dict_entry_17)
        )
        self._r_nested_mapping.define(
            Seq(
                self._r_key_ident,
                ZeroOrMore(Class(" \\t", inverted=False)),
                Lit(":"),
                ZeroOrMore(Class(" \\t", inverted=False)),
                self._r_opt_comment,
                self._r_newline,
                self._r_nested_pairs,
            ).map(self._action_nested_mapping_18)
        )
        self._r_nested_pairs.define(
            OneOrMore(self._r_nested_pair_item).map(self._action_nested_pairs_19)
        )
        self._r_nested_pair_item.define(
            Choice(
                self._r_comment_or_blank,
                self._r_nested_list_mapping,
                self._r_nested_scalar_mapping,
            )
        )
        self._r_nested_scalar_mapping.define(
            Seq(
                OneOrMore(Class(" \\t", inverted=False)),
                self._r_key_ident,
                ZeroOrMore(Class(" \\t", inverted=False)),
                Lit(":"),
                ZeroOrMore(Class(" \\t", inverted=False)),
                self._r_scalar_val,
                self._r_opt_comment,
                self._r_newline,
            ).map(self._action_nested_scalar_mapping_20)
        )
        self._r_nested_list_mapping.define(
            Seq(
                OneOrMore(Class(" \\t", inverted=False)),
                self._r_key_ident,
                ZeroOrMore(Class(" \\t", inverted=False)),
                Lit(":"),
                ZeroOrMore(Class(" \\t", inverted=False)),
                self._r_opt_comment,
                self._r_newline,
                self._r_block_list_items,
            ).map(self._action_nested_list_mapping_21)
        )
        self._r_key_ident.define(Reg("[a-zA-Z0-9_-]+").map(self._action_key_ident_22))
        self._r_scalar_val.define(
            Choice(
                self._r_double_quoted_str,
                self._r_single_quoted_str,
                self._r_unquoted_scalar,
            )
        )
        self._r_double_quoted_str.define(
            Reg('"(?:[^"\\\\]|\\\\.)*"').map(self._action_double_quoted_str_23)
        )
        self._r_single_quoted_str.define(
            Reg("'(?:[^'\\\\]|\\\\.)*'").map(self._action_single_quoted_str_24)
        )
        self._r_unquoted_scalar.define(
            Reg("[^\\r\\n#,\\{\\}\\[\\]]+([ \\t]+[^\\r\\n#,\\{\\}\\[\\]]+)*").map(
                self._action_unquoted_scalar_25
            )
        )
        self._r_opt_comment.define(
            Opt(
                Seq(
                    ZeroOrMore(Class(" \\t", inverted=False)),
                    Lit("#"),
                    ZeroOrMore(Class("\\r\\n", inverted=True)),
                )
            )
        )
        self._r_newline.define(Choice(Lit("\r\n"), Lit("\n"), Lit("\r")))
        self._r_opt_newlines.define(ZeroOrMore(self._r_newline))

        self.root_parser: Parser[Any] = self._r_document

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_document_0(val: Any) -> Any:
        fm = val[1]
        return fm

    @staticmethod
    def _action_frontmatter_1(val: Any) -> Any:
        entries = val[2]
        return _build_frontmatter_dict(entries)

    @staticmethod
    def _action_entries_2(val: Any) -> Any:
        items = val
        return [it for it in items if it is not None]

    @staticmethod
    def _action_comment_or_blank_3(val: Any) -> Any:
        return None

    @staticmethod
    def _action_comment_or_blank_4(val: Any) -> Any:
        return None

    @staticmethod
    def _action_comment_or_blank_5(val: Any) -> Any:
        return None

    @staticmethod
    def _action_scalar_mapping_6(val: Any) -> Any:
        key = val[0]
        val = val[4]
        return _make_kv_pair(key, val)

    @staticmethod
    def _action_inline_list_mapping_7(val: Any) -> Any:
        key = val[0]
        items = val[6]
        return _make_kv_pair(key, items or [])

    @staticmethod
    def _action_inline_list_items_8(val: Any) -> Any:
        s = val[3]
        return s

    @staticmethod
    def _action_inline_list_items_9(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_list_mapping_10(val: Any) -> Any:
        key = val[0]
        items = val[6]
        return _make_kv_pair(key, items)

    @staticmethod
    def _action_block_list_items_11(val: Any) -> Any:
        lines = val
        return [item for item in lines if item is not None]

    @staticmethod
    def _action_block_list_entry_12(val: Any) -> Any:
        first_k = val[3]
        first_v = val[7]
        cont_fields = val[10]
        d = {first_k: first_v}
        for k, v in cont_fields:
            d[k] = v
        return d

    @staticmethod
    def _action_block_list_entry_13(val: Any) -> Any:
        dict_item = val[3]
        return dict_item

    @staticmethod
    def _action_block_list_entry_14(val: Any) -> Any:
        val = val[3]
        return val

    @staticmethod
    def _action_block_dict_cont_15(val: Any) -> Any:
        k = val[2]
        v = val[6]
        return (k, v)

    @staticmethod
    def _action_inline_dict_entry_16(val: Any) -> Any:
        rk = val[3]
        rv = val[7]
        return (rk, rv)

    @staticmethod
    def _action_inline_dict_entry_17(val: Any) -> Any:
        k = val[0]
        v = val[4]
        rest = val[5]
        d = {k: v}
        for rk, rv in rest:
            d[rk] = rv
        return d

    @staticmethod
    def _action_nested_mapping_18(val: Any) -> Any:
        key = val[0]
        pairs = val[6]
        return _make_kv_pair(key, _build_frontmatter_dict(pairs))

    @staticmethod
    def _action_nested_pairs_19(val: Any) -> Any:
        lines = val
        return [item for item in lines if item is not None]

    @staticmethod
    def _action_nested_scalar_mapping_20(val: Any) -> Any:
        k = val[1]
        v = val[5]
        return _make_kv_pair(k, v)

    @staticmethod
    def _action_nested_list_mapping_21(val: Any) -> Any:
        k = val[1]
        items = val[7]
        return _make_kv_pair(k, items)

    @staticmethod
    def _action_key_ident_22(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_double_quoted_str_23(val: Any) -> Any:
        raw = val
        return _unescape_double_quotes(raw)

    @staticmethod
    def _action_single_quoted_str_24(val: Any) -> Any:
        raw = val
        return _unescape_single_quotes(raw)

    @staticmethod
    def _action_unquoted_scalar_25(val: Any) -> Any:
        raw = val
        return _parse_scalar(raw)
