#!/usr/bin/env python3
"""
Python Code Generator (Emitter) for PEG Grammar AST.
Converts GrammarDef AST into standalone, high-performance Python parser classes.
Conforms to DSN-25 Phase 2 Ahead-of-Time PEG Compiler specification.
Zero external dependencies.
"""

from __future__ import annotations

import re
import textwrap
from typing import Callable, ClassVar, Dict, List, Tuple, Type, cast

from core.structures.peg_compiler.ast_nodes import (
    ActionExpr,
    AnyCharExpr,
    CharClassExpr,
    ChoiceExpr,
    Expression,
    GrammarDef,
    LitExpr,
    NamedExpr,
    OptExpr,
    PredExpr,
    RegexExpr,
    RepeatExpr,
    RuleRefExpr,
    SeqExpr,
)


def _find_used_symbols(symbols: Tuple[str, ...], text: str) -> List[str]:
    return [s for s in symbols if re.search(rf"\b{s}\b", text)]


_PEG_SYMBOLS: Tuple[str, ...] = (
    "AndPred",
    "AnyChar",
    "CharClass",
    "Choice",
    "Class",
    "Dot",
    "Lit",
    "NotPred",
    "OneOrMore",
    "Opt",
    "ParseContext",
    "ParseResult",
    "Parser",
    "PEGSyntaxError",
    "Reg",
    "RuleRef",
    "Seq",
    "ZeroOrMore",
)

_TYPING_SYMBOLS: Tuple[str, ...] = (
    "Any",
    "Dict",
    "List",
    "Optional",
    "Set",
    "Tuple",
    "cast",
)


class CodeGenerator:
    """Generates Python source code for a GrammarDef AST."""

    _EXPR_EMITTERS: ClassVar[
        Dict[
            Type[Expression],
            Callable[["CodeGenerator", Expression, str], str],
        ]
    ] = {
        LitExpr: lambda self, e, r: f"Lit({cast(LitExpr, e).value!r})",
        RegexExpr: lambda self, e, r: f"Reg({cast(RegexExpr, e).pattern!r})",
        CharClassExpr: lambda self, e, r: (
            f"Class({cast(CharClassExpr, e).raw_spec!r}, inverted={cast(CharClassExpr, e).inverted})"
        ),
        AnyCharExpr: lambda self, e, r: "Dot()",
        RuleRefExpr: lambda self, e, r: f"self._r_{cast(RuleRefExpr, e).name}",
        OptExpr: lambda self, e, r: f"Opt({self._emit_expr(cast(OptExpr, e).expr, r)})",
        RepeatExpr: lambda self, e, r: self._emit_repeat(cast(RepeatExpr, e), r),
        PredExpr: lambda self, e, r: self._emit_pred(cast(PredExpr, e), r),
        SeqExpr: lambda self, e, r: self._emit_seq(cast(SeqExpr, e), r),
        ChoiceExpr: lambda self, e, r: self._emit_choice(cast(ChoiceExpr, e), r),
        NamedExpr: lambda self, e, r: self._emit_expr(cast(NamedExpr, e).expr, r),
        ActionExpr: lambda self, e, r: self._emit_action(cast(ActionExpr, e), r),
    }

    def __init__(self, grammar: GrammarDef) -> None:
        self.grammar = grammar
        self.action_counter = 0
        self.action_methods: List[str] = []

    def generate(self) -> str:
        """Generates complete Python module source code."""
        class_lines = self._build_class_definition()
        header_code = self.grammar.header_code or ""
        body_text = f"{header_code}\n" + "\n".join(class_lines)
        lines = self._build_module_header(body_text)
        if self.grammar.header_code:
            lines.append(f"# User header code\n{self.grammar.header_code}\n")

        lines.extend(class_lines)
        lines.append("")
        return "\n".join(lines)

    def _build_module_header(self, body_text: str) -> List[str]:
        peg_syms = _find_used_symbols(_PEG_SYMBOLS, body_text)
        typing_syms = _find_used_symbols(_TYPING_SYMBOLS, body_text)

        lines = [
            "#!/usr/bin/env python3",
            '"""',
            f"Auto-generated Packrat PEG Parser for grammar: {self.grammar.name}",
            "Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
        ]
        if typing_syms:
            lines.append(f"from typing import {', '.join(typing_syms)}")
            lines.append("")
        if peg_syms:
            lines.append("from core.structures.peg import (")
            for sym in peg_syms:
                lines.append(f"    {sym},")
            lines.append(")")
            lines.append("")
        return lines

    def _build_class_definition(self) -> List[str]:
        class_name = f"{self.grammar.name}Parser"
        class_lines: List[str] = [
            f"class {class_name}(Parser[Any]):",
            f'    """Packrat PEG Parser for {self.grammar.name} grammar."""',
            "",
            "    def __init__(self) -> None:",
            "        self._init_rules()",
            "",
            "    def _init_rules(self) -> None:",
        ]

        class_lines.extend(self._build_rule_init())
        class_lines.extend(self._emit_parser_methods())
        if self.action_methods:
            for method in self.action_methods:
                class_lines.append("")
                class_lines.append(method)
        return class_lines

    def _build_rule_init(self) -> List[str]:
        lines: List[str] = []
        for rule in self.grammar.rules:
            lines.append(f'        self._r_{rule.name} = RuleRef("{rule.name}")')
        lines.append("")
        for rule in self.grammar.rules:
            expr_code = self._emit_expr(rule.expr, rule.name)
            lines.append(f"        self._r_{rule.name}.define({expr_code})")

        start_r = self.grammar.start_rule or (
            self.grammar.rules[0].name if self.grammar.rules else "root"
        )
        lines.append("")
        lines.append(f"        self.root_parser: Parser[Any] = self._r_{start_r}")
        lines.append("")
        return lines

    def _emit_parser_methods(self) -> List[str]:
        return [
            "    def parse(self, text: str) -> Any:",
            '        """Parses input text and returns semantic value."""',
            "        return self.root_parser.parse(text)",
            "",
            "    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:",
            '        """Evaluates parser at given position."""',
            "        return self.root_parser.parse_at(ctx, pos)",
        ]

    def _emit_expr(self, expr: Expression, rule_name: str) -> str:
        """Emits combinator instantiation string via dispatch table."""
        emitter = self._EXPR_EMITTERS.get(type(expr))
        if emitter is not None:
            return emitter(self, expr, rule_name)
        return "Lit('')"

    def _emit_repeat(self, expr: RepeatExpr, rule_name: str) -> str:
        inner = self._emit_expr(expr.expr, rule_name)
        cls_name = "OneOrMore" if expr.min_count > 0 else "ZeroOrMore"
        return f"{cls_name}({inner})"

    def _emit_pred(self, expr: PredExpr, rule_name: str) -> str:
        inner = self._emit_expr(expr.expr, rule_name)
        cls_name = "AndPred" if expr.is_positive else "NotPred"
        return f"{cls_name}({inner})"

    def _emit_seq(self, expr: SeqExpr, rule_name: str) -> str:
        elems = [self._emit_expr(e, rule_name) for e in expr.elements]
        return f"Seq({', '.join(elems)})"

    def _emit_choice(self, expr: ChoiceExpr, rule_name: str) -> str:
        alts = [self._emit_expr(a, rule_name) for a in expr.alternatives]
        return f"Choice({', '.join(alts)})"

    def _emit_action(self, expr: ActionExpr, rule_name: str) -> str:
        inner = self._emit_expr(expr.expr, rule_name)
        method_name = f"_action_{rule_name}_{self.action_counter}"
        self.action_counter += 1

        named_bindings = self._collect_named_bindings(expr.expr)
        action_code = self._build_action_method(
            method_name, expr.action_code, named_bindings
        )
        self.action_methods.append(action_code)
        return f"{inner}.map(self.{method_name})"

    def _collect_named_bindings(
        self, expr: Expression
    ) -> Tuple[bool, List[Tuple[str, int]]]:
        """Finds named expressions in a sequence or single expression. Returns (is_seq, bindings)."""
        if isinstance(expr, NamedExpr):
            return (False, [(expr.name, 0)])
        if isinstance(expr, SeqExpr):
            bindings: List[Tuple[str, int]] = []
            for i, child in enumerate(expr.elements):
                if isinstance(child, NamedExpr):
                    bindings.append((child.name, i))
            return (True, bindings)
        return (False, [])

    def _build_action_method(
        self,
        method_name: str,
        code: str,
        named_info: Tuple[bool, List[Tuple[str, int]]],
    ) -> str:
        """Constructs a static/instance action method."""
        lines: List[str] = [
            "    @staticmethod",
            f"    def {method_name}(val: Any) -> Any:",
        ]
        lines.extend(self._emit_binding_lines(named_info))
        lines.extend(self._emit_body_lines(code))
        return "\n".join(lines)

    def _emit_binding_lines(
        self, named_info: Tuple[bool, List[Tuple[str, int]]]
    ) -> List[str]:
        is_seq, bindings = named_info
        lines: List[str] = []
        for name, idx in bindings:
            rhs = f"val[{idx}]" if is_seq else "val"
            lines.append(f"        {name} = {rhs}")
        return lines

    def _emit_body_lines(self, code: str) -> List[str]:
        dedented = textwrap.dedent(code).strip()
        body_lines = [line for line in dedented.splitlines() if line.strip()]
        if not body_lines:
            return ["        return val"]
        if len(body_lines) == 1:
            return self._format_single_expr(body_lines[0])
        return self._format_multi_lines(body_lines)

    def _format_single_expr(self, expr_line: str) -> List[str]:
        if expr_line.strip().startswith("return "):
            return [f"        {expr_line}"]
        return [f"        return ({expr_line.strip()})"]

    def _format_multi_lines(self, body_lines: List[str]) -> List[str]:
        lines = [f"        {line}" for line in body_lines]
        if not any(line.strip().startswith("return ") for line in body_lines):
            lines.append("        return val")
        return lines
