#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: MetaGrammar
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

import re
from typing import Any

from core.structures.peg import (
    Choice,
    Lit,
    NotPred,
    OneOrMore,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
    ZeroOrMore,
)
from core.structures.peg_compiler.ast_nodes import (
    ActionExpr,
    AnyCharExpr,
    CharClassExpr,
    ChoiceExpr,
    GrammarDef,
    LitExpr,
    NamedExpr,
    OptExpr,
    PredExpr,
    RegexExpr,
    RepeatExpr,
    RuleDef,
    RuleRefExpr,
    SeqExpr,
)

# User header code


def _unescape_char(char: str) -> str:
    escapes = {"n": "\n", "t": "\t", "r": "\r", '"': '"', "'": "'", "\\": "\\"}
    return escapes.get(char, char)


def _unescape_string(raw: str) -> str:
    content = raw[1:-1]
    return re.sub(r"\\(.)", lambda m: _unescape_char(m.group(1)), content)


class MetaGrammarParser(Parser[Any]):
    """Packrat PEG Parser for MetaGrammar grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_grammar_file = RuleRef("grammar_file")
        self._r_grammar_decl = RuleRef("grammar_decl")
        self._r_header_decl = RuleRef("header_decl")
        self._r_rule_def = RuleRef("rule_def")
        self._r_choice_expr = RuleRef("choice_expr")
        self._r_choice_rest = RuleRef("choice_rest")
        self._r_alt_expr = RuleRef("alt_expr")
        self._r_seq_expr = RuleRef("seq_expr")
        self._r_prefixed = RuleRef("prefixed")
        self._r_new_rule_head = RuleRef("new_rule_head")
        self._r_prefix_item = RuleRef("prefix_item")
        self._r_named_expr = RuleRef("named_expr")
        self._r_pos_pred = RuleRef("pos_pred")
        self._r_neg_pred = RuleRef("neg_pred")
        self._r_suffixed = RuleRef("suffixed")
        self._r_suffix_op = RuleRef("suffix_op")
        self._r_primary = RuleRef("primary")
        self._r_lit_str = RuleRef("lit_str")
        self._r_regex_lit = RuleRef("regex_lit")
        self._r_char_class = RuleRef("char_class")
        self._r_any_char = RuleRef("any_char")
        self._r_group_expr = RuleRef("group_expr")
        self._r_rule_ref = RuleRef("rule_ref")
        self._r_action_block = RuleRef("action_block")
        self._r_action_piece = RuleRef("action_piece")
        self._r_action_sub_block = RuleRef("action_sub_block")
        self._r_ident = RuleRef("ident")
        self._r_str_dq = RuleRef("str_dq")
        self._r_str_sq = RuleRef("str_sq")
        self._r_regex_tok = RuleRef("regex_tok")
        self._r_char_class_tok = RuleRef("char_class_tok")
        self._r_raw_str_dq = RuleRef("raw_str_dq")
        self._r_raw_str_sq = RuleRef("raw_str_sq")
        self._r_ws = RuleRef("ws")

        self._r_grammar_file.define(
            Seq(
                self._r_ws,
                Opt(self._r_grammar_decl),
                Opt(self._r_header_decl),
                OneOrMore(self._r_rule_def),
                Opt(self._r_ws),
            ).map(self._action_grammar_file_0)
        )
        self._r_grammar_decl.define(
            Seq(Lit("grammar"), self._r_ws, self._r_ident).map(
                self._action_grammar_decl_1
            )
        )
        self._r_header_decl.define(
            Seq(Lit("@header"), self._r_ws, self._r_action_block).map(
                self._action_header_decl_2
            )
        )
        self._r_rule_def.define(
            Seq(
                self._r_ident,
                Choice(Lit("<-"), Lit("=")),
                self._r_ws,
                self._r_choice_expr,
                Opt(self._r_action_block),
            ).map(self._action_rule_def_3)
        )
        self._r_choice_expr.define(
            Seq(self._r_alt_expr, ZeroOrMore(self._r_choice_rest)).map(
                self._action_choice_expr_4
            )
        )
        self._r_choice_rest.define(
            Seq(Choice(Lit("/"), Lit("|")), self._r_ws, self._r_alt_expr).map(
                self._action_choice_rest_5
            )
        )
        self._r_alt_expr.define(
            Seq(self._r_seq_expr, Opt(self._r_action_block)).map(
                self._action_alt_expr_6
            )
        )
        self._r_seq_expr.define(
            OneOrMore(self._r_prefixed).map(self._action_seq_expr_7)
        )
        self._r_prefixed.define(
            Seq(NotPred(self._r_new_rule_head), self._r_prefix_item).map(
                self._action_prefixed_8
            )
        )
        self._r_new_rule_head.define(Seq(self._r_ident, Choice(Lit("<-"), Lit("="))))
        self._r_prefix_item.define(
            Choice(
                self._r_named_expr, self._r_pos_pred, self._r_neg_pred, self._r_suffixed
            )
        )
        self._r_named_expr.define(
            Seq(self._r_ident, Lit(":"), self._r_ws, self._r_suffixed).map(
                self._action_named_expr_9
            )
        )
        self._r_pos_pred.define(
            Seq(Lit("&"), self._r_ws, self._r_suffixed).map(self._action_pos_pred_10)
        )
        self._r_neg_pred.define(
            Seq(Lit("!"), self._r_ws, self._r_suffixed).map(self._action_neg_pred_11)
        )
        self._r_suffixed.define(
            Seq(self._r_primary, Opt(self._r_suffix_op)).map(self._action_suffixed_12)
        )
        self._r_suffix_op.define(
            Seq(Choice(Lit("*"), Lit("+"), Lit("?")), self._r_ws).map(
                self._action_suffix_op_13
            )
        )
        self._r_primary.define(
            Choice(
                self._r_lit_str,
                self._r_regex_lit,
                self._r_char_class,
                self._r_any_char,
                self._r_group_expr,
                self._r_rule_ref,
            )
        )
        self._r_lit_str.define(
            Choice(self._r_str_dq, self._r_str_sq).map(self._action_lit_str_14)
        )
        self._r_regex_lit.define(self._r_regex_tok.map(self._action_regex_lit_15))
        self._r_char_class.define(
            self._r_char_class_tok.map(self._action_char_class_16)
        )
        self._r_any_char.define(Seq(Lit("."), self._r_ws).map(self._action_any_char_17))
        self._r_group_expr.define(
            Seq(Lit("("), self._r_ws, self._r_choice_expr, Lit(")"), self._r_ws).map(
                self._action_group_expr_18
            )
        )
        self._r_rule_ref.define(self._r_ident.map(self._action_rule_ref_19))
        self._r_action_block.define(
            Seq(Lit("{"), ZeroOrMore(self._r_action_piece), Lit("}"), self._r_ws).map(
                self._action_action_block_20
            )
        )
        self._r_action_piece.define(
            Choice(
                Reg("[^{}\"'\\\\]+").map(self._action_action_piece_21),
                self._r_raw_str_dq.map(self._action_action_piece_22),
                self._r_raw_str_sq.map(self._action_action_piece_23),
                Reg("\\\\.").map(self._action_action_piece_24),
                self._r_action_sub_block.map(self._action_action_piece_25),
            )
        )
        self._r_action_sub_block.define(
            Seq(Lit("{"), ZeroOrMore(self._r_action_piece), Lit("}")).map(
                self._action_action_sub_block_26
            )
        )
        self._r_ident.define(
            Seq(Reg("[A-Za-z_][A-Za-z0-9_]*"), self._r_ws).map(self._action_ident_27)
        )
        self._r_str_dq.define(
            Seq(self._r_raw_str_dq, self._r_ws).map(self._action_str_dq_28)
        )
        self._r_str_sq.define(
            Seq(self._r_raw_str_sq, self._r_ws).map(self._action_str_sq_29)
        )
        self._r_regex_tok.define(
            Seq(Reg("/(?![ \\t\\r\\n])((?:[^\\r\\n/]|\\\\.)+)/"), self._r_ws).map(
                self._action_regex_tok_30
            )
        )
        self._r_char_class_tok.define(
            Seq(Reg("\\[\\^?(?:\\\\\\]|[^\\]])+\\]"), self._r_ws).map(
                self._action_char_class_tok_31
            )
        )
        self._r_raw_str_dq.define(Reg('"(?:[^"\\\\]|\\\\.)*"'))
        self._r_raw_str_sq.define(Reg("'(?:[^'\\\\]|\\\\.)*'"))
        self._r_ws.define(Reg("(?:\\s+|#[^\\r\\n]*)*"))

        self.root_parser: Parser[Any] = self._r_grammar_file

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_grammar_file_0(val: Any) -> Any:
        g_decl = val[1]
        h_decl = val[2]
        rules = val[3]
        name_str = g_decl if g_decl is not None else "GeneratedParser"
        hdr_str = h_decl if h_decl is not None else ""
        start_r = rules[0].name if rules else None
        return GrammarDef(
            name=name_str, rules=rules, header_code=hdr_str, start_rule=start_r
        )

    @staticmethod
    def _action_grammar_decl_1(val: Any) -> Any:
        name = val[2]
        return name

    @staticmethod
    def _action_header_decl_2(val: Any) -> Any:
        act = val[2]
        return act

    @staticmethod
    def _action_rule_def_3(val: Any) -> Any:
        name = val[0]
        ch = val[3]
        act = val[4]
        final_expr = ch
        if act is not None:
            final_expr = ActionExpr(ch, act)
        return RuleDef(name=name, expr=final_expr)

    @staticmethod
    def _action_choice_expr_4(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        if not rest:
            return first
        alts = [first] + rest
        return ChoiceExpr(alts)

    @staticmethod
    def _action_choice_rest_5(val: Any) -> Any:
        alt = val[2]
        return alt

    @staticmethod
    def _action_alt_expr_6(val: Any) -> Any:
        seq = val[0]
        act = val[1]
        if act is not None:
            return ActionExpr(seq, act)
        return seq

    @staticmethod
    def _action_seq_expr_7(val: Any) -> Any:
        items = val
        if len(items) == 1:
            return items[0]
        return SeqExpr(items)

    @staticmethod
    def _action_prefixed_8(val: Any) -> Any:
        item = val[1]
        return item

    @staticmethod
    def _action_named_expr_9(val: Any) -> Any:
        name = val[0]
        expr = val[3]
        return NamedExpr(name=name, expr=expr)

    @staticmethod
    def _action_pos_pred_10(val: Any) -> Any:
        expr = val[2]
        return PredExpr(expr, is_positive=True)

    @staticmethod
    def _action_neg_pred_11(val: Any) -> Any:
        expr = val[2]
        return PredExpr(expr, is_positive=False)

    @staticmethod
    def _action_suffixed_12(val: Any) -> Any:
        expr = val[0]
        op = val[1]
        if op == "*":
            return RepeatExpr(expr, min_count=0)
        if op == "+":
            return RepeatExpr(expr, min_count=1)
        if op == "?":
            return OptExpr(expr)
        return expr

    @staticmethod
    def _action_suffix_op_13(val: Any) -> Any:
        op = val[0]
        return op

    @staticmethod
    def _action_lit_str_14(val: Any) -> Any:
        raw = val
        return LitExpr(_unescape_string(raw))

    @staticmethod
    def _action_regex_lit_15(val: Any) -> Any:
        raw = val
        pattern = raw[1:-1].replace(r"\/", "/")
        return RegexExpr(pattern)

    @staticmethod
    def _action_char_class_16(val: Any) -> Any:
        raw = val
        inv = raw.startswith("[^")
        spec = raw[2:-1] if inv else raw[1:-1]
        return CharClassExpr(raw_spec=spec, inverted=inv)

    @staticmethod
    def _action_any_char_17(val: Any) -> Any:
        return AnyCharExpr()

    @staticmethod
    def _action_group_expr_18(val: Any) -> Any:
        ch = val[2]
        return ch

    @staticmethod
    def _action_rule_ref_19(val: Any) -> Any:
        name = val
        return RuleRefExpr(name)

    @staticmethod
    def _action_action_block_20(val: Any) -> Any:
        pieces = val[1]
        return "".join(pieces)

    @staticmethod
    def _action_action_piece_21(val: Any) -> Any:
        chunk = val
        return chunk

    @staticmethod
    def _action_action_piece_22(val: Any) -> Any:
        dq = val
        return dq

    @staticmethod
    def _action_action_piece_23(val: Any) -> Any:
        sq = val
        return sq

    @staticmethod
    def _action_action_piece_24(val: Any) -> Any:
        esc = val
        return esc

    @staticmethod
    def _action_action_piece_25(val: Any) -> Any:
        sub = val
        return sub

    @staticmethod
    def _action_action_sub_block_26(val: Any) -> Any:
        pieces = val[1]
        return "{" + "".join(pieces) + "}"

    @staticmethod
    def _action_ident_27(val: Any) -> Any:
        name = val[0]
        return name

    @staticmethod
    def _action_str_dq_28(val: Any) -> Any:
        s = val[0]
        return s

    @staticmethod
    def _action_str_sq_29(val: Any) -> Any:
        s = val[0]
        return s

    @staticmethod
    def _action_regex_tok_30(val: Any) -> Any:
        r = val[0]
        return r

    @staticmethod
    def _action_char_class_tok_31(val: Any) -> Any:
        raw = val[0]
        return raw
