#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: SQLDQL
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

import ast as py_ast
import re
from typing import Any, Dict, List, Optional, Tuple

from core.structures.peg import (
    Choice,
    Lit,
    NotPred,
    OneOrMore,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
    ZeroOrMore,
)

# User header code


try:
    from .ast import (
        CTEDefinition,
        JoinClause,
        JoinType,
        SelectStatement,
        SQLCommandType,
        TableRef,
    )
except (ImportError, ValueError):
    from database.sql.ast import (
        CTEDefinition,
        JoinClause,
        JoinType,
        SelectStatement,
        SQLCommandType,
        TableRef,
    )


def _extract_knn_from_where(where_raw: str) -> Tuple[str, Optional[Dict[str, Any]]]:
    knn_m = re.search(
        r"KNN\s*\(\s*([a-zA-Z0-9_\.]+)\s*,\s*(\[.*?\])\s*,\s*([0-9]+)\s*\)",
        where_raw,
        re.IGNORECASE,
    )
    if not knn_m:
        knn_m = re.search(
            r"([a-zA-Z0-9_\.]+)\s+KNN\s+(\[.*?\])\s+TOP\s+([0-9]+)",
            where_raw,
            re.IGNORECASE,
        )
    if not knn_m:
        return where_raw, None

    knn_col = knn_m.group(1)
    try:
        knn_vec = py_ast.literal_eval(knn_m.group(2))
    except Exception as e:
        from database.sql.dql_parser import SQLParseError

        raise SQLParseError(f"Invalid vector in KNN clause: {e}") from e
    top_k = int(knn_m.group(3))
    knn_query: Dict[str, Any] = {
        "column": knn_col,
        "vector": [float(x) for x in knn_vec],
        "top_k": top_k,
    }
    cleaned = where_raw.replace(knn_m.group(0), "").strip()
    cleaned = re.sub(r"^(AND|OR)\s+", "", cleaned, flags=re.IGNORECASE).strip()
    cleaned = re.sub(r"\s+(AND|OR)$", "", cleaned, flags=re.IGNORECASE).strip()
    return cleaned, knn_query


def _parse_where_condition_terms(where_str: str) -> List[Dict[str, Any]]:
    clean = where_str.strip()
    if not clean:
        return []
    from database.sql.parser import SQLParser

    dummy_parser = SQLParser()
    return dummy_parser._extract_where_clauses(clean)


def _split_tvf_args(raw_args: Optional[str]) -> List[str]:
    if not raw_args:
        return []
    from database.sql.parser import _split_comma_expressions

    return _split_comma_expressions(raw_args)


def _set_compound_attr(base: SelectStatement, op: str, part: SelectStatement) -> None:
    attr_map = {
        "UNION": "union",
        "UNION ALL": "union_all",
        "INTERSECT": "intersect",
        "EXCEPT": "except_",
    }
    field = attr_map.get(op)
    if field and getattr(base, field) is None:
        setattr(base, field, part)


def _apply_compounds(
    base: SelectStatement,
    compounds: List[Tuple[str, SelectStatement]],
) -> SelectStatement:
    for op, part in compounds:
        base.compounds.append((op, part))
        _set_compound_attr(base, op, part)
    return base


def _unpack_order(
    order: Optional[Tuple[str, bool, Optional[str]]],
) -> Tuple[Optional[str], bool, Optional[str]]:
    if not order:
        return None, False, None
    return order[0], order[1], order[2]


def _unpack_limit(
    limit: Optional[Tuple[Optional[int], Optional[int]]],
) -> Tuple[Optional[int], Optional[int]]:
    if not limit:
        return None, None
    return limit[0], limit[1]


def _unpack_from_part(
    from_part: Optional[Tuple[TableRef, List[JoinClause]]],
) -> Tuple[str, Optional[TableRef], List[JoinClause]]:
    if not from_part:
        return "", None, []
    tbl_ref = from_part[0]
    tbl_name = tbl_ref.name or tbl_ref.alias or ""
    return tbl_name, tbl_ref, from_part[1]


def _unpack_where_part(
    where_part: Optional[str],
) -> Tuple[List[Dict[str, Any]], Optional[Dict[str, Any]]]:
    if not where_part:
        return [], None
    clean_where, knn_query = _extract_knn_from_where(where_part)
    where_clauses = _parse_where_condition_terms(clean_where)
    return where_clauses, knn_query


def _assemble_single_select(
    dist: Any,
    projs: List[str],
    from_part: Optional[Tuple[TableRef, List[JoinClause]]],
    where_part: Optional[str],
    group_part: Optional[List[str]],
    having_part: Optional[str],
    order_part: Optional[Tuple[str, bool, Optional[str]]],
    limit_part: Optional[Tuple[Optional[int], Optional[int]]],
) -> SelectStatement:
    tbl_name, tbl_ref, joins_list = _unpack_from_part(from_part)
    where_clauses, knn_query = _unpack_where_part(where_part)
    order_col, order_desc, order_collate = _unpack_order(order_part)
    lim_val, off_val = _unpack_limit(limit_part)
    return SelectStatement(
        command_type=SQLCommandType.SELECT,
        raw_sql="",
        table_name=tbl_name,
        table_ref=tbl_ref,
        columns=projs,
        where_clauses=where_clauses,
        knn_query=knn_query,
        joins=joins_list,
        distinct=bool(dist),
        group_by=group_part or [],
        having=having_part,
        order_by=order_col,
        order_desc=order_desc,
        order_collate=order_collate,
        limit=lim_val,
        offset=off_val,
    )


def _assemble_values_statement(
    rows: List[List[Any]],
    order: Optional[Tuple[str, bool, Optional[str]]],
    limit: Optional[Tuple[Optional[int], Optional[int]]],
) -> SelectStatement:
    ncols = len(rows[0]) if rows else 0
    cols = [f"column{i + 1}" for i in range(ncols)]
    order_col, order_desc, order_collate = _unpack_order(order)
    lim_val, off_val = _unpack_limit(limit)
    return SelectStatement(
        command_type=SQLCommandType.SELECT,
        raw_sql="",
        table_name="",
        columns=cols,
        values_rows=rows,
        order_by=order_col,
        order_desc=order_desc,
        order_collate=order_collate,
        limit=lim_val,
        offset=off_val,
    )


class SQLDQLParser(Parser[Any]):
    """Packrat PEG Parser for SQLDQL grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_root = RuleRef("root")
        self._r_full_dql = RuleRef("full_dql")
        self._r_cte_clause = RuleRef("cte_clause")
        self._r_cte_def_list = RuleRef("cte_def_list")
        self._r_cte_def = RuleRef("cte_def")
        self._r_ident_list = RuleRef("ident_list")
        self._r_compound_query = RuleRef("compound_query")
        self._r_compound_op = RuleRef("compound_op")
        self._r_union_all_kw = RuleRef("union_all_kw")
        self._r_union_kw = RuleRef("union_kw")
        self._r_intersect_kw = RuleRef("intersect_kw")
        self._r_except_kw = RuleRef("except_kw")
        self._r_core_query = RuleRef("core_query")
        self._r_values_statement = RuleRef("values_statement")
        self._r_value_row_list = RuleRef("value_row_list")
        self._r_value_row = RuleRef("value_row")
        self._r_value_atom = RuleRef("value_atom")
        self._r_single_select = RuleRef("single_select")
        self._r_distinct_modifier = RuleRef("distinct_modifier")
        self._r_projection_list = RuleRef("projection_list")
        self._r_projection_item = RuleRef("projection_item")
        self._r_star = RuleRef("star")
        self._r_table_star = RuleRef("table_star")
        self._r_proj_expr = RuleRef("proj_expr")
        self._r_proj_chunk = RuleRef("proj_chunk")
        self._r_from_clause = RuleRef("from_clause")
        self._r_table_ref = RuleRef("table_ref")
        self._r_subquery_table_ref = RuleRef("subquery_table_ref")
        self._r_tvf_table_ref = RuleRef("tvf_table_ref")
        self._r_tvf_args_content = RuleRef("tvf_args_content")
        self._r_plain_table_ref = RuleRef("plain_table_ref")
        self._r_index_hint = RuleRef("index_hint")
        self._r_alias_clause = RuleRef("alias_clause")
        self._r_join_clause = RuleRef("join_clause")
        self._r_comma_join = RuleRef("comma_join")
        self._r_explicit_join = RuleRef("explicit_join")
        self._r_join_type_spec = RuleRef("join_type_spec")
        self._r_join_condition = RuleRef("join_condition")
        self._r_on_condition_expr = RuleRef("on_condition_expr")
        self._r_on_chunk = RuleRef("on_chunk")
        self._r_on_end = RuleRef("on_end")
        self._r_where_clause = RuleRef("where_clause")
        self._r_where_body_expr = RuleRef("where_body_expr")
        self._r_where_chunk = RuleRef("where_chunk")
        self._r_where_end = RuleRef("where_end")
        self._r_group_by_clause = RuleRef("group_by_clause")
        self._r_ident_or_expr_list = RuleRef("ident_or_expr_list")
        self._r_group_item = RuleRef("group_item")
        self._r_having_clause = RuleRef("having_clause")
        self._r_having_body_expr = RuleRef("having_body_expr")
        self._r_having_chunk = RuleRef("having_chunk")
        self._r_having_end = RuleRef("having_end")
        self._r_order_by_clause = RuleRef("order_by_clause")
        self._r_order_item_list = RuleRef("order_item_list")
        self._r_order_item = RuleRef("order_item")
        self._r_order_col = RuleRef("order_col")
        self._r_order_dir = RuleRef("order_dir")
        self._r_nulls_clause = RuleRef("nulls_clause")
        self._r_limit_offset_clause = RuleRef("limit_offset_clause")
        self._r_integer_num = RuleRef("integer_num")
        self._r_clause_end = RuleRef("clause_end")
        self._r_chunk_token = RuleRef("chunk_token")
        self._r_func_call_token = RuleRef("func_call_token")
        self._r_paren_token = RuleRef("paren_token")
        self._r_bracket_token = RuleRef("bracket_token")
        self._r_non_ws_token = RuleRef("non_ws_token")
        self._r_ident = RuleRef("ident")
        self._r_ident_pattern = RuleRef("ident_pattern")
        self._r_backtick_pattern = RuleRef("backtick_pattern")
        self._r_double_quote_pattern = RuleRef("double_quote_pattern")
        self._r_non_reserved_ident = RuleRef("non_reserved_ident")
        self._r_reserved_kw = RuleRef("reserved_kw")
        self._r_string_literal = RuleRef("string_literal")
        self._r_double_quote_literal = RuleRef("double_quote_literal")
        self._r_number_literal = RuleRef("number_literal")
        self._r_select_kw = RuleRef("select_kw")
        self._r_from_kw = RuleRef("from_kw")
        self._r_where_kw = RuleRef("where_kw")
        self._r_group_kw = RuleRef("group_kw")
        self._r_by_kw = RuleRef("by_kw")
        self._r_having_kw = RuleRef("having_kw")
        self._r_window_kw = RuleRef("window_kw")
        self._r_order_kw = RuleRef("order_kw")
        self._r_limit_kw = RuleRef("limit_kw")
        self._r_offset_kw = RuleRef("offset_kw")
        self._r_join_kw = RuleRef("join_kw")
        self._r_inner_kw = RuleRef("inner_kw")
        self._r_left_kw = RuleRef("left_kw")
        self._r_right_kw = RuleRef("right_kw")
        self._r_cross_kw = RuleRef("cross_kw")
        self._r_natural_kw = RuleRef("natural_kw")
        self._r_outer_kw = RuleRef("outer_kw")
        self._r_on_kw = RuleRef("on_kw")
        self._r_using_kw = RuleRef("using_kw")
        self._r_with_kw = RuleRef("with_kw")
        self._r_recursive_kw = RuleRef("recursive_kw")
        self._r_as_kw = RuleRef("as_kw")
        self._r_indexed_kw = RuleRef("indexed_kw")
        self._r_not_kw = RuleRef("not_kw")
        self._r_values_kw = RuleRef("values_kw")
        self._r_distinct_kw = RuleRef("distinct_kw")
        self._r_all_kw = RuleRef("all_kw")
        self._r_collate_kw = RuleRef("collate_kw")
        self._r_asc_kw = RuleRef("asc_kw")
        self._r_desc_kw = RuleRef("desc_kw")
        self._r_nulls_kw = RuleRef("nulls_kw")
        self._r_first_kw = RuleRef("first_kw")
        self._r_last_kw = RuleRef("last_kw")
        self._r_true_kw = RuleRef("true_kw")
        self._r_false_kw = RuleRef("false_kw")
        self._r_null_kw = RuleRef("null_kw")
        self._r_ws = RuleRef("ws")
        self._r_opt_ws = RuleRef("opt_ws")

        self._r_root.define(
            Seq(self._r_opt_ws, self._r_full_dql, self._r_opt_ws).map(
                self._action_root_0
            )
        )
        self._r_full_dql.define(
            Seq(
                Opt(Seq(self._r_cte_clause, self._r_ws).map(self._action_full_dql_1)),
                self._r_compound_query,
            ).map(self._action_full_dql_2)
        )
        self._r_cte_clause.define(
            Seq(
                self._r_with_kw,
                Opt(Seq(self._r_ws, self._r_recursive_kw)),
                self._r_ws,
                self._r_cte_def_list,
            ).map(self._action_cte_clause_3)
        )
        self._r_cte_def_list.define(
            Seq(
                self._r_cte_def,
                ZeroOrMore(
                    Seq(self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_cte_def).map(
                        self._action_cte_def_list_4
                    )
                ),
            ).map(self._action_cte_def_list_5)
        )
        self._r_cte_def.define(
            Seq(
                self._r_ident,
                Opt(
                    Seq(
                        self._r_opt_ws,
                        Lit("("),
                        self._r_opt_ws,
                        self._r_ident_list,
                        self._r_opt_ws,
                        Lit(")"),
                    ).map(self._action_cte_def_6)
                ),
                self._r_ws,
                self._r_as_kw,
                self._r_ws,
                Lit("("),
                self._r_opt_ws,
                self._r_full_dql,
                self._r_opt_ws,
                Lit(")"),
            ).map(self._action_cte_def_7)
        )
        self._r_ident_list.define(
            Seq(
                self._r_ident,
                ZeroOrMore(
                    Seq(self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_ident).map(
                        self._action_ident_list_8
                    )
                ),
            ).map(self._action_ident_list_9)
        )
        self._r_compound_query.define(
            Seq(
                self._r_core_query,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws,
                        self._r_compound_op,
                        self._r_ws,
                        self._r_core_query,
                    ).map(self._action_compound_query_10)
                ),
            ).map(self._action_compound_query_11)
        )
        self._r_compound_op.define(
            Choice(
                self._r_union_all_kw,
                self._r_union_kw,
                self._r_intersect_kw,
                self._r_except_kw,
            )
        )
        self._r_union_all_kw.define(
            Reg("(?i)\\bUNION\\s+ALL\\b").map(self._action_union_all_kw_12)
        )
        self._r_union_kw.define(Reg("(?i)\\bUNION\\b").map(self._action_union_kw_13))
        self._r_intersect_kw.define(
            Reg("(?i)\\bINTERSECT\\b").map(self._action_intersect_kw_14)
        )
        self._r_except_kw.define(Reg("(?i)\\bEXCEPT\\b").map(self._action_except_kw_15))
        self._r_core_query.define(
            Choice(self._r_single_select, self._r_values_statement)
        )
        self._r_values_statement.define(
            Seq(
                self._r_values_kw,
                self._r_ws,
                self._r_value_row_list,
                Opt(
                    Seq(self._r_opt_ws, self._r_order_by_clause).map(
                        self._action_values_statement_16
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_limit_offset_clause).map(
                        self._action_values_statement_17
                    )
                ),
            ).map(self._action_values_statement_18)
        )
        self._r_value_row_list.define(
            Seq(
                self._r_value_row,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_value_row
                    ).map(self._action_value_row_list_19)
                ),
            ).map(self._action_value_row_list_20)
        )
        self._r_value_row.define(
            Seq(
                Lit("("),
                self._r_opt_ws,
                self._r_value_atom,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_value_atom
                    ).map(self._action_value_row_21)
                ),
                self._r_opt_ws,
                Lit(")"),
            ).map(self._action_value_row_22)
        )
        self._r_value_atom.define(
            Choice(
                self._r_string_literal.map(self._action_value_atom_23),
                self._r_number_literal.map(self._action_value_atom_24),
                self._r_true_kw.map(self._action_value_atom_25),
                self._r_false_kw.map(self._action_value_atom_26),
                self._r_null_kw.map(self._action_value_atom_27),
            )
        )
        self._r_single_select.define(
            Seq(
                self._r_select_kw,
                Opt(
                    Seq(self._r_ws, self._r_distinct_modifier).map(
                        self._action_single_select_28
                    )
                ),
                self._r_ws,
                self._r_projection_list,
                Opt(
                    Seq(self._r_opt_ws, self._r_from_clause).map(
                        self._action_single_select_29
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_where_clause).map(
                        self._action_single_select_30
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_group_by_clause).map(
                        self._action_single_select_31
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_having_clause).map(
                        self._action_single_select_32
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_order_by_clause).map(
                        self._action_single_select_33
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_limit_offset_clause).map(
                        self._action_single_select_34
                    )
                ),
            ).map(self._action_single_select_35)
        )
        self._r_distinct_modifier.define(
            Choice(
                self._r_distinct_kw.map(self._action_distinct_modifier_36),
                self._r_all_kw.map(self._action_distinct_modifier_37),
            )
        )
        self._r_projection_list.define(
            Seq(
                self._r_projection_item,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws,
                        Lit(","),
                        self._r_opt_ws,
                        self._r_projection_item,
                    ).map(self._action_projection_list_38)
                ),
            ).map(self._action_projection_list_39)
        )
        self._r_projection_item.define(
            Choice(self._r_table_star, self._r_star, self._r_proj_expr)
        )
        self._r_star.define(Lit("*").map(self._action_star_40))
        self._r_table_star.define(
            Seq(self._r_ident, self._r_opt_ws, Lit("."), self._r_opt_ws, Lit("*")).map(
                self._action_table_star_41
            )
        )
        self._r_proj_expr.define(
            OneOrMore(self._r_proj_chunk).map(self._action_proj_expr_42)
        )
        self._r_proj_chunk.define(
            Seq(NotPred(self._r_clause_end), self._r_chunk_token, self._r_opt_ws).map(
                self._action_proj_chunk_43
            )
        )
        self._r_from_clause.define(
            Seq(
                self._r_from_kw,
                self._r_ws,
                self._r_table_ref,
                ZeroOrMore(
                    Seq(self._r_opt_ws, self._r_join_clause).map(
                        self._action_from_clause_44
                    )
                ),
            ).map(self._action_from_clause_45)
        )
        self._r_table_ref.define(
            Choice(
                self._r_subquery_table_ref,
                self._r_tvf_table_ref,
                self._r_plain_table_ref,
            )
        )
        self._r_subquery_table_ref.define(
            Seq(
                Lit("("),
                self._r_opt_ws,
                self._r_full_dql,
                self._r_opt_ws,
                Lit(")"),
                Opt(
                    Seq(self._r_ws, self._r_alias_clause).map(
                        self._action_subquery_table_ref_46
                    )
                ),
            ).map(self._action_subquery_table_ref_47)
        )
        self._r_tvf_table_ref.define(
            Seq(
                self._r_non_reserved_ident,
                self._r_opt_ws,
                Lit("("),
                Opt(self._r_tvf_args_content),
                Lit(")"),
                Opt(
                    Seq(self._r_ws, self._r_alias_clause).map(
                        self._action_tvf_table_ref_48
                    )
                ),
            ).map(self._action_tvf_table_ref_49)
        )
        self._r_tvf_args_content.define(
            Reg("[^)]+").map(self._action_tvf_args_content_50)
        )
        self._r_plain_table_ref.define(
            Choice(
                Seq(
                    self._r_non_reserved_ident,
                    Opt(
                        Seq(self._r_ws, self._r_alias_clause).map(
                            self._action_plain_table_ref_51
                        )
                    ),
                    Opt(
                        Seq(self._r_ws, self._r_index_hint).map(
                            self._action_plain_table_ref_52
                        )
                    ),
                ).map(self._action_plain_table_ref_53),
                Seq(
                    self._r_non_reserved_ident,
                    Seq(self._r_ws, self._r_index_hint).map(
                        self._action_plain_table_ref_54
                    ),
                    Opt(
                        Seq(self._r_ws, self._r_alias_clause).map(
                            self._action_plain_table_ref_55
                        )
                    ),
                ).map(self._action_plain_table_ref_56),
            )
        )
        self._r_index_hint.define(
            Choice(
                Seq(
                    self._r_indexed_kw,
                    self._r_ws,
                    self._r_by_kw,
                    self._r_ws,
                    self._r_non_reserved_ident,
                ).map(self._action_index_hint_57),
                Seq(self._r_not_kw, self._r_ws, self._r_indexed_kw).map(
                    self._action_index_hint_58
                ),
            )
        )
        self._r_alias_clause.define(
            Choice(
                Seq(self._r_as_kw, self._r_ws, self._r_ident).map(
                    self._action_alias_clause_59
                ),
                self._r_non_reserved_ident.map(self._action_alias_clause_60),
            )
        )
        self._r_join_clause.define(Choice(self._r_comma_join, self._r_explicit_join))
        self._r_comma_join.define(
            Seq(Lit(","), self._r_opt_ws, self._r_table_ref).map(
                self._action_comma_join_61
            )
        )
        self._r_explicit_join.define(
            Seq(
                Opt(Seq(self._r_natural_kw, self._r_ws)),
                Opt(self._r_join_type_spec),
                self._r_join_kw,
                self._r_ws,
                self._r_table_ref,
                Opt(
                    Seq(self._r_ws, self._r_join_condition).map(
                        self._action_explicit_join_62
                    )
                ),
            ).map(self._action_explicit_join_63)
        )
        self._r_join_type_spec.define(
            Choice(
                Seq(self._r_inner_kw, self._r_ws).map(self._action_join_type_spec_64),
                Seq(
                    self._r_left_kw, Opt(Seq(self._r_ws, self._r_outer_kw)), self._r_ws
                ).map(self._action_join_type_spec_65),
                Seq(
                    self._r_right_kw, Opt(Seq(self._r_ws, self._r_outer_kw)), self._r_ws
                ).map(self._action_join_type_spec_66),
                Seq(self._r_cross_kw, self._r_ws).map(self._action_join_type_spec_67),
            )
        )
        self._r_join_condition.define(
            Choice(
                Seq(self._r_on_kw, self._r_ws, self._r_on_condition_expr).map(
                    self._action_join_condition_68
                ),
                Seq(
                    self._r_using_kw,
                    self._r_opt_ws,
                    Lit("("),
                    self._r_opt_ws,
                    self._r_ident_list,
                    self._r_opt_ws,
                    Lit(")"),
                ).map(self._action_join_condition_69),
            )
        )
        self._r_on_condition_expr.define(
            OneOrMore(self._r_on_chunk).map(self._action_on_condition_expr_70)
        )
        self._r_on_chunk.define(
            Seq(NotPred(self._r_on_end), self._r_chunk_token, self._r_opt_ws).map(
                self._action_on_chunk_71
            )
        )
        self._r_on_end.define(
            Choice(
                self._r_natural_kw,
                self._r_join_kw,
                self._r_inner_kw,
                self._r_left_kw,
                self._r_right_kw,
                self._r_cross_kw,
                self._r_where_kw,
                self._r_group_kw,
                self._r_having_kw,
                self._r_window_kw,
                self._r_order_kw,
                self._r_limit_kw,
                self._r_union_kw,
                self._r_intersect_kw,
                self._r_except_kw,
                Lit(";"),
            )
        )
        self._r_where_clause.define(
            Seq(self._r_where_kw, self._r_ws, self._r_where_body_expr).map(
                self._action_where_clause_72
            )
        )
        self._r_where_body_expr.define(
            OneOrMore(self._r_where_chunk).map(self._action_where_body_expr_73)
        )
        self._r_where_chunk.define(
            Seq(NotPred(self._r_where_end), self._r_chunk_token, self._r_opt_ws).map(
                self._action_where_chunk_74
            )
        )
        self._r_where_end.define(
            Choice(
                self._r_group_kw,
                self._r_having_kw,
                self._r_window_kw,
                self._r_order_kw,
                self._r_limit_kw,
                self._r_union_kw,
                self._r_intersect_kw,
                self._r_except_kw,
                Lit(";"),
            )
        )
        self._r_group_by_clause.define(
            Seq(
                self._r_group_kw,
                self._r_ws,
                self._r_by_kw,
                self._r_ws,
                self._r_ident_or_expr_list,
            ).map(self._action_group_by_clause_75)
        )
        self._r_ident_or_expr_list.define(
            Seq(
                self._r_group_item,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_group_item
                    ).map(self._action_ident_or_expr_list_76)
                ),
            ).map(self._action_ident_or_expr_list_77)
        )
        self._r_group_item.define(
            Reg("[a-zA-Z0-9_\\.\\->>\\'\\\"]+").map(self._action_group_item_78)
        )
        self._r_having_clause.define(
            Seq(self._r_having_kw, self._r_ws, self._r_having_body_expr).map(
                self._action_having_clause_79
            )
        )
        self._r_having_body_expr.define(
            OneOrMore(self._r_having_chunk).map(self._action_having_body_expr_80)
        )
        self._r_having_chunk.define(
            Seq(NotPred(self._r_having_end), self._r_chunk_token, self._r_opt_ws).map(
                self._action_having_chunk_81
            )
        )
        self._r_having_end.define(
            Choice(
                self._r_window_kw,
                self._r_order_kw,
                self._r_limit_kw,
                self._r_union_kw,
                self._r_intersect_kw,
                self._r_except_kw,
                Lit(";"),
            )
        )
        self._r_order_by_clause.define(
            Seq(
                self._r_order_kw,
                self._r_ws,
                self._r_by_kw,
                self._r_ws,
                self._r_order_item_list,
            ).map(self._action_order_by_clause_82)
        )
        self._r_order_item_list.define(
            Seq(
                self._r_order_item,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_order_item
                    ).map(self._action_order_item_list_83)
                ),
            ).map(self._action_order_item_list_84)
        )
        self._r_order_item.define(
            Seq(
                self._r_order_col,
                Opt(
                    Seq(self._r_ws, self._r_collate_kw, self._r_ws, self._r_ident).map(
                        self._action_order_item_85
                    )
                ),
                Opt(Seq(self._r_ws, self._r_order_dir).map(self._action_order_item_86)),
                Opt(Seq(self._r_ws, self._r_nulls_clause)),
            ).map(self._action_order_item_87)
        )
        self._r_order_col.define(
            Reg("[a-zA-Z0-9_\\.\\->>\\'\\\"]+").map(self._action_order_col_88)
        )
        self._r_order_dir.define(
            Choice(
                self._r_asc_kw.map(self._action_order_dir_89),
                self._r_desc_kw.map(self._action_order_dir_90),
            )
        )
        self._r_nulls_clause.define(
            Seq(self._r_nulls_kw, self._r_ws, Choice(self._r_first_kw, self._r_last_kw))
        )
        self._r_limit_offset_clause.define(
            Choice(
                Seq(
                    self._r_limit_kw,
                    self._r_ws,
                    self._r_integer_num,
                    self._r_ws,
                    self._r_offset_kw,
                    self._r_ws,
                    self._r_integer_num,
                ).map(self._action_limit_offset_clause_91),
                Seq(
                    self._r_limit_kw,
                    self._r_ws,
                    self._r_integer_num,
                    self._r_opt_ws,
                    Lit(","),
                    self._r_opt_ws,
                    self._r_integer_num,
                ).map(self._action_limit_offset_clause_92),
                Seq(self._r_limit_kw, self._r_ws, self._r_integer_num).map(
                    self._action_limit_offset_clause_93
                ),
            )
        )
        self._r_integer_num.define(Reg("[0-9]+").map(self._action_integer_num_94))
        self._r_clause_end.define(
            Choice(
                self._r_from_kw,
                self._r_where_kw,
                self._r_group_kw,
                self._r_having_kw,
                self._r_window_kw,
                self._r_order_kw,
                self._r_limit_kw,
                self._r_union_kw,
                self._r_intersect_kw,
                self._r_except_kw,
                Lit(";"),
            )
        )
        self._r_chunk_token.define(
            Choice(
                self._r_func_call_token,
                self._r_paren_token,
                self._r_bracket_token,
                self._r_string_literal,
                self._r_double_quote_literal,
                self._r_non_ws_token,
            )
        )
        self._r_func_call_token.define(
            Seq(
                NotPred(self._r_clause_end),
                Reg("[a-zA-Z_][a-zA-Z0-9_]*"),
                Reg("\\s*\\((?:[^()]|\\([^()]*\\))*\\)"),
            ).map(self._action_func_call_token_95)
        )
        self._r_paren_token.define(
            Reg("\\((?:[^()]|\\([^()]*\\))*\\)").map(self._action_paren_token_96)
        )
        self._r_bracket_token.define(
            Reg("\\[(?:[^\\[\\]]|\\[[^\\[\\]]*\\])*\\]").map(
                self._action_bracket_token_97
            )
        )
        self._r_non_ws_token.define(
            Seq(NotPred(self._r_clause_end), Reg("[^\\s,;()]+")).map(
                self._action_non_ws_token_98
            )
        )
        self._r_ident.define(
            Choice(
                self._r_ident_pattern.map(self._action_ident_99),
                self._r_backtick_pattern.map(self._action_ident_100),
                self._r_double_quote_pattern.map(self._action_ident_101),
            )
        )
        self._r_ident_pattern.define(
            Reg("[a-zA-Z_][a-zA-Z0-9_]*(\\.[a-zA-Z_][a-zA-Z0-9_]*)?").map(
                self._action_ident_pattern_102
            )
        )
        self._r_backtick_pattern.define(
            Reg("`[^`]*`").map(self._action_backtick_pattern_103)
        )
        self._r_double_quote_pattern.define(
            Reg('"[^"]*"').map(self._action_double_quote_pattern_104)
        )
        self._r_non_reserved_ident.define(
            Seq(NotPred(self._r_reserved_kw), self._r_ident).map(
                self._action_non_reserved_ident_105
            )
        )
        self._r_reserved_kw.define(
            Choice(
                self._r_select_kw,
                self._r_from_kw,
                self._r_where_kw,
                self._r_group_kw,
                self._r_by_kw,
                self._r_having_kw,
                self._r_window_kw,
                self._r_order_kw,
                self._r_limit_kw,
                self._r_offset_kw,
                self._r_join_kw,
                self._r_inner_kw,
                self._r_left_kw,
                self._r_right_kw,
                self._r_cross_kw,
                self._r_natural_kw,
                self._r_on_kw,
                self._r_using_kw,
                self._r_union_kw,
                self._r_intersect_kw,
                self._r_except_kw,
                self._r_with_kw,
                self._r_recursive_kw,
                self._r_as_kw,
                self._r_indexed_kw,
                self._r_not_kw,
                self._r_values_kw,
                self._r_distinct_kw,
                self._r_all_kw,
            )
        )
        self._r_string_literal.define(
            Reg("'([^']|'')*'").map(self._action_string_literal_106)
        )
        self._r_double_quote_literal.define(
            Reg('"([^"\\\\]|\\\\.)*"').map(self._action_double_quote_literal_107)
        )
        self._r_number_literal.define(
            Reg("[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?").map(
                self._action_number_literal_108
            )
        )
        self._r_select_kw.define(Reg("(?i)\\bSELECT\\b"))
        self._r_from_kw.define(Reg("(?i)\\bFROM\\b"))
        self._r_where_kw.define(Reg("(?i)\\bWHERE\\b"))
        self._r_group_kw.define(Reg("(?i)\\bGROUP\\b"))
        self._r_by_kw.define(Reg("(?i)\\bBY\\b"))
        self._r_having_kw.define(Reg("(?i)\\bHAVING\\b"))
        self._r_window_kw.define(Reg("(?i)\\bWINDOW\\b"))
        self._r_order_kw.define(Reg("(?i)\\bORDER\\b"))
        self._r_limit_kw.define(Reg("(?i)\\bLIMIT\\b"))
        self._r_offset_kw.define(Reg("(?i)\\bOFFSET\\b"))
        self._r_join_kw.define(Reg("(?i)\\bJOIN\\b"))
        self._r_inner_kw.define(Reg("(?i)\\bINNER\\b"))
        self._r_left_kw.define(Reg("(?i)\\bLEFT\\b"))
        self._r_right_kw.define(Reg("(?i)\\bRIGHT\\b"))
        self._r_cross_kw.define(Reg("(?i)\\bCROSS\\b"))
        self._r_natural_kw.define(Reg("(?i)\\bNATURAL\\b"))
        self._r_outer_kw.define(Reg("(?i)\\bOUTER\\b"))
        self._r_on_kw.define(Reg("(?i)\\bON\\b"))
        self._r_using_kw.define(Reg("(?i)\\bUSING\\b"))
        self._r_with_kw.define(Reg("(?i)\\bWITH\\b"))
        self._r_recursive_kw.define(Reg("(?i)\\bRECURSIVE\\b"))
        self._r_as_kw.define(Reg("(?i)\\bAS\\b"))
        self._r_indexed_kw.define(Reg("(?i)\\bINDEXED\\b"))
        self._r_not_kw.define(Reg("(?i)\\bNOT\\b"))
        self._r_values_kw.define(Reg("(?i)\\bVALUES\\b"))
        self._r_distinct_kw.define(Reg("(?i)\\bDISTINCT\\b"))
        self._r_all_kw.define(Reg("(?i)\\bALL\\b"))
        self._r_collate_kw.define(Reg("(?i)\\bCOLLATE\\b"))
        self._r_asc_kw.define(Reg("(?i)\\bASC\\b"))
        self._r_desc_kw.define(Reg("(?i)\\bDESC\\b"))
        self._r_nulls_kw.define(Reg("(?i)\\bNULLS\\b"))
        self._r_first_kw.define(Reg("(?i)\\bFIRST\\b"))
        self._r_last_kw.define(Reg("(?i)\\bLAST\\b"))
        self._r_true_kw.define(Reg("(?i)\\bTRUE\\b"))
        self._r_false_kw.define(Reg("(?i)\\bFALSE\\b"))
        self._r_null_kw.define(Reg("(?i)\\bNULL\\b"))
        self._r_ws.define(Reg("[ \\t\\r\\n]+|#[^\\r\\n]*|--[^\\r\\n]*"))
        self._r_opt_ws.define(Reg("[ \\t\\r\\n]*|#[^\\r\\n]*|--[^\\r\\n]*"))

        self.root_parser: Parser[Any] = self._r_root

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_root_0(val: Any) -> Any:
        dql = val[1]
        return dql

    @staticmethod
    def _action_full_dql_1(val: Any) -> Any:
        c = val[0]
        return c

    @staticmethod
    def _action_full_dql_2(val: Any) -> Any:
        ctes = val[0]
        q = val[1]
        if ctes:
            q.ctes = ctes
        return q

    @staticmethod
    def _action_cte_clause_3(val: Any) -> Any:
        is_rec = val[1]
        defs = val[3]
        rec_flag = bool(is_rec)
        res: List[CTEDefinition] = []
        for c in defs:
            res.append(
                CTEDefinition(
                    name=c.name,
                    columns=c.columns,
                    statement=c.statement,
                    is_recursive=rec_flag,
                )
            )
        return res

    @staticmethod
    def _action_cte_def_list_4(val: Any) -> Any:
        next_c = val[3]
        return next_c

    @staticmethod
    def _action_cte_def_list_5(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_cte_def_6(val: Any) -> Any:
        cl = val[3]
        return cl

    @staticmethod
    def _action_cte_def_7(val: Any) -> Any:
        name = val[0]
        cols = val[1]
        stmt = val[7]
        return CTEDefinition(
            name=name,
            columns=cols or [],
            statement=stmt,
            is_recursive=False,
        )

    @staticmethod
    def _action_ident_list_8(val: Any) -> Any:
        next_id = val[3]
        return next_id

    @staticmethod
    def _action_ident_list_9(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_compound_query_10(val: Any) -> Any:
        op = val[1]
        next_q = val[3]
        return (op, next_q)

    @staticmethod
    def _action_compound_query_11(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return _apply_compounds(first, rest)

    @staticmethod
    def _action_union_all_kw_12(val: Any) -> Any:
        return "UNION ALL"

    @staticmethod
    def _action_union_kw_13(val: Any) -> Any:
        return "UNION"

    @staticmethod
    def _action_intersect_kw_14(val: Any) -> Any:
        return "INTERSECT"

    @staticmethod
    def _action_except_kw_15(val: Any) -> Any:
        return "EXCEPT"

    @staticmethod
    def _action_values_statement_16(val: Any) -> Any:
        o = val[1]
        return o

    @staticmethod
    def _action_values_statement_17(val: Any) -> Any:
        lim = val[1]
        return lim

    @staticmethod
    def _action_values_statement_18(val: Any) -> Any:
        rows = val[2]
        order = val[3]
        limit = val[4]
        return _assemble_values_statement(rows, order, limit)

    @staticmethod
    def _action_value_row_list_19(val: Any) -> Any:
        r = val[3]
        return r

    @staticmethod
    def _action_value_row_list_20(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_value_row_21(val: Any) -> Any:
        a = val[3]
        return a

    @staticmethod
    def _action_value_row_22(val: Any) -> Any:
        first = val[2]
        rest = val[3]
        return [first] + rest

    @staticmethod
    def _action_value_atom_23(val: Any) -> Any:
        s = val
        return s[1:-1].replace("''", "'")

    @staticmethod
    def _action_value_atom_24(val: Any) -> Any:
        n = val
        return n

    @staticmethod
    def _action_value_atom_25(val: Any) -> Any:
        return True

    @staticmethod
    def _action_value_atom_26(val: Any) -> Any:
        return False

    @staticmethod
    def _action_value_atom_27(val: Any) -> Any:
        return None

    @staticmethod
    def _action_single_select_28(val: Any) -> Any:
        d = val[1]
        return d

    @staticmethod
    def _action_single_select_29(val: Any) -> Any:
        f = val[1]
        return f

    @staticmethod
    def _action_single_select_30(val: Any) -> Any:
        w = val[1]
        return w

    @staticmethod
    def _action_single_select_31(val: Any) -> Any:
        g = val[1]
        return g

    @staticmethod
    def _action_single_select_32(val: Any) -> Any:
        h = val[1]
        return h

    @staticmethod
    def _action_single_select_33(val: Any) -> Any:
        o = val[1]
        return o

    @staticmethod
    def _action_single_select_34(val: Any) -> Any:
        lim = val[1]
        return lim

    @staticmethod
    def _action_single_select_35(val: Any) -> Any:
        dist = val[1]
        projs = val[3]
        from_part = val[4]
        where_part = val[5]
        group_part = val[6]
        having_part = val[7]
        order_part = val[8]
        limit_part = val[9]
        return _assemble_single_select(
            dist,
            projs,
            from_part,
            where_part,
            group_part,
            having_part,
            order_part,
            limit_part,
        )

    @staticmethod
    def _action_distinct_modifier_36(val: Any) -> Any:
        return True

    @staticmethod
    def _action_distinct_modifier_37(val: Any) -> Any:
        return False

    @staticmethod
    def _action_projection_list_38(val: Any) -> Any:
        next_p = val[3]
        return next_p

    @staticmethod
    def _action_projection_list_39(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_star_40(val: Any) -> Any:
        return "*"

    @staticmethod
    def _action_table_star_41(val: Any) -> Any:
        id = val[0]
        return f"{id}.*"

    @staticmethod
    def _action_proj_expr_42(val: Any) -> Any:
        parts = val
        return " ".join(parts).strip()

    @staticmethod
    def _action_proj_chunk_43(val: Any) -> Any:
        raw = val[1]
        return raw

    @staticmethod
    def _action_from_clause_44(val: Any) -> Any:
        j = val[1]
        return j

    @staticmethod
    def _action_from_clause_45(val: Any) -> Any:
        primary_table = val[2]
        joins = val[3]
        return (primary_table, joins)

    @staticmethod
    def _action_subquery_table_ref_46(val: Any) -> Any:
        a = val[1]
        return a

    @staticmethod
    def _action_subquery_table_ref_47(val: Any) -> Any:
        sub = val[2]
        al = val[5]
        alias_str = al if al else None
        return TableRef(
            name=alias_str or "",
            alias=alias_str,
            subquery=sub,
        )

    @staticmethod
    def _action_tvf_table_ref_48(val: Any) -> Any:
        a = val[1]
        return a

    @staticmethod
    def _action_tvf_table_ref_49(val: Any) -> Any:
        id = val[0]
        raw_args = val[3]
        al = val[5]
        parsed_args = _split_tvf_args(raw_args)
        return TableRef(
            name=id,
            alias=al,
            function_name=id,
            function_args=parsed_args,
        )

    @staticmethod
    def _action_tvf_args_content_50(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_plain_table_ref_51(val: Any) -> Any:
        a = val[1]
        return a

    @staticmethod
    def _action_plain_table_ref_52(val: Any) -> Any:
        h = val[1]
        return h

    @staticmethod
    def _action_plain_table_ref_53(val: Any) -> Any:
        id = val[0]
        al = val[1]
        hint = val[2]
        idx_by = hint[1] if (hint and hint[0] == "INDEXED") else None
        not_idx = bool(hint and hint[0] == "NOT_INDEXED")
        return TableRef(
            name=id,
            alias=al,
            indexed_by=idx_by,
            not_indexed=not_idx,
        )

    @staticmethod
    def _action_plain_table_ref_54(val: Any) -> Any:
        h = val[1]
        return h

    @staticmethod
    def _action_plain_table_ref_55(val: Any) -> Any:
        a = val[1]
        return a

    @staticmethod
    def _action_plain_table_ref_56(val: Any) -> Any:
        id = val[0]
        hint = val[1]
        al = val[2]
        idx_by = hint[1] if (hint and hint[0] == "INDEXED") else None
        not_idx = bool(hint and hint[0] == "NOT_INDEXED")
        return TableRef(
            name=id,
            alias=al,
            indexed_by=idx_by,
            not_indexed=not_idx,
        )

    @staticmethod
    def _action_index_hint_57(val: Any) -> Any:
        id = val[4]
        return ("INDEXED", id)

    @staticmethod
    def _action_index_hint_58(val: Any) -> Any:
        return ("NOT_INDEXED", None)

    @staticmethod
    def _action_alias_clause_59(val: Any) -> Any:
        id = val[2]
        return id

    @staticmethod
    def _action_alias_clause_60(val: Any) -> Any:
        id = val
        return id

    @staticmethod
    def _action_comma_join_61(val: Any) -> Any:
        tbl = val[2]
        return JoinClause(
            join_type=JoinType.CROSS,
            table=tbl,
            on_conditions=[],
        )

    @staticmethod
    def _action_explicit_join_62(val: Any) -> Any:
        c = val[1]
        return c

    @staticmethod
    def _action_explicit_join_63(val: Any) -> Any:
        jt = val[1]
        tbl = val[4]
        cond = val[5]
        jtype = jt if jt else JoinType.INNER
        return JoinClause(
            join_type=jtype,
            table=tbl,
            on_conditions=cond or [],
        )

    @staticmethod
    def _action_join_type_spec_64(val: Any) -> Any:
        return JoinType.INNER

    @staticmethod
    def _action_join_type_spec_65(val: Any) -> Any:
        return JoinType.LEFT

    @staticmethod
    def _action_join_type_spec_66(val: Any) -> Any:
        return JoinType.RIGHT

    @staticmethod
    def _action_join_type_spec_67(val: Any) -> Any:
        return JoinType.CROSS

    @staticmethod
    def _action_join_condition_68(val: Any) -> Any:
        cond_str = val[2]
        return _parse_where_condition_terms(cond_str)

    @staticmethod
    def _action_join_condition_69(val: Any) -> Any:
        cols = val[4]
        return [{"column": c, "operator": "=", "value": c} for c in cols]

    @staticmethod
    def _action_on_condition_expr_70(val: Any) -> Any:
        parts = val
        return " ".join(parts).strip()

    @staticmethod
    def _action_on_chunk_71(val: Any) -> Any:
        raw = val[1]
        return raw

    @staticmethod
    def _action_where_clause_72(val: Any) -> Any:
        body = val[2]
        return body

    @staticmethod
    def _action_where_body_expr_73(val: Any) -> Any:
        parts = val
        return " ".join(parts).strip()

    @staticmethod
    def _action_where_chunk_74(val: Any) -> Any:
        raw = val[1]
        return raw

    @staticmethod
    def _action_group_by_clause_75(val: Any) -> Any:
        cols = val[4]
        return cols

    @staticmethod
    def _action_ident_or_expr_list_76(val: Any) -> Any:
        next_i = val[3]
        return next_i

    @staticmethod
    def _action_ident_or_expr_list_77(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_group_item_78(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_having_clause_79(val: Any) -> Any:
        cond = val[2]
        return cond

    @staticmethod
    def _action_having_body_expr_80(val: Any) -> Any:
        parts = val
        return " ".join(parts).strip()

    @staticmethod
    def _action_having_chunk_81(val: Any) -> Any:
        raw = val[1]
        return raw

    @staticmethod
    def _action_order_by_clause_82(val: Any) -> Any:
        items = val[4]
        return items[0]

    @staticmethod
    def _action_order_item_list_83(val: Any) -> Any:
        next_o = val[3]
        return next_o

    @staticmethod
    def _action_order_item_list_84(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_order_item_85(val: Any) -> Any:
        c = val[3]
        return c.upper()

    @staticmethod
    def _action_order_item_86(val: Any) -> Any:
        d = val[1]
        return d

    @staticmethod
    def _action_order_item_87(val: Any) -> Any:
        col = val[0]
        coll = val[1]
        dir = val[2]
        is_desc = (dir == "DESC") if dir else False
        return (col, is_desc, coll)

    @staticmethod
    def _action_order_col_88(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_order_dir_89(val: Any) -> Any:
        return "ASC"

    @staticmethod
    def _action_order_dir_90(val: Any) -> Any:
        return "DESC"

    @staticmethod
    def _action_limit_offset_clause_91(val: Any) -> Any:
        lim = val[2]
        off = val[6]
        return (lim, off)

    @staticmethod
    def _action_limit_offset_clause_92(val: Any) -> Any:
        off = val[2]
        lim = val[6]
        return (lim, off)

    @staticmethod
    def _action_limit_offset_clause_93(val: Any) -> Any:
        lim = val[2]
        return (lim, None)

    @staticmethod
    def _action_integer_num_94(val: Any) -> Any:
        raw = val
        return int(raw)

    @staticmethod
    def _action_func_call_token_95(val: Any) -> Any:
        fn = val[1]
        args = val[2]
        return f"{fn}{args}"

    @staticmethod
    def _action_paren_token_96(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_bracket_token_97(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_non_ws_token_98(val: Any) -> Any:
        raw = val[1]
        return raw

    @staticmethod
    def _action_ident_99(val: Any) -> Any:
        plain = val
        return plain

    @staticmethod
    def _action_ident_100(val: Any) -> Any:
        backtick = val
        return backtick

    @staticmethod
    def _action_ident_101(val: Any) -> Any:
        double_quote = val
        return double_quote

    @staticmethod
    def _action_ident_pattern_102(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_backtick_pattern_103(val: Any) -> Any:
        raw = val
        return raw[1:-1]

    @staticmethod
    def _action_double_quote_pattern_104(val: Any) -> Any:
        raw = val
        return raw[1:-1]

    @staticmethod
    def _action_non_reserved_ident_105(val: Any) -> Any:
        id = val[1]
        return id

    @staticmethod
    def _action_string_literal_106(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_double_quote_literal_107(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_number_literal_108(val: Any) -> Any:
        raw = val
        if "." in raw or "e" in raw or "E" in raw:
            return float(raw)
        return int(raw)
