#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: SQLAdmin
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

from typing import Any

from core.structures.peg import (
    Choice,
    Lit,
    NotPred,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
)

# User header code

try:
    from .ast import (
        AnalyzeStatement,
        AttachStatement,
        BeginStatement,
        CommitStatement,
        DetachStatement,
        ExplainStatement,
        GrantStatement,
        PragmaStatement,
        RevokeStatement,
        RollbackStatement,
        SavepointStatement,
        ShowStatement,
        SQLCommandType,
        SQLStatement,
        VacuumStatement,
    )
except (ImportError, ValueError):
    from database.sql.ast import (
        AnalyzeStatement,
        AttachStatement,
        BeginStatement,
        CommitStatement,
        DetachStatement,
        ExplainStatement,
        GrantStatement,
        PragmaStatement,
        RevokeStatement,
        RollbackStatement,
        SavepointStatement,
        ShowStatement,
        SQLCommandType,
        SQLStatement,
        VacuumStatement,
    )


def _parse_explain_stmt(raw_stmt: str) -> SQLStatement:
    from database.sql.parser import SQLParser

    return SQLParser().parse(raw_stmt.strip())


class SQLAdminParser(Parser[Any]):
    """Packrat PEG Parser for SQLAdmin grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_root = RuleRef("root")
        self._r_admin_stmt = RuleRef("admin_stmt")
        self._r_begin_stmt = RuleRef("begin_stmt")
        self._r_isolation_mode = RuleRef("isolation_mode")
        self._r_commit_stmt = RuleRef("commit_stmt")
        self._r_rollback_stmt = RuleRef("rollback_stmt")
        self._r_rollback_to_stmt = RuleRef("rollback_to_stmt")
        self._r_rollback_plain_stmt = RuleRef("rollback_plain_stmt")
        self._r_savepoint_stmt = RuleRef("savepoint_stmt")
        self._r_release_stmt = RuleRef("release_stmt")
        self._r_grant_stmt = RuleRef("grant_stmt")
        self._r_revoke_stmt = RuleRef("revoke_stmt")
        self._r_permission_spec = RuleRef("permission_spec")
        self._r_table_or_star = RuleRef("table_or_star")
        self._r_pragma_stmt = RuleRef("pragma_stmt")
        self._r_pragma_name_spec = RuleRef("pragma_name_spec")
        self._r_pragma_arg_spec = RuleRef("pragma_arg_spec")
        self._r_pragma_call_spec = RuleRef("pragma_call_spec")
        self._r_pragma_eq_spec = RuleRef("pragma_eq_spec")
        self._r_pragma_val_token = RuleRef("pragma_val_token")
        self._r_vacuum_stmt = RuleRef("vacuum_stmt")
        self._r_analyze_stmt = RuleRef("analyze_stmt")
        self._r_analyze_target = RuleRef("analyze_target")
        self._r_attach_stmt = RuleRef("attach_stmt")
        self._r_attach_fn = RuleRef("attach_fn")
        self._r_detach_stmt = RuleRef("detach_stmt")
        self._r_explain_stmt = RuleRef("explain_stmt")
        self._r_rest_of_query = RuleRef("rest_of_query")
        self._r_show_stmt = RuleRef("show_stmt")
        self._r_show_target = RuleRef("show_target")
        self._r_ident = RuleRef("ident")
        self._r_ident_pattern = RuleRef("ident_pattern")
        self._r_backtick_pattern = RuleRef("backtick_pattern")
        self._r_double_quote_pattern = RuleRef("double_quote_pattern")
        self._r_bracket_pattern = RuleRef("bracket_pattern")
        self._r_str_literal = RuleRef("str_literal")
        self._r_begin_kw = RuleRef("begin_kw")
        self._r_commit_kw = RuleRef("commit_kw")
        self._r_rollback_kw = RuleRef("rollback_kw")
        self._r_savepoint_kw = RuleRef("savepoint_kw")
        self._r_release_kw = RuleRef("release_kw")
        self._r_grant_kw = RuleRef("grant_kw")
        self._r_revoke_kw = RuleRef("revoke_kw")
        self._r_pragma_kw = RuleRef("pragma_kw")
        self._r_vacuum_kw = RuleRef("vacuum_kw")
        self._r_analyze_kw = RuleRef("analyze_kw")
        self._r_attach_kw = RuleRef("attach_kw")
        self._r_detach_kw = RuleRef("detach_kw")
        self._r_explain_kw = RuleRef("explain_kw")
        self._r_show_kw = RuleRef("show_kw")
        self._r_deferred_kw = RuleRef("deferred_kw")
        self._r_immediate_kw = RuleRef("immediate_kw")
        self._r_exclusive_kw = RuleRef("exclusive_kw")
        self._r_transaction_kw = RuleRef("transaction_kw")
        self._r_to_kw = RuleRef("to_kw")
        self._r_from_kw = RuleRef("from_kw")
        self._r_all_kw = RuleRef("all_kw")
        self._r_privileges_kw = RuleRef("privileges_kw")
        self._r_on_kw = RuleRef("on_kw")
        self._r_into_kw = RuleRef("into_kw")
        self._r_database_kw = RuleRef("database_kw")
        self._r_as_kw = RuleRef("as_kw")
        self._r_query_kw = RuleRef("query_kw")
        self._r_plan_kw = RuleRef("plan_kw")
        self._r_databases_kw = RuleRef("databases_kw")
        self._r_schemas_kw = RuleRef("schemas_kw")
        self._r_tables_kw = RuleRef("tables_kw")
        self._r_table_kw = RuleRef("table_kw")
        self._r_status_kw = RuleRef("status_kw")
        self._r_columns_kw = RuleRef("columns_kw")
        self._r_indexes_kw = RuleRef("indexes_kw")
        self._r_like_kw = RuleRef("like_kw")
        self._r_ws = RuleRef("ws")
        self._r_opt_ws = RuleRef("opt_ws")

        self._r_root.define(
            Seq(self._r_opt_ws, self._r_admin_stmt, self._r_opt_ws).map(
                self._action_root_0
            )
        )
        self._r_admin_stmt.define(
            Choice(
                self._r_begin_stmt,
                self._r_commit_stmt,
                self._r_rollback_stmt,
                self._r_savepoint_stmt,
                self._r_release_stmt,
                self._r_grant_stmt,
                self._r_revoke_stmt,
                self._r_pragma_stmt,
                self._r_vacuum_stmt,
                self._r_analyze_stmt,
                self._r_attach_stmt,
                self._r_detach_stmt,
                self._r_explain_stmt,
                self._r_show_stmt,
            )
        )
        self._r_begin_stmt.define(
            Seq(
                self._r_begin_kw,
                Opt(Seq(self._r_ws, self._r_isolation_mode)),
                Opt(Seq(self._r_ws, self._r_transaction_kw)),
            ).map(self._action_begin_stmt_1)
        )
        self._r_isolation_mode.define(
            Choice(self._r_deferred_kw, self._r_immediate_kw, self._r_exclusive_kw)
        )
        self._r_commit_stmt.define(
            Seq(self._r_commit_kw, Opt(Seq(self._r_ws, self._r_transaction_kw))).map(
                self._action_commit_stmt_2
            )
        )
        self._r_rollback_stmt.define(
            Choice(self._r_rollback_to_stmt, self._r_rollback_plain_stmt)
        )
        self._r_rollback_to_stmt.define(
            Seq(
                self._r_rollback_kw,
                Opt(Seq(self._r_ws, self._r_transaction_kw)),
                self._r_ws,
                self._r_to_kw,
                Opt(Seq(self._r_ws, self._r_savepoint_kw)),
                self._r_ws,
                self._r_ident,
            ).map(self._action_rollback_to_stmt_3)
        )
        self._r_rollback_plain_stmt.define(
            Seq(self._r_rollback_kw, Opt(Seq(self._r_ws, self._r_transaction_kw))).map(
                self._action_rollback_plain_stmt_4
            )
        )
        self._r_savepoint_stmt.define(
            Seq(self._r_savepoint_kw, self._r_ws, self._r_ident).map(
                self._action_savepoint_stmt_5
            )
        )
        self._r_release_stmt.define(
            Seq(
                self._r_release_kw,
                Opt(Seq(self._r_ws, self._r_savepoint_kw)),
                self._r_ws,
                self._r_ident,
            ).map(self._action_release_stmt_6)
        )
        self._r_grant_stmt.define(
            Seq(
                self._r_grant_kw,
                self._r_ws,
                self._r_permission_spec,
                Opt(
                    Seq(
                        self._r_ws, self._r_on_kw, self._r_ws, self._r_table_or_star
                    ).map(self._action_grant_stmt_7)
                ),
                self._r_ws,
                self._r_to_kw,
                self._r_ws,
                self._r_ident,
            ).map(self._action_grant_stmt_8)
        )
        self._r_revoke_stmt.define(
            Seq(
                self._r_revoke_kw,
                self._r_ws,
                self._r_permission_spec,
                Opt(
                    Seq(
                        self._r_ws, self._r_on_kw, self._r_ws, self._r_table_or_star
                    ).map(self._action_revoke_stmt_9)
                ),
                self._r_ws,
                self._r_from_kw,
                self._r_ws,
                self._r_ident,
            ).map(self._action_revoke_stmt_10)
        )
        self._r_permission_spec.define(
            Choice(
                Seq(self._r_all_kw, Opt(Seq(self._r_ws, self._r_privileges_kw))).map(
                    self._action_permission_spec_11
                ),
                self._r_ident.map(self._action_permission_spec_12),
            )
        )
        self._r_table_or_star.define(
            Choice(
                Lit("*").map(self._action_table_or_star_13),
                self._r_ident.map(self._action_table_or_star_14),
            )
        )
        self._r_pragma_stmt.define(
            Seq(
                self._r_pragma_kw,
                self._r_ws,
                self._r_pragma_name_spec,
                Opt(
                    Seq(self._r_opt_ws, self._r_pragma_arg_spec).map(
                        self._action_pragma_stmt_15
                    )
                ),
            ).map(self._action_pragma_stmt_16)
        )
        self._r_pragma_name_spec.define(
            Choice(
                Seq(
                    self._r_ident,
                    self._r_opt_ws,
                    Lit("."),
                    self._r_opt_ws,
                    self._r_ident,
                ).map(self._action_pragma_name_spec_17),
                self._r_ident.map(self._action_pragma_name_spec_18),
            )
        )
        self._r_pragma_arg_spec.define(
            Choice(self._r_pragma_call_spec, self._r_pragma_eq_spec)
        )
        self._r_pragma_call_spec.define(
            Seq(
                Lit("("),
                self._r_opt_ws,
                self._r_pragma_val_token,
                self._r_opt_ws,
                Lit(")"),
            ).map(self._action_pragma_call_spec_19)
        )
        self._r_pragma_eq_spec.define(
            Seq(Lit("="), self._r_opt_ws, self._r_pragma_val_token).map(
                self._action_pragma_eq_spec_20
            )
        )
        self._r_pragma_val_token.define(
            Choice(
                self._r_str_literal,
                Reg("[a-zA-Z0-9_\\-]+").map(self._action_pragma_val_token_21),
            )
        )
        self._r_vacuum_stmt.define(
            Seq(
                self._r_vacuum_kw,
                Opt(
                    Seq(self._r_ws, NotPred(self._r_into_kw), self._r_ident).map(
                        self._action_vacuum_stmt_22
                    )
                ),
                Opt(
                    Seq(
                        self._r_ws, self._r_into_kw, self._r_ws, self._r_str_literal
                    ).map(self._action_vacuum_stmt_23)
                ),
            ).map(self._action_vacuum_stmt_24)
        )
        self._r_analyze_stmt.define(
            Seq(
                self._r_analyze_kw,
                Opt(
                    Seq(self._r_ws, self._r_analyze_target).map(
                        self._action_analyze_stmt_25
                    )
                ),
            ).map(self._action_analyze_stmt_26)
        )
        self._r_analyze_target.define(
            Choice(
                Seq(
                    self._r_ident,
                    self._r_opt_ws,
                    Lit("."),
                    self._r_opt_ws,
                    self._r_ident,
                ).map(self._action_analyze_target_27),
                self._r_ident.map(self._action_analyze_target_28),
            )
        )
        self._r_attach_stmt.define(
            Seq(
                self._r_attach_kw,
                Opt(Seq(self._r_ws, self._r_database_kw)),
                self._r_ws,
                self._r_attach_fn,
                self._r_ws,
                self._r_as_kw,
                self._r_ws,
                self._r_ident,
            ).map(self._action_attach_stmt_29)
        )
        self._r_attach_fn.define(
            Choice(self._r_str_literal, Reg("[^\\s;]+").map(self._action_attach_fn_30))
        )
        self._r_detach_stmt.define(
            Seq(
                self._r_detach_kw,
                Opt(Seq(self._r_ws, self._r_database_kw)),
                self._r_ws,
                self._r_ident,
            ).map(self._action_detach_stmt_31)
        )
        self._r_explain_stmt.define(
            Seq(
                self._r_explain_kw,
                Opt(
                    Seq(self._r_ws, self._r_query_kw, self._r_ws, self._r_plan_kw).map(
                        self._action_explain_stmt_32
                    )
                ),
                self._r_ws,
                self._r_rest_of_query,
            ).map(self._action_explain_stmt_33)
        )
        self._r_rest_of_query.define(
            Reg("[^\\r\\n;]+").map(self._action_rest_of_query_34)
        )
        self._r_show_stmt.define(
            Seq(
                self._r_show_kw,
                self._r_ws,
                self._r_show_target,
                Opt(
                    Seq(self._r_ws, self._r_from_kw, self._r_ws, self._r_ident).map(
                        self._action_show_stmt_35
                    )
                ),
                Opt(
                    Seq(
                        self._r_ws, self._r_like_kw, self._r_ws, self._r_str_literal
                    ).map(self._action_show_stmt_36)
                ),
            ).map(self._action_show_stmt_37)
        )
        self._r_show_target.define(
            Choice(
                self._r_databases_kw.map(self._action_show_target_38),
                self._r_schemas_kw.map(self._action_show_target_39),
                Seq(self._r_table_kw, self._r_ws, self._r_status_kw).map(
                    self._action_show_target_40
                ),
                self._r_tables_kw.map(self._action_show_target_41),
                self._r_columns_kw.map(self._action_show_target_42),
                self._r_indexes_kw.map(self._action_show_target_43),
            )
        )
        self._r_ident.define(
            Choice(
                self._r_ident_pattern.map(self._action_ident_44),
                self._r_backtick_pattern.map(self._action_ident_45),
                self._r_double_quote_pattern.map(self._action_ident_46),
                self._r_bracket_pattern.map(self._action_ident_47),
            )
        )
        self._r_ident_pattern.define(
            Reg("[a-zA-Z_][a-zA-Z0-9_]*").map(self._action_ident_pattern_48)
        )
        self._r_backtick_pattern.define(
            Reg("`[^`]*`").map(self._action_backtick_pattern_49)
        )
        self._r_double_quote_pattern.define(
            Reg('"[^"]*"').map(self._action_double_quote_pattern_50)
        )
        self._r_bracket_pattern.define(
            Reg("\\[[^\\]]*\\]").map(self._action_bracket_pattern_51)
        )
        self._r_str_literal.define(
            Choice(
                Reg("'([^']*)'").map(self._action_str_literal_52),
                Reg('"([^"]*)"').map(self._action_str_literal_53),
            )
        )
        self._r_begin_kw.define(Reg("(?i)\\bBEGIN\\b"))
        self._r_commit_kw.define(Reg("(?i)\\bCOMMIT\\b"))
        self._r_rollback_kw.define(Reg("(?i)\\bROLLBACK\\b"))
        self._r_savepoint_kw.define(Reg("(?i)\\bSAVEPOINT\\b"))
        self._r_release_kw.define(Reg("(?i)\\bRELEASE\\b"))
        self._r_grant_kw.define(Reg("(?i)\\bGRANT\\b"))
        self._r_revoke_kw.define(Reg("(?i)\\bREVOKE\\b"))
        self._r_pragma_kw.define(Reg("(?i)\\bPRAGMA\\b"))
        self._r_vacuum_kw.define(Reg("(?i)\\bVACUUM\\b"))
        self._r_analyze_kw.define(Reg("(?i)\\bANALYZE\\b"))
        self._r_attach_kw.define(Reg("(?i)\\bATTACH\\b"))
        self._r_detach_kw.define(Reg("(?i)\\bDETACH\\b"))
        self._r_explain_kw.define(Reg("(?i)\\bEXPLAIN\\b"))
        self._r_show_kw.define(Reg("(?i)\\bSHOW\\b"))
        self._r_deferred_kw.define(Reg("(?i)\\bDEFERRED\\b"))
        self._r_immediate_kw.define(Reg("(?i)\\bIMMEDIATE\\b"))
        self._r_exclusive_kw.define(Reg("(?i)\\bEXCLUSIVE\\b"))
        self._r_transaction_kw.define(Reg("(?i)\\bTRANSACTION\\b"))
        self._r_to_kw.define(Reg("(?i)\\bTO\\b"))
        self._r_from_kw.define(Reg("(?i)\\bFROM\\b"))
        self._r_all_kw.define(Reg("(?i)\\bALL\\b"))
        self._r_privileges_kw.define(Reg("(?i)\\bPRIVILEGES\\b"))
        self._r_on_kw.define(Reg("(?i)\\bON\\b"))
        self._r_into_kw.define(Reg("(?i)\\bINTO\\b"))
        self._r_database_kw.define(Reg("(?i)\\bDATABASE\\b"))
        self._r_as_kw.define(Reg("(?i)\\bAS\\b"))
        self._r_query_kw.define(Reg("(?i)\\bQUERY\\b"))
        self._r_plan_kw.define(Reg("(?i)\\bPLAN\\b"))
        self._r_databases_kw.define(Reg("(?i)\\bDATABASES\\b"))
        self._r_schemas_kw.define(Reg("(?i)\\bSCHEMAS\\b"))
        self._r_tables_kw.define(Reg("(?i)\\bTABLES\\b"))
        self._r_table_kw.define(Reg("(?i)\\bTABLE\\b"))
        self._r_status_kw.define(Reg("(?i)\\bSTATUS\\b"))
        self._r_columns_kw.define(Reg("(?i)\\bCOLUMNS\\b"))
        self._r_indexes_kw.define(Reg("(?i)\\bINDEXES\\b"))
        self._r_like_kw.define(Reg("(?i)\\bLIKE\\b"))
        self._r_ws.define(Reg("[ \\t\\r\\n]+|#[^\\r\\n]*|--[^\\r\\n]*"))
        self._r_opt_ws.define(Reg("[ \\t\\r\\n]*|#[^\\r\\n]*|--[^\\r\\n]*"))

        self.root_parser: Parser[Any] = self._r_root

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_root_0(val: Any) -> Any:
        admin = val[1]
        return admin

    @staticmethod
    def _action_begin_stmt_1(val: Any) -> Any:
        return BeginStatement(command_type=SQLCommandType.BEGIN, raw_sql="")

    @staticmethod
    def _action_commit_stmt_2(val: Any) -> Any:
        return CommitStatement(command_type=SQLCommandType.COMMIT, raw_sql="")

    @staticmethod
    def _action_rollback_to_stmt_3(val: Any) -> Any:
        name = val[6]
        return SavepointStatement(
            command_type=SQLCommandType.ROLLBACK_TO,
            raw_sql="",
            name=str(name),
            action="ROLLBACK_TO",
        )

    @staticmethod
    def _action_rollback_plain_stmt_4(val: Any) -> Any:
        return RollbackStatement(command_type=SQLCommandType.ROLLBACK, raw_sql="")

    @staticmethod
    def _action_savepoint_stmt_5(val: Any) -> Any:
        name = val[2]
        return SavepointStatement(
            command_type=SQLCommandType.SAVEPOINT,
            raw_sql="",
            name=str(name),
            action="SAVEPOINT",
        )

    @staticmethod
    def _action_release_stmt_6(val: Any) -> Any:
        name = val[3]
        return SavepointStatement(
            command_type=SQLCommandType.RELEASE,
            raw_sql="",
            name=str(name),
            action="RELEASE",
        )

    @staticmethod
    def _action_grant_stmt_7(val: Any) -> Any:
        t = val[3]
        return t

    @staticmethod
    def _action_grant_stmt_8(val: Any) -> Any:
        perm = val[2]
        on_clause = val[3]
        role = val[7]
        tbl = on_clause if on_clause is not None else "*"
        return GrantStatement(
            command_type=SQLCommandType.GRANT,
            raw_sql="",
            permission=str(perm).upper(),
            table_name=str(tbl),
            role=str(role),
        )

    @staticmethod
    def _action_revoke_stmt_9(val: Any) -> Any:
        t = val[3]
        return t

    @staticmethod
    def _action_revoke_stmt_10(val: Any) -> Any:
        perm = val[2]
        on_clause = val[3]
        role = val[7]
        tbl = on_clause if on_clause is not None else "*"
        return RevokeStatement(
            command_type=SQLCommandType.REVOKE,
            raw_sql="",
            permission=str(perm).upper(),
            table_name=str(tbl),
            role=str(role),
        )

    @staticmethod
    def _action_permission_spec_11(val: Any) -> Any:
        return "ALL"

    @staticmethod
    def _action_permission_spec_12(val: Any) -> Any:
        id = val
        return id

    @staticmethod
    def _action_table_or_star_13(val: Any) -> Any:
        return "*"

    @staticmethod
    def _action_table_or_star_14(val: Any) -> Any:
        id = val
        return id

    @staticmethod
    def _action_pragma_stmt_15(val: Any) -> Any:
        a = val[1]
        return a

    @staticmethod
    def _action_pragma_stmt_16(val: Any) -> Any:
        name = val[2]
        arg = val[3]
        mode, val = arg if arg else (None, None)
        return PragmaStatement(
            command_type=SQLCommandType.PRAGMA,
            raw_sql="",
            pragma_name=str(name).lower(),
            argument=val if mode == "call" else None,
            value=val if mode == "eq" else None,
        )

    @staticmethod
    def _action_pragma_name_spec_17(val: Any) -> Any:
        s = val[0]
        t = val[4]
        return f"{s}.{t}"

    @staticmethod
    def _action_pragma_name_spec_18(val: Any) -> Any:
        id = val
        return id

    @staticmethod
    def _action_pragma_call_spec_19(val: Any) -> Any:
        val = val[2]
        return ("call", str(val).strip("'\""))

    @staticmethod
    def _action_pragma_eq_spec_20(val: Any) -> Any:
        val = val[2]
        return ("eq", str(val).strip("'\""))

    @staticmethod
    def _action_pragma_val_token_21(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_vacuum_stmt_22(val: Any) -> Any:
        t = val[2]
        return t

    @staticmethod
    def _action_vacuum_stmt_23(val: Any) -> Any:
        f = val[3]
        return f

    @staticmethod
    def _action_vacuum_stmt_24(val: Any) -> Any:
        tgt = val[1]
        into = val[2]
        return VacuumStatement(
            command_type=SQLCommandType.VACUUM,
            raw_sql="",
            target_table=tgt if tgt is not None else None,
            into_file=into if into is not None else None,
        )

    @staticmethod
    def _action_analyze_stmt_25(val: Any) -> Any:
        t = val[1]
        return t

    @staticmethod
    def _action_analyze_stmt_26(val: Any) -> Any:
        tgt = val[1]
        schema, target = tgt if tgt else (None, None)
        return AnalyzeStatement(
            command_type=SQLCommandType.ANALYZE,
            raw_sql="",
            schema_name=schema,
            target_name=target,
        )

    @staticmethod
    def _action_analyze_target_27(val: Any) -> Any:
        s = val[0]
        t = val[4]
        return (str(s), str(t))

    @staticmethod
    def _action_analyze_target_28(val: Any) -> Any:
        t = val
        return (None, str(t))

    @staticmethod
    def _action_attach_stmt_29(val: Any) -> Any:
        fn = val[3]
        schema = val[7]
        return AttachStatement(
            command_type=SQLCommandType.ATTACH,
            raw_sql="",
            filename=str(fn),
            schema_name=str(schema),
        )

    @staticmethod
    def _action_attach_fn_30(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_detach_stmt_31(val: Any) -> Any:
        schema = val[3]
        return DetachStatement(
            command_type=SQLCommandType.DETACH,
            raw_sql="",
            schema_name=str(schema),
        )

    @staticmethod
    def _action_explain_stmt_32(val: Any) -> Any:
        return True

    @staticmethod
    def _action_explain_stmt_33(val: Any) -> Any:
        qp = val[1]
        stmt = val[3]
        return ExplainStatement(
            command_type=SQLCommandType.EXPLAIN,
            raw_sql="",
            statement=_parse_explain_stmt(stmt),
            query_plan=bool(qp),
        )

    @staticmethod
    def _action_rest_of_query_34(val: Any) -> Any:
        raw = val
        return raw.strip()

    @staticmethod
    def _action_show_stmt_35(val: Any) -> Any:
        d = val[3]
        return d

    @staticmethod
    def _action_show_stmt_36(val: Any) -> Any:
        p = val[3]
        return p

    @staticmethod
    def _action_show_stmt_37(val: Any) -> Any:
        tgt = val[2]
        from_clause = val[3]
        like_clause = val[4]
        return ShowStatement(
            command_type=SQLCommandType.SHOW,
            raw_sql="",
            target=tgt,
            from_database=str(from_clause) if from_clause else None,
            like_pattern=str(like_clause) if like_clause else None,
        )

    @staticmethod
    def _action_show_target_38(val: Any) -> Any:
        return "DATABASES"

    @staticmethod
    def _action_show_target_39(val: Any) -> Any:
        return "DATABASES"

    @staticmethod
    def _action_show_target_40(val: Any) -> Any:
        return "TABLE_STATUS"

    @staticmethod
    def _action_show_target_41(val: Any) -> Any:
        return "TABLES"

    @staticmethod
    def _action_show_target_42(val: Any) -> Any:
        return "COLUMNS"

    @staticmethod
    def _action_show_target_43(val: Any) -> Any:
        return "INDEXES"

    @staticmethod
    def _action_ident_44(val: Any) -> Any:
        plain = val
        return plain

    @staticmethod
    def _action_ident_45(val: Any) -> Any:
        backtick = val
        return backtick

    @staticmethod
    def _action_ident_46(val: Any) -> Any:
        double_quote = val
        return double_quote

    @staticmethod
    def _action_ident_47(val: Any) -> Any:
        bracket = val
        return bracket

    @staticmethod
    def _action_ident_pattern_48(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_backtick_pattern_49(val: Any) -> Any:
        raw = val
        return raw[1:-1]

    @staticmethod
    def _action_double_quote_pattern_50(val: Any) -> Any:
        raw = val
        return raw[1:-1]

    @staticmethod
    def _action_bracket_pattern_51(val: Any) -> Any:
        raw = val
        return raw[1:-1]

    @staticmethod
    def _action_str_literal_52(val: Any) -> Any:
        s = val
        return s[1:-1]

    @staticmethod
    def _action_str_literal_53(val: Any) -> Any:
        s = val
        return s[1:-1]
