#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: SQLExpr
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

from typing import Any

from core.structures.peg import (
    Choice,
    Lit,
    OneOrMore,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
    ZeroOrMore,
)
from database.sql.expr_parser import (
    BinaryOpExpr,
    CaseExpr,
    CollateExpr,
    ColumnRefExpr,
    ExistsExpr,
    FunctionCallExpr,
    LiteralExpr,
    UnaryOpExpr,
    _dispatch_pred,
)

# User header code


class SQLExprParser(Parser[Any]):
    """Packrat PEG Parser for SQLExpr grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_root = RuleRef("root")
        self._r_or_expr = RuleRef("or_expr")
        self._r_or_kw = RuleRef("or_kw")
        self._r_and_expr = RuleRef("and_expr")
        self._r_and_kw = RuleRef("and_kw")
        self._r_pred_expr = RuleRef("pred_expr")
        self._r_collate_kw = RuleRef("collate_kw")
        self._r_pred_suffix = RuleRef("pred_suffix")
        self._r_is_null_suffix = RuleRef("is_null_suffix")
        self._r_is_kw = RuleRef("is_kw")
        self._r_null_kw = RuleRef("null_kw")
        self._r_between_suffix = RuleRef("between_suffix")
        self._r_between_kw = RuleRef("between_kw")
        self._r_like_suffix = RuleRef("like_suffix")
        self._r_like_op = RuleRef("like_op")
        self._r_escape_kw = RuleRef("escape_kw")
        self._r_in_suffix = RuleRef("in_suffix")
        self._r_in_kw = RuleRef("in_kw")
        self._r_in_body = RuleRef("in_body")
        self._r_in_subquery = RuleRef("in_subquery")
        self._r_subquery_text = RuleRef("subquery_text")
        self._r_in_val_list = RuleRef("in_val_list")
        self._r_cmp_suffix = RuleRef("cmp_suffix")
        self._r_cmp_op = RuleRef("cmp_op")
        self._r_add_expr = RuleRef("add_expr")
        self._r_add_op = RuleRef("add_op")
        self._r_mult_expr = RuleRef("mult_expr")
        self._r_mult_op = RuleRef("mult_op")
        self._r_unary_expr = RuleRef("unary_expr")
        self._r_exists_expr = RuleRef("exists_expr")
        self._r_exists_kw = RuleRef("exists_kw")
        self._r_prefix_unary_expr = RuleRef("prefix_unary_expr")
        self._r_prefix_unary_op = RuleRef("prefix_unary_op")
        self._r_not_kw = RuleRef("not_kw")
        self._r_primary_expr = RuleRef("primary_expr")
        self._r_paren_expr = RuleRef("paren_expr")
        self._r_case_expr = RuleRef("case_expr")
        self._r_searched_case = RuleRef("searched_case")
        self._r_simple_case = RuleRef("simple_case")
        self._r_case_kw = RuleRef("case_kw")
        self._r_when_kw = RuleRef("when_kw")
        self._r_then_kw = RuleRef("then_kw")
        self._r_else_kw = RuleRef("else_kw")
        self._r_end_kw = RuleRef("end_kw")
        self._r_when_branch = RuleRef("when_branch")
        self._r_else_branch = RuleRef("else_branch")
        self._r_atom_expr = RuleRef("atom_expr")
        self._r_func_call_expr = RuleRef("func_call_expr")
        self._r_func_args = RuleRef("func_args")
        self._r_func_star_args = RuleRef("func_star_args")
        self._r_func_list_args = RuleRef("func_list_args")
        self._r_distinct_kw = RuleRef("distinct_kw")
        self._r_literal_expr = RuleRef("literal_expr")
        self._r_bool_lit = RuleRef("bool_lit")
        self._r_null_lit = RuleRef("null_lit")
        self._r_number_lit = RuleRef("number_lit")
        self._r_float_val = RuleRef("float_val")
        self._r_int_val = RuleRef("int_val")
        self._r_string_lit = RuleRef("string_lit")
        self._r_single_string_lit = RuleRef("single_string_lit")
        self._r_double_string_lit = RuleRef("double_string_lit")
        self._r_column_ref_expr = RuleRef("column_ref_expr")
        self._r_json_path_lit = RuleRef("json_path_lit")
        self._r_ident = RuleRef("ident")
        self._r_ws = RuleRef("ws")
        self._r_opt_ws = RuleRef("opt_ws")

        self._r_root.define(
            Seq(self._r_opt_ws, self._r_or_expr, self._r_opt_ws).map(
                self._action_root_0
            )
        )
        self._r_or_expr.define(
            Seq(
                self._r_and_expr,
                ZeroOrMore(
                    Seq(self._r_ws, self._r_or_kw, self._r_ws, self._r_and_expr).map(
                        self._action_or_expr_1
                    )
                ),
            ).map(self._action_or_expr_2)
        )
        self._r_or_kw.define(Reg("(?i)\\bOR\\b"))
        self._r_and_expr.define(
            Seq(
                self._r_pred_expr,
                ZeroOrMore(
                    Seq(self._r_ws, self._r_and_kw, self._r_ws, self._r_pred_expr).map(
                        self._action_and_expr_3
                    )
                ),
            ).map(self._action_and_expr_4)
        )
        self._r_and_kw.define(Reg("(?i)\\bAND\\b"))
        self._r_pred_expr.define(
            Seq(
                self._r_add_expr,
                Opt(Seq(self._r_ws, self._r_pred_suffix).map(self._action_pred_expr_5)),
                Opt(
                    Seq(self._r_ws, self._r_collate_kw, self._r_ws, self._r_ident).map(
                        self._action_pred_expr_6
                    )
                ),
            ).map(self._action_pred_expr_7)
        )
        self._r_collate_kw.define(Reg("(?i)\\bCOLLATE\\b"))
        self._r_pred_suffix.define(
            Choice(
                self._r_is_null_suffix,
                self._r_between_suffix,
                self._r_like_suffix,
                self._r_in_suffix,
                self._r_cmp_suffix,
            )
        )
        self._r_is_null_suffix.define(
            Seq(
                self._r_is_kw,
                self._r_ws,
                Opt(Seq(self._r_not_kw, self._r_ws)),
                self._r_null_kw,
            ).map(self._action_is_null_suffix_8)
        )
        self._r_is_kw.define(Reg("(?i)\\bIS\\b"))
        self._r_null_kw.define(Reg("(?i)\\bNULL\\b"))
        self._r_between_suffix.define(
            Seq(
                Opt(Seq(self._r_not_kw, self._r_ws)),
                self._r_between_kw,
                self._r_ws,
                self._r_add_expr,
                self._r_ws,
                self._r_and_kw,
                self._r_ws,
                self._r_add_expr,
            ).map(self._action_between_suffix_9)
        )
        self._r_between_kw.define(Reg("(?i)\\bBETWEEN\\b"))
        self._r_like_suffix.define(
            Seq(
                Opt(Seq(self._r_not_kw, self._r_ws)),
                self._r_like_op,
                self._r_ws,
                self._r_add_expr,
                Opt(
                    Seq(
                        self._r_ws,
                        self._r_escape_kw,
                        self._r_ws,
                        self._r_single_string_lit,
                    ).map(self._action_like_suffix_10)
                ),
            ).map(self._action_like_suffix_11)
        )
        self._r_like_op.define(Reg("(?i)\\b(?:LIKE|GLOB|MATCH)\\b"))
        self._r_escape_kw.define(Reg("(?i)\\bESCAPE\\b"))
        self._r_in_suffix.define(
            Seq(
                Opt(Seq(self._r_not_kw, self._r_ws)),
                self._r_in_kw,
                self._r_opt_ws,
                self._r_in_body,
            ).map(self._action_in_suffix_12)
        )
        self._r_in_kw.define(Reg("(?i)\\bIN\\b"))
        self._r_in_body.define(Choice(self._r_in_subquery, self._r_in_val_list))
        self._r_in_subquery.define(
            Seq(
                Lit("("),
                self._r_opt_ws,
                self._r_subquery_text,
                self._r_opt_ws,
                Lit(")"),
            ).map(self._action_in_subquery_13)
        )
        self._r_subquery_text.define(Reg("(?i)SELECT\\b[^;)]*(?:\\([^;)]*\\)[^;)]*)*"))
        self._r_in_val_list.define(
            Seq(
                Lit("("),
                self._r_opt_ws,
                self._r_add_expr,
                ZeroOrMore(
                    Seq(self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_add_expr).map(
                        self._action_in_val_list_14
                    )
                ),
                self._r_opt_ws,
                Lit(")"),
            ).map(self._action_in_val_list_15)
        )
        self._r_cmp_suffix.define(
            Seq(self._r_cmp_op, self._r_opt_ws, self._r_add_expr).map(
                self._action_cmp_suffix_16
            )
        )
        self._r_cmp_op.define(
            Choice(
                Lit(">="), Lit("<="), Lit("<>"), Lit("!="), Lit("="), Lit(">"), Lit("<")
            )
        )
        self._r_add_expr.define(
            Seq(
                self._r_mult_expr,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws,
                        self._r_add_op,
                        self._r_opt_ws,
                        self._r_mult_expr,
                    ).map(self._action_add_expr_17)
                ),
            ).map(self._action_add_expr_18)
        )
        self._r_add_op.define(Choice(Lit("+"), Lit("-")))
        self._r_mult_expr.define(
            Seq(
                self._r_unary_expr,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws,
                        self._r_mult_op,
                        self._r_opt_ws,
                        self._r_unary_expr,
                    ).map(self._action_mult_expr_19)
                ),
            ).map(self._action_mult_expr_20)
        )
        self._r_mult_op.define(Choice(Lit("*"), Lit("/"), Lit("%")))
        self._r_unary_expr.define(
            Choice(self._r_exists_expr, self._r_prefix_unary_expr, self._r_primary_expr)
        )
        self._r_exists_expr.define(
            Seq(
                Opt(Seq(self._r_not_kw, self._r_ws)),
                self._r_exists_kw,
                self._r_opt_ws,
                Lit("("),
                self._r_opt_ws,
                self._r_subquery_text,
                self._r_opt_ws,
                Lit(")"),
            ).map(self._action_exists_expr_21)
        )
        self._r_exists_kw.define(Reg("(?i)\\bEXISTS\\b"))
        self._r_prefix_unary_expr.define(
            Seq(self._r_prefix_unary_op, self._r_opt_ws, self._r_primary_expr).map(
                self._action_prefix_unary_expr_22
            )
        )
        self._r_prefix_unary_op.define(Choice(Lit("+"), Lit("-"), self._r_not_kw))
        self._r_not_kw.define(Reg("(?i)\\bNOT\\b"))
        self._r_primary_expr.define(
            Choice(
                self._r_paren_expr,
                self._r_case_expr,
                self._r_func_call_expr,
                self._r_literal_expr,
                self._r_column_ref_expr,
            )
        )
        self._r_paren_expr.define(
            Seq(
                Lit("("), self._r_opt_ws, self._r_or_expr, self._r_opt_ws, Lit(")")
            ).map(self._action_paren_expr_23)
        )
        self._r_case_expr.define(Choice(self._r_searched_case, self._r_simple_case))
        self._r_searched_case.define(
            Seq(
                self._r_case_kw,
                self._r_ws,
                OneOrMore(
                    Seq(self._r_when_branch, self._r_ws).map(
                        self._action_searched_case_24
                    )
                ),
                Opt(
                    Seq(self._r_else_branch, self._r_ws).map(
                        self._action_searched_case_25
                    )
                ),
                self._r_end_kw,
            ).map(self._action_searched_case_26)
        )
        self._r_simple_case.define(
            Seq(
                self._r_case_kw,
                self._r_ws,
                self._r_atom_expr,
                self._r_ws,
                OneOrMore(
                    Seq(self._r_when_branch, self._r_ws).map(
                        self._action_simple_case_27
                    )
                ),
                Opt(
                    Seq(self._r_else_branch, self._r_ws).map(
                        self._action_simple_case_28
                    )
                ),
                self._r_end_kw,
            ).map(self._action_simple_case_29)
        )
        self._r_case_kw.define(Reg("(?i)\\bCASE\\b"))
        self._r_when_kw.define(Reg("(?i)\\bWHEN\\b"))
        self._r_then_kw.define(Reg("(?i)\\bTHEN\\b"))
        self._r_else_kw.define(Reg("(?i)\\bELSE\\b"))
        self._r_end_kw.define(Reg("(?i)\\bEND\\b"))
        self._r_when_branch.define(
            Seq(
                self._r_when_kw,
                self._r_ws,
                self._r_or_expr,
                self._r_ws,
                self._r_then_kw,
                self._r_ws,
                self._r_or_expr,
            ).map(self._action_when_branch_30)
        )
        self._r_else_branch.define(
            Seq(self._r_else_kw, self._r_ws, self._r_or_expr).map(
                self._action_else_branch_31
            )
        )
        self._r_atom_expr.define(
            Choice(
                self._r_func_call_expr,
                self._r_literal_expr,
                self._r_column_ref_expr,
                self._r_paren_expr,
            )
        )
        self._r_func_call_expr.define(
            Seq(self._r_ident, self._r_opt_ws, self._r_func_args).map(
                self._action_func_call_expr_32
            )
        )
        self._r_func_args.define(Choice(self._r_func_star_args, self._r_func_list_args))
        self._r_func_star_args.define(
            Seq(Lit("("), self._r_opt_ws, Lit("*"), self._r_opt_ws, Lit(")")).map(
                self._action_func_star_args_33
            )
        )
        self._r_func_list_args.define(
            Seq(
                Lit("("),
                self._r_opt_ws,
                Opt(Seq(self._r_distinct_kw, self._r_ws)),
                Opt(self._r_or_expr),
                ZeroOrMore(
                    Seq(self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_or_expr).map(
                        self._action_func_list_args_34
                    )
                ),
                self._r_opt_ws,
                Lit(")"),
            ).map(self._action_func_list_args_35)
        )
        self._r_distinct_kw.define(Reg("(?i)\\bDISTINCT\\b"))
        self._r_literal_expr.define(
            Choice(
                self._r_bool_lit,
                self._r_null_lit,
                self._r_number_lit,
                self._r_string_lit,
            )
        )
        self._r_bool_lit.define(
            Choice(
                Reg("(?i)\\bTRUE\\b").map(self._action_bool_lit_36),
                Reg("(?i)\\bFALSE\\b").map(self._action_bool_lit_37),
            )
        )
        self._r_null_lit.define(Reg("(?i)\\bNULL\\b").map(self._action_null_lit_38))
        self._r_number_lit.define(
            Choice(
                self._r_float_val.map(self._action_number_lit_39),
                self._r_int_val.map(self._action_number_lit_40),
            )
        )
        self._r_float_val.define(Reg("[0-9]+\\.[0-9]+").map(self._action_float_val_41))
        self._r_int_val.define(Reg("[0-9]+").map(self._action_int_val_42))
        self._r_string_lit.define(
            Choice(self._r_single_string_lit, self._r_double_string_lit)
        )
        self._r_single_string_lit.define(
            Reg("'(''|[^'])*'").map(self._action_single_string_lit_43)
        )
        self._r_double_string_lit.define(
            Reg('"(""|[^"])*"').map(self._action_double_string_lit_44)
        )
        self._r_column_ref_expr.define(
            Seq(
                Opt(
                    Seq(self._r_ident, self._r_opt_ws, Lit("."), self._r_opt_ws).map(
                        self._action_column_ref_expr_45
                    )
                ),
                self._r_ident,
                Opt(
                    Seq(
                        self._r_opt_ws,
                        Lit("->>"),
                        self._r_opt_ws,
                        self._r_json_path_lit,
                    ).map(self._action_column_ref_expr_46)
                ),
            ).map(self._action_column_ref_expr_47)
        )
        self._r_json_path_lit.define(
            Choice(
                Reg("'[^']*'").map(self._action_json_path_lit_48),
                Reg('"[^"]*"').map(self._action_json_path_lit_49),
            )
        )
        self._r_ident.define(Reg("[a-zA-Z_][a-zA-Z0-9_]*"))
        self._r_ws.define(Reg("[ \\t\\r\\n]+"))
        self._r_opt_ws.define(Reg("[ \\t\\r\\n]*"))

        self.root_parser: Parser[Any] = self._r_root

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_root_0(val: Any) -> Any:
        e = val[1]
        return e

    @staticmethod
    def _action_or_expr_1(val: Any) -> Any:
        next_e = val[3]
        return next_e

    @staticmethod
    def _action_or_expr_2(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        res = first
        for r in rest:
            res = BinaryOpExpr("OR", res, r)
        return res

    @staticmethod
    def _action_and_expr_3(val: Any) -> Any:
        next_e = val[3]
        return next_e

    @staticmethod
    def _action_and_expr_4(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        res = first
        for r in rest:
            res = BinaryOpExpr("AND", res, r)
        return res

    @staticmethod
    def _action_pred_expr_5(val: Any) -> Any:
        s = val[1]
        return s

    @staticmethod
    def _action_pred_expr_6(val: Any) -> Any:
        c = val[3]
        return c

    @staticmethod
    def _action_pred_expr_7(val: Any) -> Any:
        base = val[0]
        suf = val[1]
        coll = val[2]
        expr = _dispatch_pred(base, suf) if suf else base
        if coll:
            return CollateExpr(expr, coll)
        return expr

    @staticmethod
    def _action_is_null_suffix_8(val: Any) -> Any:
        is_not = val[2]
        return ("IS_NULL", bool(is_not))

    @staticmethod
    def _action_between_suffix_9(val: Any) -> Any:
        is_not = val[0]
        low = val[3]
        high = val[7]
        return ("BETWEEN", bool(is_not), low, high)

    @staticmethod
    def _action_like_suffix_10(val: Any) -> Any:
        e_str = val[3]
        return e_str

    @staticmethod
    def _action_like_suffix_11(val: Any) -> Any:
        is_not = val[0]
        op = val[1]
        pat = val[3]
        esc = val[4]
        esc_val = esc.value if esc else None
        return ("LIKE", bool(is_not), op, pat, esc_val)

    @staticmethod
    def _action_in_suffix_12(val: Any) -> Any:
        is_not = val[0]
        body = val[3]
        vals, subquery = body
        return ("IN", bool(is_not), vals, subquery)

    @staticmethod
    def _action_in_subquery_13(val: Any) -> Any:
        subq = val[2]
        return (None, subq)

    @staticmethod
    def _action_in_val_list_14(val: Any) -> Any:
        next_val = val[3]
        return next_val

    @staticmethod
    def _action_in_val_list_15(val: Any) -> Any:
        first = val[2]
        rest = val[3]
        return ([first] + rest, None)

    @staticmethod
    def _action_cmp_suffix_16(val: Any) -> Any:
        op = val[0]
        right = val[2]
        return ("CMP", op, right)

    @staticmethod
    def _action_add_expr_17(val: Any) -> Any:
        op = val[1]
        next_e = val[3]
        return (op, next_e)

    @staticmethod
    def _action_add_expr_18(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        res = first
        for op, r in rest:
            res = BinaryOpExpr(op, res, r)
        return res

    @staticmethod
    def _action_mult_expr_19(val: Any) -> Any:
        op = val[1]
        next_e = val[3]
        return (op, next_e)

    @staticmethod
    def _action_mult_expr_20(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        res = first
        for op, r in rest:
            res = BinaryOpExpr(op, res, r)
        return res

    @staticmethod
    def _action_exists_expr_21(val: Any) -> Any:
        is_not = val[0]
        subq = val[5]
        return ExistsExpr(subq, is_not=bool(is_not))

    @staticmethod
    def _action_prefix_unary_expr_22(val: Any) -> Any:
        op = val[0]
        e = val[2]
        return UnaryOpExpr(op, e)

    @staticmethod
    def _action_paren_expr_23(val: Any) -> Any:
        e = val[2]
        return e

    @staticmethod
    def _action_searched_case_24(val: Any) -> Any:
        b = val[0]
        return b

    @staticmethod
    def _action_searched_case_25(val: Any) -> Any:
        eb = val[0]
        return eb

    @staticmethod
    def _action_searched_case_26(val: Any) -> Any:
        branches = val[2]
        else_b = val[3]
        return CaseExpr(base_expr=None, when_then_list=branches, else_expr=else_b)

    @staticmethod
    def _action_simple_case_27(val: Any) -> Any:
        b = val[0]
        return b

    @staticmethod
    def _action_simple_case_28(val: Any) -> Any:
        eb = val[0]
        return eb

    @staticmethod
    def _action_simple_case_29(val: Any) -> Any:
        base = val[2]
        branches = val[4]
        else_b = val[5]
        return CaseExpr(base_expr=base, when_then_list=branches, else_expr=else_b)

    @staticmethod
    def _action_when_branch_30(val: Any) -> Any:
        cond = val[2]
        res = val[6]
        return (cond, res)

    @staticmethod
    def _action_else_branch_31(val: Any) -> Any:
        e = val[2]
        return e

    @staticmethod
    def _action_func_call_expr_32(val: Any) -> Any:
        name = val[0]
        args = val[2]
        is_star, is_dist, arg_list = args
        return FunctionCallExpr(name, arg_list, is_star=is_star, is_distinct=is_dist)

    @staticmethod
    def _action_func_star_args_33(val: Any) -> Any:
        return (True, False, [])

    @staticmethod
    def _action_func_list_args_34(val: Any) -> Any:
        next_a = val[3]
        return next_a

    @staticmethod
    def _action_func_list_args_35(val: Any) -> Any:
        dist = val[2]
        first = val[3]
        rest = val[4]
        args = []
        if first is not None:
            args.append(first)
            args.extend(rest)
        return (False, bool(dist), args)

    @staticmethod
    def _action_bool_lit_36(val: Any) -> Any:
        return LiteralExpr(True)

    @staticmethod
    def _action_bool_lit_37(val: Any) -> Any:
        return LiteralExpr(False)

    @staticmethod
    def _action_null_lit_38(val: Any) -> Any:
        return LiteralExpr(None)

    @staticmethod
    def _action_number_lit_39(val: Any) -> Any:
        f = val
        return LiteralExpr(f)

    @staticmethod
    def _action_number_lit_40(val: Any) -> Any:
        i = val
        return LiteralExpr(i)

    @staticmethod
    def _action_float_val_41(val: Any) -> Any:
        raw = val
        return float(raw)

    @staticmethod
    def _action_int_val_42(val: Any) -> Any:
        raw = val
        return int(raw)

    @staticmethod
    def _action_single_string_lit_43(val: Any) -> Any:
        raw = val
        s = raw[1:-1].replace("''", "'")
        return LiteralExpr(s)

    @staticmethod
    def _action_double_string_lit_44(val: Any) -> Any:
        raw = val
        s = raw[1:-1].replace('""', '"')
        return LiteralExpr(s)

    @staticmethod
    def _action_column_ref_expr_45(val: Any) -> Any:
        id1 = val[0]
        return id1

    @staticmethod
    def _action_column_ref_expr_46(val: Any) -> Any:
        p = val[3]
        return p

    @staticmethod
    def _action_column_ref_expr_47(val: Any) -> Any:
        tbl = val[0]
        col = val[1]
        json_p = val[2]
        return ColumnRefExpr(column=col, table=tbl, json_path=json_p)

    @staticmethod
    def _action_json_path_lit_48(val: Any) -> Any:
        raw = val
        return raw.strip("'")

    @staticmethod
    def _action_json_path_lit_49(val: Any) -> Any:
        raw = val
        return raw.strip('"')
