#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: SQLDDL
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

import re
from typing import Any, List, Optional, Tuple

from core.structures.peg import (
    Choice,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
)

# User header code


try:
    from .ast import (
        AlterTableAction,
        AlterTableStatement,
        ColumnDef,
        CreateIndexStatement,
        CreateTableStatement,
        CreateTriggerStatement,
        CreateViewStatement,
        CreateVirtualTableStatement,
        DropIndexStatement,
        DropTableStatement,
        DropTriggerStatement,
        DropViewStatement,
        ForeignKeyDef,
        ReindexStatement,
        SQLCommandType,
    )
    from .dql_parser import parse_dql
except (ImportError, ValueError):
    from database.sql.ast import (
        AlterTableAction,
        AlterTableStatement,
        ColumnDef,
        CreateIndexStatement,
        CreateTableStatement,
        CreateTriggerStatement,
        CreateViewStatement,
        CreateVirtualTableStatement,
        DropIndexStatement,
        DropTableStatement,
        DropTriggerStatement,
        DropViewStatement,
        ForeignKeyDef,
        ReindexStatement,
        SQLCommandType,
    )
    from database.sql.dql_parser import parse_dql

ALLOWED_STRICT_TYPES = {"INT", "INTEGER", "REAL", "TEXT", "BLOB", "ANY"}

_ALLOWED_ENGINES: set[str] = {
    "binary_vdb",
    "json_lines",
    "json_table",
    "file_plain_text",
    "fts5",
    "csv_table",
    "csv",
    "slotted",
    "slotted_page",
    "pager",
}


def _validate_storage_engine(engine: Optional[str]) -> Optional[str]:
    if not engine:
        return None
    from database.sql.parser import SQLParseError

    clean = engine.strip().lower()
    if clean not in _ALLOWED_ENGINES:
        allowed = ", ".join(sorted(_ALLOWED_ENGINES))
        raise SQLParseError(
            f"Unsupported storage engine: '{engine}'. Allowed: [{allowed}]"
        )
    return clean


def _validate_strict_columns(columns: List[ColumnDef]) -> None:
    from database.sql.parser import SQLParseError

    for col in columns:
        dt = col.data_type.strip().upper()
        if dt not in ALLOWED_STRICT_TYPES:
            raise SQLParseError(
                f"Unknown datatype for {col.name} in STRICT table: {col.data_type}"
            )


def _extract_col_nullability_and_keys(
    upper_c: str,
) -> Tuple[bool, bool, bool]:
    is_pk = bool(re.search(r"\bPRIMARY\s+KEY\b", upper_c))
    is_unique = bool(re.search(r"\bUNIQUE\b", upper_c))
    is_nullable = True
    if re.search(r"\bNOT\s+NULL\b", upper_c):
        is_nullable = False
    elif is_pk:
        is_nullable = False
    return is_pk, is_unique, is_nullable


def _extract_collate_from_raw(cleaned: str) -> Optional[str]:
    m_collate = re.search(r"\bCOLLATE\s+([a-zA-Z0-9_]+)\b", cleaned, re.IGNORECASE)
    return m_collate.group(1).upper() if m_collate else None


def _extract_generated_from_raw(
    cleaned: str, c_name: str
) -> Tuple[Optional[str], bool]:
    from database.sql.parser import SQLParseError

    gen_pattern = r"(?:GENERATED\s+ALWAYS\s+)?AS\s*\((.*?)\)(?:\s+(STORED|VIRTUAL))?"
    m_gen = re.search(gen_pattern, cleaned, re.IGNORECASE)
    if not m_gen:
        return None, False
    gen_expr = m_gen.group(1).strip()
    if re.search(rf"\b{re.escape(c_name)}\b", gen_expr):
        raise SQLParseError(f"Generated column '{c_name}' cannot refer to itself")
    is_stored = bool(m_gen.group(2) and m_gen.group(2).upper() == "STORED")
    return gen_expr, is_stored


def _is_null_default(raw_val: Optional[str]) -> bool:
    if raw_val is None:
        return True
    return raw_val.upper() == "NULL"


def _is_numeric_default(raw_val: str) -> Tuple[bool, Any]:
    if re.match(r"^-?\d+$", raw_val):
        return True, int(raw_val)
    if re.match(r"^-?\d+\.\d+$", raw_val):
        return True, float(raw_val)
    return False, raw_val


def _resolve_raw_default_val(raw_val: Optional[str]) -> Any:
    if _is_null_default(raw_val):
        return None
    assert raw_val is not None
    is_num, val = _is_numeric_default(raw_val)
    if is_num:
        return val
    return raw_val


def _extract_default_from_raw(cleaned: str) -> Any:
    m_def = re.search(
        r"\s+DEFAULT\s+('([^']*)'|\"([^\"]*)\"|([a-zA-Z0-9_\.\-]+))",
        cleaned,
        re.IGNORECASE,
    )
    if not m_def:
        return None
    raw_val = m_def.group(2) or m_def.group(3) or m_def.group(4)
    return _resolve_raw_default_val(raw_val)


def _extract_fk_actions_from_rest(rest: str) -> Tuple[str, str]:
    on_del = "NO ACTION"
    on_upd = "NO ACTION"
    m_del = re.search(
        r"\bON\s+DELETE\s+(CASCADE|SET\s+NULL|RESTRICT|NO\s+ACTION|SET\s+DEFAULT)\b",
        rest,
        re.IGNORECASE,
    )
    if m_del:
        on_del = m_del.group(1).upper()
    m_upd = re.search(
        r"\bON\s+UPDATE\s+(CASCADE|SET\s+NULL|RESTRICT|NO\s+ACTION|SET\s+DEFAULT)\b",
        rest,
        re.IGNORECASE,
    )
    if m_upd:
        on_upd = m_upd.group(1).upper()
    return on_del, on_upd


def _extract_fk_from_raw(
    cleaned: str, c_name: str
) -> Tuple[Optional[ForeignKeyDef], str]:
    pattern = r"\bREFERENCES\s+([a-zA-Z0-9_.]+)(?:\s*\(([a-zA-Z0-9_]+)\))?(.*?)$"
    m = re.search(pattern, cleaned, re.IGNORECASE)
    if not m:
        return None, cleaned

    ref_table = m.group(1).strip()
    ref_col = m.group(2).strip() if m.group(2) else c_name
    rest = m.group(3) or ""
    on_del, on_upd = _extract_fk_actions_from_rest(rest)

    fk = ForeignKeyDef(
        child_column=c_name,
        parent_table=ref_table,
        parent_column=ref_col,
        on_delete=on_del,
        on_update=on_upd,
    )
    cleaned_wo_fk = cleaned[: m.start()].strip()
    return fk, cleaned_wo_fk


_TABLE_CONSTRAINT_PREFIXES: Tuple[str, ...] = (
    "FOREIGN KEY ",
    "FOREIGN KEY(",
    "PRIMARY KEY ",
    "PRIMARY KEY(",
    "UNIQUE ",
    "UNIQUE(",
    "CHECK ",
    "CHECK(",
    "CONSTRAINT ",
)


def _is_table_level_constraint(upper_c: str) -> bool:
    return upper_c.startswith(_TABLE_CONSTRAINT_PREFIXES)


def _parse_single_column_def(col_str: str) -> Optional[ColumnDef]:
    cleaned = col_str.strip()
    if not cleaned:
        return None
    upper_c = cleaned.upper()
    if _is_table_level_constraint(upper_c):
        return None

    parts = cleaned.split(None, 2)
    c_name = parts[0].strip("`\"'")
    c_type = parts[1].upper() if len(parts) > 1 else "TEXT"

    is_pk, is_uniq, is_null = _extract_col_nullability_and_keys(upper_c)
    collate = _extract_collate_from_raw(cleaned)
    gen_expr, is_stored = _extract_generated_from_raw(cleaned, c_name)
    fk, cleaned_wo_fk = _extract_fk_from_raw(cleaned, c_name)
    default_val = _extract_default_from_raw(cleaned_wo_fk)

    return ColumnDef(
        name=c_name,
        data_type=c_type,
        is_primary_key=is_pk,
        is_nullable=is_null,
        default_value=default_val,
        is_unique=is_uniq,
        collate=collate,
        foreign_key=fk,
        generated_expr=gen_expr,
        is_stored=is_stored,
    )


def _clean_csv_cols(raw_cols: str) -> List[str]:
    res: List[str] = []
    for c in raw_cols.split(","):
        stripped = c.strip().strip("`\"'")
        if stripped:
            res.append(stripped)
    return res


def _extract_table_fk_def(chunk: str) -> Optional[ForeignKeyDef]:
    cleaned = chunk.strip()
    fk_pattern = (
        r"^(?:CONSTRAINT\s+[a-zA-Z0-9_]+\s+)?FOREIGN\s+KEY\s*\((.*?)\)\s*"
        r"REFERENCES\s+([a-zA-Z0-9_]+)\s*\((.*?)\)(.*)$"
    )
    m = re.search(fk_pattern, cleaned, re.IGNORECASE)
    if not m:
        return None
    cols = _clean_csv_cols(m.group(1))
    ref_tbl = m.group(2).strip().strip("`\"'")
    ref_cols = _clean_csv_cols(m.group(3))
    rest = m.group(4) or ""
    on_del, on_upd = _extract_fk_actions_from_rest(rest)
    return ForeignKeyDef(
        child_column=cols[0] if cols else "",
        parent_table=ref_tbl,
        parent_column=ref_cols[0] if ref_cols else "",
        on_delete=on_del,
        on_update=on_upd,
    )


def _split_comma_top_level(text: str) -> List[str]:
    from database.sql.parser import _split_comma_expressions

    return _split_comma_expressions(text)


def _handle_table_chunk(
    ch: str, cols: List[ColumnDef], fks: List[ForeignKeyDef]
) -> None:
    tbl_fk = _extract_table_fk_def(ch)
    if tbl_fk is not None:
        fks.append(tbl_fk)
        return
    c_def = _parse_single_column_def(ch)
    if c_def is not None:
        cols.append(c_def)
        if c_def.foreign_key is not None:
            fks.append(c_def.foreign_key)


def _split_table_items(body: str) -> Tuple[List[ColumnDef], List[ForeignKeyDef]]:
    cols: List[ColumnDef] = []
    fks: List[ForeignKeyDef] = []
    for chunk in _split_comma_top_level(body):
        ch = chunk.strip()
        if ch:
            _handle_table_chunk(ch, cols, fks)
    return cols, fks


def _extract_table_tail_opts(
    tail_str: str,
) -> Tuple[bool, Optional[str], Optional[str]]:
    strict = bool(re.search(r"\bSTRICT\b", tail_str, re.IGNORECASE))
    m_loc = re.search(r"\bLOCATION\s+['\"](.*?)['\"]", tail_str, re.IGNORECASE)
    location = m_loc.group(1).strip() if m_loc else None
    m_eng = re.search(r"\bUSING\s+([a-zA-Z0-9_]+)\b", tail_str, re.IGNORECASE)
    raw_engine = m_eng.group(1).strip() if m_eng else None
    return strict, location, raw_engine


def _assemble_create_table_stmt(
    tbl: str,
    body: str,
    tail: Optional[str],
    if_not: bool,
) -> CreateTableStatement:
    clean_body = body.strip()[1:-1]
    tail_str = tail.strip() if tail else ""
    strict, location, raw_engine = _extract_table_tail_opts(tail_str)
    engine = _validate_storage_engine(raw_engine)
    cols, fks = _split_table_items(clean_body)
    if strict:
        _validate_strict_columns(cols)
    return CreateTableStatement(
        command_type=SQLCommandType.CREATE_TABLE,
        raw_sql="",
        table_name=tbl,
        columns=cols,
        if_not_exists=if_not,
        storage_engine=engine,
        location=location,
        strict=strict,
        foreign_keys=fks,
    )


class SQLDDLParser(Parser[Any]):
    """Packrat PEG Parser for SQLDDL grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_root = RuleRef("root")
        self._r_ddl_stmt = RuleRef("ddl_stmt")
        self._r_create_table_stmt = RuleRef("create_table_stmt")
        self._r_create_virtual_table_stmt = RuleRef("create_virtual_table_stmt")
        self._r_create_index_stmt = RuleRef("create_index_stmt")
        self._r_create_view_stmt = RuleRef("create_view_stmt")
        self._r_create_trigger_stmt = RuleRef("create_trigger_stmt")
        self._r_trigger_timing = RuleRef("trigger_timing")
        self._r_trigger_event = RuleRef("trigger_event")
        self._r_trigger_body = RuleRef("trigger_body")
        self._r_alter_table_stmt = RuleRef("alter_table_stmt")
        self._r_alter_action = RuleRef("alter_action")
        self._r_rename_table_action = RuleRef("rename_table_action")
        self._r_rename_column_action = RuleRef("rename_column_action")
        self._r_add_column_action = RuleRef("add_column_action")
        self._r_drop_column_action = RuleRef("drop_column_action")
        self._r_drop_stmt = RuleRef("drop_stmt")
        self._r_drop_kind = RuleRef("drop_kind")
        self._r_reindex_stmt = RuleRef("reindex_stmt")
        self._r_opt_if_not_exists = RuleRef("opt_if_not_exists")
        self._r_opt_if_exists = RuleRef("opt_if_exists")
        self._r_paren_chunk = RuleRef("paren_chunk")
        self._r_rest_of_line = RuleRef("rest_of_line")
        self._r_ident = RuleRef("ident")
        self._r_ident_pattern = RuleRef("ident_pattern")
        self._r_backtick_pattern = RuleRef("backtick_pattern")
        self._r_double_quote_pattern = RuleRef("double_quote_pattern")
        self._r_bracket_pattern = RuleRef("bracket_pattern")
        self._r_create_kw = RuleRef("create_kw")
        self._r_table_kw = RuleRef("table_kw")
        self._r_temp_kw = RuleRef("temp_kw")
        self._r_temporary_kw = RuleRef("temporary_kw")
        self._r_virtual_kw = RuleRef("virtual_kw")
        self._r_index_kw = RuleRef("index_kw")
        self._r_unique_kw = RuleRef("unique_kw")
        self._r_view_kw = RuleRef("view_kw")
        self._r_trigger_kw = RuleRef("trigger_kw")
        self._r_alter_kw = RuleRef("alter_kw")
        self._r_drop_kw = RuleRef("drop_kw")
        self._r_reindex_kw = RuleRef("reindex_kw")
        self._r_rename_kw = RuleRef("rename_kw")
        self._r_to_kw = RuleRef("to_kw")
        self._r_add_kw = RuleRef("add_kw")
        self._r_column_kw = RuleRef("column_kw")
        self._r_using_kw = RuleRef("using_kw")
        self._r_on_kw = RuleRef("on_kw")
        self._r_as_kw = RuleRef("as_kw")
        self._r_before_kw = RuleRef("before_kw")
        self._r_after_kw = RuleRef("after_kw")
        self._r_instead_kw = RuleRef("instead_kw")
        self._r_of_kw = RuleRef("of_kw")
        self._r_insert_kw = RuleRef("insert_kw")
        self._r_update_kw = RuleRef("update_kw")
        self._r_delete_kw = RuleRef("delete_kw")
        self._r_for_kw = RuleRef("for_kw")
        self._r_each_kw = RuleRef("each_kw")
        self._r_row_kw = RuleRef("row_kw")
        self._r_begin_kw = RuleRef("begin_kw")
        self._r_end_kw = RuleRef("end_kw")
        self._r_if_kw = RuleRef("if_kw")
        self._r_not_kw = RuleRef("not_kw")
        self._r_exists_kw = RuleRef("exists_kw")
        self._r_ws = RuleRef("ws")
        self._r_opt_ws = RuleRef("opt_ws")

        self._r_root.define(
            Seq(self._r_opt_ws, self._r_ddl_stmt, self._r_opt_ws).map(
                self._action_root_0
            )
        )
        self._r_ddl_stmt.define(
            Choice(
                self._r_create_virtual_table_stmt,
                self._r_create_table_stmt,
                self._r_create_index_stmt,
                self._r_create_view_stmt,
                self._r_create_trigger_stmt,
                self._r_alter_table_stmt,
                self._r_drop_stmt,
                self._r_reindex_stmt,
            )
        )
        self._r_create_table_stmt.define(
            Seq(
                self._r_create_kw,
                Opt(Seq(self._r_ws, Choice(self._r_temp_kw, self._r_temporary_kw))),
                self._r_ws,
                self._r_table_kw,
                self._r_opt_if_not_exists,
                self._r_ws,
                self._r_ident,
                self._r_opt_ws,
                self._r_paren_chunk,
                Opt(
                    Seq(self._r_ws, self._r_rest_of_line).map(
                        self._action_create_table_stmt_1
                    )
                ),
            ).map(self._action_create_table_stmt_2)
        )
        self._r_create_virtual_table_stmt.define(
            Seq(
                self._r_create_kw,
                self._r_ws,
                self._r_virtual_kw,
                self._r_ws,
                self._r_table_kw,
                self._r_opt_if_not_exists,
                self._r_ws,
                self._r_ident,
                self._r_ws,
                self._r_using_kw,
                self._r_ws,
                self._r_ident,
                Opt(
                    Seq(self._r_opt_ws, self._r_paren_chunk).map(
                        self._action_create_virtual_table_stmt_3
                    )
                ),
            ).map(self._action_create_virtual_table_stmt_4)
        )
        self._r_create_index_stmt.define(
            Seq(
                self._r_create_kw,
                Opt(Seq(self._r_ws, self._r_unique_kw)),
                self._r_ws,
                self._r_index_kw,
                self._r_opt_if_not_exists,
                self._r_ws,
                self._r_ident,
                self._r_ws,
                self._r_on_kw,
                self._r_ws,
                self._r_ident,
                self._r_opt_ws,
                self._r_paren_chunk,
                Opt(
                    Seq(self._r_ws, self._r_using_kw, self._r_ws, self._r_ident).map(
                        self._action_create_index_stmt_5
                    )
                ),
            ).map(self._action_create_index_stmt_6)
        )
        self._r_create_view_stmt.define(
            Seq(
                self._r_create_kw,
                Opt(Seq(self._r_ws, Choice(self._r_temp_kw, self._r_temporary_kw))),
                self._r_ws,
                self._r_view_kw,
                self._r_opt_if_not_exists,
                self._r_ws,
                self._r_ident,
                self._r_ws,
                self._r_as_kw,
                self._r_ws,
                self._r_rest_of_line,
            ).map(self._action_create_view_stmt_7)
        )
        self._r_create_trigger_stmt.define(
            Seq(
                self._r_create_kw,
                Opt(Seq(self._r_ws, Choice(self._r_temp_kw, self._r_temporary_kw))),
                self._r_ws,
                self._r_trigger_kw,
                self._r_opt_if_not_exists,
                self._r_ws,
                self._r_ident,
                self._r_ws,
                self._r_trigger_timing,
                self._r_ws,
                self._r_trigger_event,
                self._r_ws,
                self._r_on_kw,
                self._r_ws,
                self._r_ident,
                Opt(
                    Seq(
                        self._r_ws,
                        self._r_for_kw,
                        self._r_ws,
                        self._r_each_kw,
                        self._r_ws,
                        self._r_row_kw,
                    )
                ),
                self._r_ws,
                self._r_begin_kw,
                self._r_ws,
                self._r_trigger_body,
                self._r_opt_ws,
                self._r_end_kw,
            ).map(self._action_create_trigger_stmt_8)
        )
        self._r_trigger_timing.define(
            Choice(
                self._r_before_kw.map(self._action_trigger_timing_9),
                self._r_after_kw.map(self._action_trigger_timing_10),
                Seq(self._r_instead_kw, self._r_ws, self._r_of_kw).map(
                    self._action_trigger_timing_11
                ),
            )
        )
        self._r_trigger_event.define(
            Choice(
                self._r_insert_kw.map(self._action_trigger_event_12),
                self._r_update_kw.map(self._action_trigger_event_13),
                self._r_delete_kw.map(self._action_trigger_event_14),
            )
        )
        self._r_trigger_body.define(
            Reg("(?is).*?(?=\\bEND\\b)").map(self._action_trigger_body_15)
        )
        self._r_alter_table_stmt.define(
            Seq(
                self._r_alter_kw,
                self._r_ws,
                self._r_table_kw,
                self._r_ws,
                self._r_ident,
                self._r_ws,
                self._r_alter_action,
            ).map(self._action_alter_table_stmt_16)
        )
        self._r_alter_action.define(
            Choice(
                self._r_rename_table_action,
                self._r_rename_column_action,
                self._r_add_column_action,
                self._r_drop_column_action,
            )
        )
        self._r_rename_table_action.define(
            Seq(
                self._r_rename_kw, self._r_ws, self._r_to_kw, self._r_ws, self._r_ident
            ).map(self._action_rename_table_action_17)
        )
        self._r_rename_column_action.define(
            Seq(
                self._r_rename_kw,
                Opt(Seq(self._r_ws, self._r_column_kw)),
                self._r_ws,
                self._r_ident,
                self._r_ws,
                self._r_to_kw,
                self._r_ws,
                self._r_ident,
            ).map(self._action_rename_column_action_18)
        )
        self._r_add_column_action.define(
            Seq(
                self._r_add_kw,
                Opt(Seq(self._r_ws, self._r_column_kw)),
                self._r_ws,
                self._r_rest_of_line,
            ).map(self._action_add_column_action_19)
        )
        self._r_drop_column_action.define(
            Seq(
                self._r_drop_kw,
                Opt(Seq(self._r_ws, self._r_column_kw)),
                self._r_ws,
                self._r_ident,
            ).map(self._action_drop_column_action_20)
        )
        self._r_drop_stmt.define(
            Seq(
                self._r_drop_kw,
                self._r_ws,
                self._r_drop_kind,
                self._r_opt_if_exists,
                self._r_ws,
                self._r_ident,
            ).map(self._action_drop_stmt_21)
        )
        self._r_drop_kind.define(
            Choice(
                self._r_table_kw.map(self._action_drop_kind_22),
                self._r_index_kw.map(self._action_drop_kind_23),
                self._r_view_kw.map(self._action_drop_kind_24),
                self._r_trigger_kw.map(self._action_drop_kind_25),
            )
        )
        self._r_reindex_stmt.define(
            Seq(
                self._r_reindex_kw,
                Opt(Seq(self._r_ws, self._r_ident).map(self._action_reindex_stmt_26)),
            ).map(self._action_reindex_stmt_27)
        )
        self._r_opt_if_not_exists.define(
            Opt(
                Seq(
                    self._r_ws,
                    self._r_if_kw,
                    self._r_ws,
                    self._r_not_kw,
                    self._r_ws,
                    self._r_exists_kw,
                )
            ).map(self._action_opt_if_not_exists_28)
        )
        self._r_opt_if_exists.define(
            Opt(Seq(self._r_ws, self._r_if_kw, self._r_ws, self._r_exists_kw)).map(
                self._action_opt_if_exists_29
            )
        )
        self._r_paren_chunk.define(
            Reg("\\((?:[^()]|\\([^()]*\\))*\\)").map(self._action_paren_chunk_30)
        )
        self._r_rest_of_line.define(
            Reg("[^\\r\\n;]+").map(self._action_rest_of_line_31)
        )
        self._r_ident.define(
            Choice(
                self._r_ident_pattern.map(self._action_ident_32),
                self._r_backtick_pattern.map(self._action_ident_33),
                self._r_double_quote_pattern.map(self._action_ident_34),
                self._r_bracket_pattern.map(self._action_ident_35),
            )
        )
        self._r_ident_pattern.define(
            Reg("[a-zA-Z_][a-zA-Z0-9_]*(\\.[a-zA-Z_][a-zA-Z0-9_]*)?").map(
                self._action_ident_pattern_36
            )
        )
        self._r_backtick_pattern.define(
            Reg("`[^`]*`").map(self._action_backtick_pattern_37)
        )
        self._r_double_quote_pattern.define(
            Reg('"[^"]*"').map(self._action_double_quote_pattern_38)
        )
        self._r_bracket_pattern.define(
            Reg("\\[[^\\]]*\\]").map(self._action_bracket_pattern_39)
        )
        self._r_create_kw.define(Reg("(?i)\\bCREATE\\b"))
        self._r_table_kw.define(Reg("(?i)\\bTABLE\\b"))
        self._r_temp_kw.define(Reg("(?i)\\bTEMP\\b"))
        self._r_temporary_kw.define(Reg("(?i)\\bTEMPORARY\\b"))
        self._r_virtual_kw.define(Reg("(?i)\\bVIRTUAL\\b"))
        self._r_index_kw.define(Reg("(?i)\\bINDEX\\b"))
        self._r_unique_kw.define(Reg("(?i)\\bUNIQUE\\b"))
        self._r_view_kw.define(Reg("(?i)\\bVIEW\\b"))
        self._r_trigger_kw.define(Reg("(?i)\\bTRIGGER\\b"))
        self._r_alter_kw.define(Reg("(?i)\\bALTER\\b"))
        self._r_drop_kw.define(Reg("(?i)\\bDROP\\b"))
        self._r_reindex_kw.define(Reg("(?i)\\bREINDEX\\b"))
        self._r_rename_kw.define(Reg("(?i)\\bRENAME\\b"))
        self._r_to_kw.define(Reg("(?i)\\bTO\\b"))
        self._r_add_kw.define(Reg("(?i)\\bADD\\b"))
        self._r_column_kw.define(Reg("(?i)\\bCOLUMN\\b"))
        self._r_using_kw.define(Reg("(?i)\\bUSING\\b"))
        self._r_on_kw.define(Reg("(?i)\\bON\\b"))
        self._r_as_kw.define(Reg("(?i)\\bAS\\b"))
        self._r_before_kw.define(Reg("(?i)\\bBEFORE\\b"))
        self._r_after_kw.define(Reg("(?i)\\bAFTER\\b"))
        self._r_instead_kw.define(Reg("(?i)\\bINSTEAD\\b"))
        self._r_of_kw.define(Reg("(?i)\\bOF\\b"))
        self._r_insert_kw.define(Reg("(?i)\\bINSERT\\b"))
        self._r_update_kw.define(Reg("(?i)\\bUPDATE\\b"))
        self._r_delete_kw.define(Reg("(?i)\\bDELETE\\b"))
        self._r_for_kw.define(Reg("(?i)\\bFOR\\b"))
        self._r_each_kw.define(Reg("(?i)\\bEACH\\b"))
        self._r_row_kw.define(Reg("(?i)\\bROW\\b"))
        self._r_begin_kw.define(Reg("(?i)\\bBEGIN\\b"))
        self._r_end_kw.define(Reg("(?i)\\bEND\\b"))
        self._r_if_kw.define(Reg("(?i)\\bIF\\b"))
        self._r_not_kw.define(Reg("(?i)\\bNOT\\b"))
        self._r_exists_kw.define(Reg("(?i)\\bEXISTS\\b"))
        self._r_ws.define(Reg("[ \\t\\r\\n]+|#[^\\r\\n]*|--[^\\r\\n]*"))
        self._r_opt_ws.define(Reg("[ \\t\\r\\n]*|#[^\\r\\n]*|--[^\\r\\n]*"))

        self.root_parser: Parser[Any] = self._r_root

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_root_0(val: Any) -> Any:
        ddl = val[1]
        return ddl

    @staticmethod
    def _action_create_table_stmt_1(val: Any) -> Any:
        t = val[1]
        return t

    @staticmethod
    def _action_create_table_stmt_2(val: Any) -> Any:
        if_not = val[4]
        tbl = val[6]
        body = val[8]
        tail = val[9]
        return _assemble_create_table_stmt(tbl, body, tail, if_not)

    @staticmethod
    def _action_create_virtual_table_stmt_3(val: Any) -> Any:
        p = val[1]
        return p

    @staticmethod
    def _action_create_virtual_table_stmt_4(val: Any) -> Any:
        if_not = val[5]
        tbl = val[7]
        module = val[11]
        args_paren = val[12]
        args_raw = args_paren.strip()[1:-1] if args_paren else ""
        args = [a.strip() for a in _split_comma_top_level(args_raw) if a.strip()]
        return CreateVirtualTableStatement(
            command_type=SQLCommandType.CREATE_VIRTUAL_TABLE,
            raw_sql="",
            table_name=tbl,
            module_name=module,
            module_args=args,
            if_not_exists=if_not,
        )

    @staticmethod
    def _action_create_index_stmt_5(val: Any) -> Any:
        it = val[3]
        return it

    @staticmethod
    def _action_create_index_stmt_6(val: Any) -> Any:
        idx = val[6]
        tbl = val[10]
        cols_paren = val[12]
        idx_type_opt = val[13]
        cols_body = cols_paren.strip()[1:-1].strip()
        idx_t = idx_type_opt.upper() if idx_type_opt else "HNSW"
        return CreateIndexStatement(
            command_type=SQLCommandType.CREATE_INDEX,
            raw_sql="",
            index_name=idx,
            table_name=tbl,
            column_name=cols_body,
            index_type=idx_t,
        )

    @staticmethod
    def _action_create_view_stmt_7(val: Any) -> Any:
        if_not = val[4]
        vw = val[6]
        select_raw = val[10]
        sub_select = parse_dql(select_raw.strip())
        return CreateViewStatement(
            command_type=SQLCommandType.CREATE_VIEW,
            raw_sql="",
            view_name=vw,
            select_stmt=sub_select,
            if_not_exists=if_not,
        )

    @staticmethod
    def _action_create_trigger_stmt_8(val: Any) -> Any:
        trg = val[6]
        timing = val[8]
        event = val[10]
        tbl = val[14]
        body_raw = val[19]
        body_sqls = [s.strip() for s in body_raw.split(";") if s.strip()]
        return CreateTriggerStatement(
            command_type=SQLCommandType.CREATE_TRIGGER,
            raw_sql="",
            trigger_name=trg,
            timing=timing,
            event=event,
            table_name=tbl,
            body_sqls=body_sqls,
        )

    @staticmethod
    def _action_trigger_timing_9(val: Any) -> Any:
        return "BEFORE"

    @staticmethod
    def _action_trigger_timing_10(val: Any) -> Any:
        return "AFTER"

    @staticmethod
    def _action_trigger_timing_11(val: Any) -> Any:
        return "INSTEAD OF"

    @staticmethod
    def _action_trigger_event_12(val: Any) -> Any:
        return "INSERT"

    @staticmethod
    def _action_trigger_event_13(val: Any) -> Any:
        return "UPDATE"

    @staticmethod
    def _action_trigger_event_14(val: Any) -> Any:
        return "DELETE"

    @staticmethod
    def _action_trigger_body_15(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_alter_table_stmt_16(val: Any) -> Any:
        tbl = val[4]
        action = val[6]
        return action(tbl)

    @staticmethod
    def _action_rename_table_action_17(val: Any) -> Any:
        new_tbl = val[4]
        return lambda tbl: AlterTableStatement(
            command_type=SQLCommandType.ALTER_TABLE,
            raw_sql="",
            table_name=tbl,
            action=AlterTableAction.RENAME_TABLE,
            new_table_name=new_tbl,
        )

    @staticmethod
    def _action_rename_column_action_18(val: Any) -> Any:
        old_c = val[3]
        new_c = val[7]
        return lambda tbl: AlterTableStatement(
            command_type=SQLCommandType.ALTER_TABLE,
            raw_sql="",
            table_name=tbl,
            action=AlterTableAction.RENAME_COLUMN,
            old_column_name=old_c,
            new_column_name=new_c,
        )

    @staticmethod
    def _action_add_column_action_19(val: Any) -> Any:
        raw_col = val[3]
        c_def = _parse_single_column_def(raw_col.strip())
        def_val = c_def.default_value if c_def else None
        return lambda tbl: AlterTableStatement(
            command_type=SQLCommandType.ALTER_TABLE,
            raw_sql="",
            table_name=tbl,
            action=AlterTableAction.ADD_COLUMN,
            column_def=c_def,
            default_value=def_val,
        )

    @staticmethod
    def _action_drop_column_action_20(val: Any) -> Any:
        drop_c = val[3]
        return lambda tbl: AlterTableStatement(
            command_type=SQLCommandType.ALTER_TABLE,
            raw_sql="",
            table_name=tbl,
            action=AlterTableAction.DROP_COLUMN,
            drop_column_name=drop_c,
        )

    @staticmethod
    def _action_drop_stmt_21(val: Any) -> Any:
        kind = val[2]
        if_ex = val[3]
        target = val[5]
        if kind == "TABLE":
            return DropTableStatement(
                command_type=SQLCommandType.DROP_TABLE,
                raw_sql="",
                table_name=target,
                if_exists=if_ex,
            )
        elif kind == "INDEX":
            return DropIndexStatement(
                command_type=SQLCommandType.DROP_INDEX,
                raw_sql="",
                index_name=target,
                if_exists=if_ex,
            )
        elif kind == "VIEW":
            return DropViewStatement(
                command_type=SQLCommandType.DROP_VIEW,
                raw_sql="",
                view_name=target,
                if_exists=if_ex,
            )
        else:
            return DropTriggerStatement(
                command_type=SQLCommandType.DROP_TRIGGER,
                raw_sql="",
                trigger_name=target,
                if_exists=if_ex,
            )

    @staticmethod
    def _action_drop_kind_22(val: Any) -> Any:
        return "TABLE"

    @staticmethod
    def _action_drop_kind_23(val: Any) -> Any:
        return "INDEX"

    @staticmethod
    def _action_drop_kind_24(val: Any) -> Any:
        return "VIEW"

    @staticmethod
    def _action_drop_kind_25(val: Any) -> Any:
        return "TRIGGER"

    @staticmethod
    def _action_reindex_stmt_26(val: Any) -> Any:
        t = val[1]
        return t

    @staticmethod
    def _action_reindex_stmt_27(val: Any) -> Any:
        target = val[1]
        return ReindexStatement(
            command_type=SQLCommandType.REINDEX,
            raw_sql="",
            target_name=target,
        )

    @staticmethod
    def _action_opt_if_not_exists_28(val: Any) -> Any:
        flag = val
        return bool(flag)

    @staticmethod
    def _action_opt_if_exists_29(val: Any) -> Any:
        flag = val
        return bool(flag)

    @staticmethod
    def _action_paren_chunk_30(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_rest_of_line_31(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_ident_32(val: Any) -> Any:
        plain = val
        return plain

    @staticmethod
    def _action_ident_33(val: Any) -> Any:
        backtick = val
        return backtick

    @staticmethod
    def _action_ident_34(val: Any) -> Any:
        double_quote = val
        return double_quote

    @staticmethod
    def _action_ident_35(val: Any) -> Any:
        bracket = val
        return bracket

    @staticmethod
    def _action_ident_pattern_36(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_backtick_pattern_37(val: Any) -> Any:
        raw = val
        return raw[1:-1]

    @staticmethod
    def _action_double_quote_pattern_38(val: Any) -> Any:
        raw = val
        return raw[1:-1]

    @staticmethod
    def _action_bracket_pattern_39(val: Any) -> Any:
        raw = val
        return raw[1:-1]
