#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: SQLDML
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

import ast as py_ast
from typing import Any, Dict, List, Optional, Tuple, cast

from core.structures.peg import (
    Choice,
    Lit,
    NotPred,
    OneOrMore,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
    ZeroOrMore,
)

# User header code


try:
    from .ast import (
        DeleteStatement,
        InsertStatement,
        JoinClause,
        JoinType,
        SelectStatement,
        SQLCommandType,
        TableRef,
        UpdateStatement,
    )
    from .dql_parser import parse_dql
except (ImportError, ValueError):
    from database.sql.ast import (
        DeleteStatement,
        InsertStatement,
        JoinClause,
        JoinType,
        SelectStatement,
        SQLCommandType,
        TableRef,
        UpdateStatement,
    )
    from database.sql.dql_parser import parse_dql


def _resolve_boolean_or_null(clean: str) -> Tuple[bool, Any]:
    u = clean.upper()
    if u == "NULL":
        return True, None
    if u == "TRUE":
        return True, True
    if u == "FALSE":
        return True, False
    return False, None


def _resolve_raw_literal(val_str: str) -> Any:
    clean = val_str.strip()
    is_special, val = _resolve_boolean_or_null(clean)
    if is_special:
        return val
    try:
        return py_ast.literal_eval(clean)
    except Exception:
        return clean.strip("'\"")


def _extract_where_list(where_raw: Optional[str]) -> List[Dict[str, Any]]:
    if not where_raw:
        return []
    from database.sql.parser import SQLParser

    dummy_parser = SQLParser()
    return dummy_parser._extract_where_clauses(where_raw.strip())


def _validate_insert_rows_columns(cols: List[str], rows: List[List[Any]]) -> None:
    if not cols:
        return
    for r in rows:
        if len(r) != len(cols):
            from database.sql.dml_parser import SQLParseError

            raise SQLParseError(
                f"Column count ({len(cols)}) does not match values count ({len(r)})"
            )


def _make_insert_values_stmt(
    table_name: str,
    cols: List[str],
    rows: List[List[Any]],
    up_tgt: Optional[List[str]],
    up_act: Optional[str],
    up_set: Dict[str, Any],
    ret_cols: Optional[List[str]],
) -> InsertStatement:
    _validate_insert_rows_columns(cols, rows)
    first_val = rows[0] if rows else []
    return InsertStatement(
        command_type=SQLCommandType.INSERT,
        raw_sql="",
        table_name=table_name,
        columns=cols,
        values=first_val,
        rows_values=rows,
        upsert_target=up_tgt,
        upsert_action=up_act,
        upsert_update_set=up_set,
        returning_cols=ret_cols,
    )


def _resolve_upsert_metadata(
    is_replace: bool,
    upsert_info: Optional[Tuple[Optional[List[str]], str, Dict[str, Any]]],
) -> Tuple[Optional[List[str]], Optional[str], Dict[str, Any]]:
    if upsert_info:
        up_act: Optional[str] = "UPDATE" if is_replace else upsert_info[1]
        return upsert_info[0], up_act, upsert_info[2]
    no_up_act: Optional[str] = "UPDATE" if is_replace else None
    return None, no_up_act, {}


def _assemble_insert_stmt(
    is_replace: bool,
    table_name: str,
    cols: Optional[List[str]],
    body: Any,
    upsert_info: Optional[Tuple[Optional[List[str]], str, Dict[str, Any]]],
    ret_cols: Optional[List[str]],
) -> InsertStatement:
    cols_list = cols or []
    up_tgt, up_act, up_set = _resolve_upsert_metadata(is_replace, upsert_info)

    if isinstance(body, SelectStatement):
        return InsertStatement(
            command_type=SQLCommandType.INSERT,
            raw_sql="",
            table_name=table_name,
            columns=cols_list,
            select_stmt=body,
            upsert_target=up_tgt,
            upsert_action=up_act,
            upsert_update_set=up_set,
            returning_cols=ret_cols,
        )

    return _make_insert_values_stmt(
        table_name=table_name,
        cols=cols_list,
        rows=cast(List[List[Any]], body),
        up_tgt=up_tgt,
        up_act=up_act,
        up_set=up_set,
        ret_cols=ret_cols,
    )


def _unpack_hint(
    hint: Optional[Tuple[Optional[str], bool]],
) -> Tuple[Optional[str], bool]:
    if not hint:
        return None, False
    return hint[0], hint[1]


def _unpack_ord_lim(
    ord_lim: Optional[Tuple[Optional[str], bool, Optional[int]]],
) -> Tuple[Optional[str], bool, Optional[int]]:
    if not ord_lim:
        return None, False, None
    return ord_lim[0], ord_lim[1], ord_lim[2]


def _unpack_from_info(
    from_info: Optional[Tuple[TableRef, List[JoinClause]]],
) -> Tuple[Optional[TableRef], List[JoinClause]]:
    if not from_info:
        return None, []
    return from_info[0], from_info[1]


def _assemble_update_stmt(
    tbl_name: str,
    hint: Optional[Tuple[Optional[str], bool]],
    sets: Tuple[Dict[str, Any], Dict[str, str]],
    from_info: Optional[Tuple[TableRef, List[JoinClause]]],
    where_raw: Optional[str],
    ord_lim: Optional[Tuple[Optional[str], bool, Optional[int]]],
    ret_cols: Optional[List[str]],
) -> UpdateStatement:
    indexed_by, not_indexed = _unpack_hint(hint)
    from_tbl, joins_list = _unpack_from_info(from_info)
    order_by, order_desc, limit_val = _unpack_ord_lim(ord_lim)
    where_clauses = _extract_where_list(where_raw)

    return UpdateStatement(
        command_type=SQLCommandType.UPDATE,
        raw_sql="",
        table_name=tbl_name,
        assignments=sets[0],
        raw_assignments=sets[1],
        from_table=from_tbl,
        joins=joins_list,
        where_clauses=where_clauses,
        returning_cols=ret_cols,
        order_by=order_by,
        order_desc=order_desc,
        limit=limit_val,
        indexed_by=indexed_by,
        not_indexed=not_indexed,
    )


def _assemble_delete_stmt(
    tbl_name: str,
    hint: Optional[Tuple[Optional[str], bool]],
    where_raw: Optional[str],
    ord_lim: Optional[Tuple[Optional[str], bool, Optional[int]]],
    ret_cols: Optional[List[str]],
) -> DeleteStatement:
    indexed_by, not_indexed = _unpack_hint(hint)
    order_by, order_desc, limit_val = _unpack_ord_lim(ord_lim)
    where_clauses = _extract_where_list(where_raw)

    return DeleteStatement(
        command_type=SQLCommandType.DELETE,
        raw_sql="",
        table_name=tbl_name,
        where_clauses=where_clauses,
        returning_cols=ret_cols,
        order_by=order_by,
        order_desc=order_desc,
        limit=limit_val,
        indexed_by=indexed_by,
        not_indexed=not_indexed,
    )


class SQLDMLParser(Parser[Any]):
    """Packrat PEG Parser for SQLDML grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_root = RuleRef("root")
        self._r_dml_stmt = RuleRef("dml_stmt")
        self._r_insert_stmt = RuleRef("insert_stmt")
        self._r_insert_header = RuleRef("insert_header")
        self._r_insert_body = RuleRef("insert_body")
        self._r_values_clause = RuleRef("values_clause")
        self._r_values_rows = RuleRef("values_rows")
        self._r_value_row = RuleRef("value_row")
        self._r_value_atom = RuleRef("value_atom")
        self._r_atom_token = RuleRef("atom_token")
        self._r_select_insert_body = RuleRef("select_insert_body")
        self._r_select_raw_text = RuleRef("select_raw_text")
        self._r_select_chunk = RuleRef("select_chunk")
        self._r_select_insert_end = RuleRef("select_insert_end")
        self._r_on_conflict_kw = RuleRef("on_conflict_kw")
        self._r_upsert_clause = RuleRef("upsert_clause")
        self._r_upsert_action = RuleRef("upsert_action")
        self._r_update_stmt = RuleRef("update_stmt")
        self._r_set_assignment_list = RuleRef("set_assignment_list")
        self._r_set_item = RuleRef("set_item")
        self._r_set_expr = RuleRef("set_expr")
        self._r_set_chunk = RuleRef("set_chunk")
        self._r_set_end = RuleRef("set_end")
        self._r_update_from_clause = RuleRef("update_from_clause")
        self._r_join_spec = RuleRef("join_spec")
        self._r_delete_stmt = RuleRef("delete_stmt")
        self._r_where_clause = RuleRef("where_clause")
        self._r_where_body_expr = RuleRef("where_body_expr")
        self._r_where_chunk = RuleRef("where_chunk")
        self._r_where_end = RuleRef("where_end")
        self._r_order_limit_clause = RuleRef("order_limit_clause")
        self._r_order_by_clause = RuleRef("order_by_clause")
        self._r_order_dir = RuleRef("order_dir")
        self._r_limit_clause = RuleRef("limit_clause")
        self._r_returning_clause = RuleRef("returning_clause")
        self._r_returning_item_list = RuleRef("returning_item_list")
        self._r_returning_item = RuleRef("returning_item")
        self._r_idx_hint = RuleRef("idx_hint")
        self._r_ident_list = RuleRef("ident_list")
        self._r_ident = RuleRef("ident")
        self._r_ident_pattern = RuleRef("ident_pattern")
        self._r_backtick_pattern = RuleRef("backtick_pattern")
        self._r_double_quote_pattern = RuleRef("double_quote_pattern")
        self._r_non_reserved_ident = RuleRef("non_reserved_ident")
        self._r_reserved_kw = RuleRef("reserved_kw")
        self._r_string_literal = RuleRef("string_literal")
        self._r_double_quote_literal = RuleRef("double_quote_literal")
        self._r_bracket_token = RuleRef("bracket_token")
        self._r_chunk_token = RuleRef("chunk_token")
        self._r_func_call_token = RuleRef("func_call_token")
        self._r_paren_token = RuleRef("paren_token")
        self._r_non_ws_token = RuleRef("non_ws_token")
        self._r_integer_num = RuleRef("integer_num")
        self._r_insert_kw = RuleRef("insert_kw")
        self._r_replace_kw = RuleRef("replace_kw")
        self._r_into_kw = RuleRef("into_kw")
        self._r_update_kw = RuleRef("update_kw")
        self._r_delete_kw = RuleRef("delete_kw")
        self._r_from_kw = RuleRef("from_kw")
        self._r_set_kw = RuleRef("set_kw")
        self._r_values_kw = RuleRef("values_kw")
        self._r_where_kw = RuleRef("where_kw")
        self._r_order_kw = RuleRef("order_kw")
        self._r_by_kw = RuleRef("by_kw")
        self._r_limit_kw = RuleRef("limit_kw")
        self._r_returning_kw = RuleRef("returning_kw")
        self._r_on_kw = RuleRef("on_kw")
        self._r_conflict_kw = RuleRef("conflict_kw")
        self._r_do_kw = RuleRef("do_kw")
        self._r_nothing_kw = RuleRef("nothing_kw")
        self._r_indexed_kw = RuleRef("indexed_kw")
        self._r_not_kw = RuleRef("not_kw")
        self._r_or_kw = RuleRef("or_kw")
        self._r_rollback_kw = RuleRef("rollback_kw")
        self._r_abort_kw = RuleRef("abort_kw")
        self._r_fail_kw = RuleRef("fail_kw")
        self._r_ignore_kw = RuleRef("ignore_kw")
        self._r_join_kw = RuleRef("join_kw")
        self._r_asc_kw = RuleRef("asc_kw")
        self._r_desc_kw = RuleRef("desc_kw")
        self._r_select_kw = RuleRef("select_kw")
        self._r_ws = RuleRef("ws")
        self._r_opt_ws = RuleRef("opt_ws")

        self._r_root.define(
            Seq(self._r_opt_ws, self._r_dml_stmt, self._r_opt_ws).map(
                self._action_root_0
            )
        )
        self._r_dml_stmt.define(
            Choice(self._r_insert_stmt, self._r_update_stmt, self._r_delete_stmt)
        )
        self._r_insert_stmt.define(
            Seq(
                self._r_insert_header,
                self._r_ws,
                self._r_ident,
                Opt(
                    Seq(
                        self._r_opt_ws,
                        Lit("("),
                        self._r_opt_ws,
                        self._r_ident_list,
                        self._r_opt_ws,
                        Lit(")"),
                    ).map(self._action_insert_stmt_1)
                ),
                self._r_ws,
                self._r_insert_body,
                Opt(
                    Seq(self._r_opt_ws, self._r_upsert_clause).map(
                        self._action_insert_stmt_2
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_returning_clause).map(
                        self._action_insert_stmt_3
                    )
                ),
            ).map(self._action_insert_stmt_4)
        )
        self._r_insert_header.define(
            Choice(
                Seq(self._r_replace_kw, self._r_ws, self._r_into_kw).map(
                    self._action_insert_header_5
                ),
                Seq(
                    self._r_insert_kw,
                    self._r_ws,
                    self._r_or_kw,
                    self._r_ws,
                    self._r_replace_kw,
                    self._r_ws,
                    self._r_into_kw,
                ).map(self._action_insert_header_6),
                Seq(self._r_insert_kw, self._r_ws, self._r_into_kw).map(
                    self._action_insert_header_7
                ),
            )
        )
        self._r_insert_body.define(
            Choice(self._r_values_clause, self._r_select_insert_body)
        )
        self._r_values_clause.define(
            Seq(self._r_values_kw, self._r_ws, self._r_values_rows).map(
                self._action_values_clause_8
            )
        )
        self._r_values_rows.define(
            Seq(
                self._r_value_row,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_value_row
                    ).map(self._action_values_rows_9)
                ),
            ).map(self._action_values_rows_10)
        )
        self._r_value_row.define(
            Seq(
                Lit("("),
                self._r_opt_ws,
                self._r_value_atom,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_value_atom
                    ).map(self._action_value_row_11)
                ),
                self._r_opt_ws,
                Lit(")"),
            ).map(self._action_value_row_12)
        )
        self._r_value_atom.define(
            Seq(self._r_atom_token, self._r_opt_ws).map(self._action_value_atom_13)
        )
        self._r_atom_token.define(
            Choice(
                self._r_string_literal,
                self._r_double_quote_literal,
                self._r_bracket_token,
                Reg("[^\\s,)]+"),
            )
        )
        self._r_select_insert_body.define(
            self._r_select_raw_text.map(self._action_select_insert_body_14)
        )
        self._r_select_raw_text.define(
            Seq(self._r_select_kw, self._r_ws, OneOrMore(self._r_select_chunk)).map(
                self._action_select_raw_text_15
            )
        )
        self._r_select_chunk.define(
            Seq(
                NotPred(self._r_select_insert_end),
                Choice(Lit(","), self._r_chunk_token),
                self._r_opt_ws,
            ).map(self._action_select_chunk_16)
        )
        self._r_select_insert_end.define(
            Choice(self._r_on_conflict_kw, self._r_returning_kw, Lit(";"))
        )
        self._r_on_conflict_kw.define(
            Seq(self._r_on_kw, self._r_ws, self._r_conflict_kw)
        )
        self._r_upsert_clause.define(
            Seq(
                self._r_on_kw,
                self._r_ws,
                self._r_conflict_kw,
                Opt(
                    Seq(
                        self._r_opt_ws,
                        Lit("("),
                        self._r_opt_ws,
                        self._r_ident_list,
                        self._r_opt_ws,
                        Lit(")"),
                    ).map(self._action_upsert_clause_17)
                ),
                Opt(
                    Seq(self._r_ws, self._r_where_kw, self._r_ws, Reg("[^\\bDO\\b;]+"))
                ),
                self._r_ws,
                self._r_do_kw,
                self._r_ws,
                self._r_upsert_action,
            ).map(self._action_upsert_clause_18)
        )
        self._r_upsert_action.define(
            Choice(
                self._r_nothing_kw.map(self._action_upsert_action_19),
                Seq(
                    self._r_update_kw,
                    self._r_ws,
                    self._r_set_kw,
                    self._r_ws,
                    self._r_set_assignment_list,
                    Opt(
                        Seq(
                            self._r_ws,
                            self._r_where_kw,
                            self._r_ws,
                            Reg("[^\\bRETURNING\\b;]+"),
                        )
                    ),
                ).map(self._action_upsert_action_20),
            )
        )
        self._r_update_stmt.define(
            Seq(
                self._r_update_kw,
                Opt(
                    Seq(
                        self._r_ws,
                        self._r_or_kw,
                        self._r_ws,
                        Choice(
                            self._r_rollback_kw,
                            self._r_abort_kw,
                            self._r_fail_kw,
                            self._r_ignore_kw,
                            self._r_replace_kw,
                        ),
                    )
                ),
                self._r_ws,
                self._r_ident,
                Opt(Seq(self._r_ws, self._r_idx_hint).map(self._action_update_stmt_21)),
                self._r_ws,
                self._r_set_kw,
                self._r_ws,
                self._r_set_assignment_list,
                Opt(
                    Seq(self._r_opt_ws, self._r_update_from_clause).map(
                        self._action_update_stmt_22
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_where_clause).map(
                        self._action_update_stmt_23
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_order_limit_clause).map(
                        self._action_update_stmt_24
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_returning_clause).map(
                        self._action_update_stmt_25
                    )
                ),
            ).map(self._action_update_stmt_26)
        )
        self._r_set_assignment_list.define(
            Seq(
                self._r_set_item,
                ZeroOrMore(
                    Seq(self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_set_item).map(
                        self._action_set_assignment_list_27
                    )
                ),
            ).map(self._action_set_assignment_list_28)
        )
        self._r_set_item.define(
            Seq(
                self._r_ident,
                self._r_opt_ws,
                Lit("="),
                self._r_opt_ws,
                self._r_set_expr,
            ).map(self._action_set_item_29)
        )
        self._r_set_expr.define(
            OneOrMore(self._r_set_chunk).map(self._action_set_expr_30)
        )
        self._r_set_chunk.define(
            Seq(NotPred(self._r_set_end), self._r_chunk_token, self._r_opt_ws).map(
                self._action_set_chunk_31
            )
        )
        self._r_set_end.define(
            Choice(
                self._r_from_kw,
                self._r_where_kw,
                self._r_order_kw,
                self._r_limit_kw,
                self._r_returning_kw,
                Lit(";"),
            )
        )
        self._r_update_from_clause.define(
            Seq(
                self._r_from_kw,
                self._r_ws,
                self._r_ident,
                Opt(
                    Seq(self._r_ws, self._r_non_reserved_ident).map(
                        self._action_update_from_clause_32
                    )
                ),
                ZeroOrMore(
                    Seq(self._r_opt_ws, self._r_join_spec).map(
                        self._action_update_from_clause_33
                    )
                ),
            ).map(self._action_update_from_clause_34)
        )
        self._r_join_spec.define(
            Seq(
                self._r_join_kw,
                self._r_ws,
                self._r_ident,
                Opt(
                    Seq(self._r_ws, self._r_non_reserved_ident).map(
                        self._action_join_spec_35
                    )
                ),
                Opt(
                    Seq(
                        self._r_ws,
                        self._r_on_kw,
                        self._r_ws,
                        Reg("[^\\bWHERE\\b\\bORDER\\b\\bLIMIT\\b\\bRETURNING\\b;]+"),
                    )
                ),
            ).map(self._action_join_spec_36)
        )
        self._r_delete_stmt.define(
            Seq(
                self._r_delete_kw,
                self._r_ws,
                self._r_from_kw,
                self._r_ws,
                self._r_ident,
                Opt(Seq(self._r_ws, self._r_idx_hint).map(self._action_delete_stmt_37)),
                Opt(
                    Seq(self._r_opt_ws, self._r_where_clause).map(
                        self._action_delete_stmt_38
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_order_limit_clause).map(
                        self._action_delete_stmt_39
                    )
                ),
                Opt(
                    Seq(self._r_opt_ws, self._r_returning_clause).map(
                        self._action_delete_stmt_40
                    )
                ),
            ).map(self._action_delete_stmt_41)
        )
        self._r_where_clause.define(
            Seq(self._r_where_kw, self._r_ws, self._r_where_body_expr).map(
                self._action_where_clause_42
            )
        )
        self._r_where_body_expr.define(
            OneOrMore(self._r_where_chunk).map(self._action_where_body_expr_43)
        )
        self._r_where_chunk.define(
            Seq(NotPred(self._r_where_end), self._r_chunk_token, self._r_opt_ws).map(
                self._action_where_chunk_44
            )
        )
        self._r_where_end.define(
            Choice(self._r_order_kw, self._r_limit_kw, self._r_returning_kw, Lit(";"))
        )
        self._r_order_limit_clause.define(
            Seq(Opt(self._r_order_by_clause), Opt(self._r_limit_clause)).map(
                self._action_order_limit_clause_45
            )
        )
        self._r_order_by_clause.define(
            Seq(
                self._r_order_kw,
                self._r_ws,
                self._r_by_kw,
                self._r_ws,
                self._r_ident,
                Opt(
                    Seq(self._r_ws, self._r_order_dir).map(
                        self._action_order_by_clause_46
                    )
                ),
            ).map(self._action_order_by_clause_47)
        )
        self._r_order_dir.define(
            Choice(
                self._r_asc_kw.map(self._action_order_dir_48),
                self._r_desc_kw.map(self._action_order_dir_49),
            )
        )
        self._r_limit_clause.define(
            Seq(self._r_opt_ws, self._r_limit_kw, self._r_ws, self._r_integer_num).map(
                self._action_limit_clause_50
            )
        )
        self._r_returning_clause.define(
            Seq(self._r_returning_kw, self._r_ws, self._r_returning_item_list).map(
                self._action_returning_clause_51
            )
        )
        self._r_returning_item_list.define(
            Seq(
                self._r_returning_item,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_returning_item
                    ).map(self._action_returning_item_list_52)
                ),
            ).map(self._action_returning_item_list_53)
        )
        self._r_returning_item.define(
            Choice(
                Lit("*").map(self._action_returning_item_54),
                Reg("[a-zA-Z0-9_\\.]+(\\s+AS\\s+[a-zA-Z0-9_]+)?").map(
                    self._action_returning_item_55
                ),
            )
        )
        self._r_idx_hint.define(
            Choice(
                Seq(
                    self._r_indexed_kw,
                    self._r_ws,
                    self._r_by_kw,
                    self._r_ws,
                    self._r_ident,
                ).map(self._action_idx_hint_56),
                Seq(self._r_not_kw, self._r_ws, self._r_indexed_kw).map(
                    self._action_idx_hint_57
                ),
            )
        )
        self._r_ident_list.define(
            Seq(
                self._r_ident,
                ZeroOrMore(
                    Seq(self._r_opt_ws, Lit(","), self._r_opt_ws, self._r_ident).map(
                        self._action_ident_list_58
                    )
                ),
            ).map(self._action_ident_list_59)
        )
        self._r_ident.define(
            Choice(
                self._r_ident_pattern.map(self._action_ident_60),
                self._r_backtick_pattern.map(self._action_ident_61),
                self._r_double_quote_pattern.map(self._action_ident_62),
            )
        )
        self._r_ident_pattern.define(
            Reg("[a-zA-Z_][a-zA-Z0-9_]*(\\.[a-zA-Z_][a-zA-Z0-9_]*)?").map(
                self._action_ident_pattern_63
            )
        )
        self._r_backtick_pattern.define(
            Reg("`[^`]*`").map(self._action_backtick_pattern_64)
        )
        self._r_double_quote_pattern.define(
            Reg('"[^"]*"').map(self._action_double_quote_pattern_65)
        )
        self._r_non_reserved_ident.define(
            Seq(NotPred(self._r_reserved_kw), self._r_ident).map(
                self._action_non_reserved_ident_66
            )
        )
        self._r_reserved_kw.define(
            Choice(
                self._r_where_kw,
                self._r_order_kw,
                self._r_limit_kw,
                self._r_returning_kw,
                self._r_join_kw,
                self._r_from_kw,
                self._r_set_kw,
                self._r_on_kw,
            )
        )
        self._r_string_literal.define(
            Reg("'([^']|'')*'").map(self._action_string_literal_67)
        )
        self._r_double_quote_literal.define(
            Reg('"([^"\\\\]|\\\\.)*"').map(self._action_double_quote_literal_68)
        )
        self._r_bracket_token.define(
            Reg("\\[(?:[^\\[\\]]|\\[[^\\[\\]]*\\])*\\]").map(
                self._action_bracket_token_69
            )
        )
        self._r_chunk_token.define(
            Choice(
                self._r_func_call_token,
                self._r_paren_token,
                self._r_bracket_token,
                self._r_string_literal,
                self._r_double_quote_literal,
                self._r_non_ws_token,
            )
        )
        self._r_func_call_token.define(
            Seq(
                Reg("[a-zA-Z_][a-zA-Z0-9_]*"), Reg("\\s*\\((?:[^()]|\\([^()]*\\))*\\)")
            ).map(self._action_func_call_token_70)
        )
        self._r_paren_token.define(
            Reg("\\((?:[^()]|\\([^()]*\\))*\\)").map(self._action_paren_token_71)
        )
        self._r_non_ws_token.define(
            Reg("[^\\s,;()]+").map(self._action_non_ws_token_72)
        )
        self._r_integer_num.define(Reg("[0-9]+").map(self._action_integer_num_73))
        self._r_insert_kw.define(Reg("(?i)\\bINSERT\\b"))
        self._r_replace_kw.define(Reg("(?i)\\bREPLACE\\b"))
        self._r_into_kw.define(Reg("(?i)\\bINTO\\b"))
        self._r_update_kw.define(Reg("(?i)\\bUPDATE\\b"))
        self._r_delete_kw.define(Reg("(?i)\\bDELETE\\b"))
        self._r_from_kw.define(Reg("(?i)\\bFROM\\b"))
        self._r_set_kw.define(Reg("(?i)\\bSET\\b"))
        self._r_values_kw.define(Reg("(?i)\\bVALUES\\b"))
        self._r_where_kw.define(Reg("(?i)\\bWHERE\\b"))
        self._r_order_kw.define(Reg("(?i)\\bORDER\\b"))
        self._r_by_kw.define(Reg("(?i)\\bBY\\b"))
        self._r_limit_kw.define(Reg("(?i)\\bLIMIT\\b"))
        self._r_returning_kw.define(Reg("(?i)\\bRETURNING\\b"))
        self._r_on_kw.define(Reg("(?i)\\bON\\b"))
        self._r_conflict_kw.define(Reg("(?i)\\bCONFLICT\\b"))
        self._r_do_kw.define(Reg("(?i)\\bDO\\b"))
        self._r_nothing_kw.define(Reg("(?i)\\bNOTHING\\b"))
        self._r_indexed_kw.define(Reg("(?i)\\bINDEXED\\b"))
        self._r_not_kw.define(Reg("(?i)\\bNOT\\b"))
        self._r_or_kw.define(Reg("(?i)\\bOR\\b"))
        self._r_rollback_kw.define(Reg("(?i)\\bROLLBACK\\b"))
        self._r_abort_kw.define(Reg("(?i)\\bABORT\\b"))
        self._r_fail_kw.define(Reg("(?i)\\bFAIL\\b"))
        self._r_ignore_kw.define(Reg("(?i)\\bIGNORE\\b"))
        self._r_join_kw.define(Reg("(?i)\\bJOIN\\b"))
        self._r_asc_kw.define(Reg("(?i)\\bASC\\b"))
        self._r_desc_kw.define(Reg("(?i)\\bDESC\\b"))
        self._r_select_kw.define(Reg("(?i)\\bSELECT\\b"))
        self._r_ws.define(Reg("[ \\t\\r\\n]+|#[^\\r\\n]*|--[^\\r\\n]*"))
        self._r_opt_ws.define(Reg("[ \\t\\r\\n]*|#[^\\r\\n]*|--[^\\r\\n]*"))

        self.root_parser: Parser[Any] = self._r_root

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_root_0(val: Any) -> Any:
        dml = val[1]
        return dml

    @staticmethod
    def _action_insert_stmt_1(val: Any) -> Any:
        cl = val[3]
        return cl

    @staticmethod
    def _action_insert_stmt_2(val: Any) -> Any:
        u = val[1]
        return u

    @staticmethod
    def _action_insert_stmt_3(val: Any) -> Any:
        r = val[1]
        return r

    @staticmethod
    def _action_insert_stmt_4(val: Any) -> Any:
        hdr = val[0]
        tbl = val[2]
        cols = val[3]
        body = val[5]
        upsert = val[6]
        ret = val[7]
        return _assemble_insert_stmt(
            is_replace=hdr,
            table_name=tbl,
            cols=cols,
            body=body,
            upsert_info=upsert,
            ret_cols=ret,
        )

    @staticmethod
    def _action_insert_header_5(val: Any) -> Any:
        return True

    @staticmethod
    def _action_insert_header_6(val: Any) -> Any:
        return True

    @staticmethod
    def _action_insert_header_7(val: Any) -> Any:
        return False

    @staticmethod
    def _action_values_clause_8(val: Any) -> Any:
        rows = val[2]
        return rows

    @staticmethod
    def _action_values_rows_9(val: Any) -> Any:
        r = val[3]
        return r

    @staticmethod
    def _action_values_rows_10(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_value_row_11(val: Any) -> Any:
        a = val[3]
        return a

    @staticmethod
    def _action_value_row_12(val: Any) -> Any:
        first = val[2]
        rest = val[3]
        return [first] + rest

    @staticmethod
    def _action_value_atom_13(val: Any) -> Any:
        raw = val[0]
        return _resolve_raw_literal(raw)

    @staticmethod
    def _action_select_insert_body_14(val: Any) -> Any:
        raw = val
        return parse_dql(raw)

    @staticmethod
    def _action_select_raw_text_15(val: Any) -> Any:
        parts = val[2]
        return "SELECT " + " ".join(parts).strip()

    @staticmethod
    def _action_select_chunk_16(val: Any) -> Any:
        raw = val[1]
        return raw

    @staticmethod
    def _action_upsert_clause_17(val: Any) -> Any:
        tl = val[3]
        return tl

    @staticmethod
    def _action_upsert_clause_18(val: Any) -> Any:
        tgt = val[3]
        act = val[8]
        return (tgt, act[0], act[1])

    @staticmethod
    def _action_upsert_action_19(val: Any) -> Any:
        return ("NOTHING", {})

    @staticmethod
    def _action_upsert_action_20(val: Any) -> Any:
        sets = val[4]
        return ("UPDATE", sets[0])

    @staticmethod
    def _action_update_stmt_21(val: Any) -> Any:
        h = val[1]
        return h

    @staticmethod
    def _action_update_stmt_22(val: Any) -> Any:
        f = val[1]
        return f

    @staticmethod
    def _action_update_stmt_23(val: Any) -> Any:
        w = val[1]
        return w

    @staticmethod
    def _action_update_stmt_24(val: Any) -> Any:
        ol = val[1]
        return ol

    @staticmethod
    def _action_update_stmt_25(val: Any) -> Any:
        r = val[1]
        return r

    @staticmethod
    def _action_update_stmt_26(val: Any) -> Any:
        tbl = val[3]
        hint = val[4]
        sets = val[8]
        from_p = val[9]
        where_p = val[10]
        ord_lim = val[11]
        ret = val[12]
        return _assemble_update_stmt(
            tbl_name=tbl,
            hint=hint,
            sets=sets,
            from_info=from_p,
            where_raw=where_p,
            ord_lim=ord_lim,
            ret_cols=ret,
        )

    @staticmethod
    def _action_set_assignment_list_27(val: Any) -> Any:
        next_i = val[3]
        return next_i

    @staticmethod
    def _action_set_assignment_list_28(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        static_map: Dict[str, Any] = {}
        raw_map: Dict[str, str] = {}
        for col, val, raw_expr in [first] + rest:
            static_map[col] = val
            raw_map[col] = raw_expr
        return (static_map, raw_map)

    @staticmethod
    def _action_set_item_29(val: Any) -> Any:
        col = val[0]
        expr = val[4]
        return (col, _resolve_raw_literal(expr), expr)

    @staticmethod
    def _action_set_expr_30(val: Any) -> Any:
        parts = val
        return " ".join(parts).strip()

    @staticmethod
    def _action_set_chunk_31(val: Any) -> Any:
        raw = val[1]
        return raw

    @staticmethod
    def _action_update_from_clause_32(val: Any) -> Any:
        a = val[1]
        return a

    @staticmethod
    def _action_update_from_clause_33(val: Any) -> Any:
        j = val[1]
        return j

    @staticmethod
    def _action_update_from_clause_34(val: Any) -> Any:
        tbl = val[2]
        opt_alias = val[3]
        joins = val[4]
        t_ref = TableRef(name=tbl, alias=opt_alias)
        return (t_ref, joins)

    @staticmethod
    def _action_join_spec_35(val: Any) -> Any:
        a = val[1]
        return a

    @staticmethod
    def _action_join_spec_36(val: Any) -> Any:
        tbl = val[2]
        opt_alias = val[3]
        t_ref = TableRef(name=tbl, alias=opt_alias)
        return JoinClause(
            join_type=JoinType.INNER,
            table=t_ref,
            on_conditions=[],
        )

    @staticmethod
    def _action_delete_stmt_37(val: Any) -> Any:
        h = val[1]
        return h

    @staticmethod
    def _action_delete_stmt_38(val: Any) -> Any:
        w = val[1]
        return w

    @staticmethod
    def _action_delete_stmt_39(val: Any) -> Any:
        ol = val[1]
        return ol

    @staticmethod
    def _action_delete_stmt_40(val: Any) -> Any:
        r = val[1]
        return r

    @staticmethod
    def _action_delete_stmt_41(val: Any) -> Any:
        tbl = val[4]
        hint = val[5]
        where_p = val[6]
        ord_lim = val[7]
        ret = val[8]
        return _assemble_delete_stmt(
            tbl_name=tbl,
            hint=hint,
            where_raw=where_p,
            ord_lim=ord_lim,
            ret_cols=ret,
        )

    @staticmethod
    def _action_where_clause_42(val: Any) -> Any:
        body = val[2]
        return body

    @staticmethod
    def _action_where_body_expr_43(val: Any) -> Any:
        parts = val
        return " ".join(parts).strip()

    @staticmethod
    def _action_where_chunk_44(val: Any) -> Any:
        raw = val[1]
        return raw

    @staticmethod
    def _action_order_limit_clause_45(val: Any) -> Any:
        ord = val[0]
        lim = val[1]
        order_col = ord[0] if ord else None
        order_desc = ord[1] if ord else False
        limit_val = lim if lim is not None else None
        return (order_col, order_desc, limit_val)

    @staticmethod
    def _action_order_by_clause_46(val: Any) -> Any:
        d = val[1]
        return d

    @staticmethod
    def _action_order_by_clause_47(val: Any) -> Any:
        col = val[4]
        dir = val[5]
        is_desc = (dir == "DESC") if dir else False
        return (col, is_desc)

    @staticmethod
    def _action_order_dir_48(val: Any) -> Any:
        return "ASC"

    @staticmethod
    def _action_order_dir_49(val: Any) -> Any:
        return "DESC"

    @staticmethod
    def _action_limit_clause_50(val: Any) -> Any:
        num = val[3]
        return num

    @staticmethod
    def _action_returning_clause_51(val: Any) -> Any:
        items = val[2]
        return items

    @staticmethod
    def _action_returning_item_list_52(val: Any) -> Any:
        next_i = val[3]
        return next_i

    @staticmethod
    def _action_returning_item_list_53(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_returning_item_54(val: Any) -> Any:
        return "*"

    @staticmethod
    def _action_returning_item_55(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_idx_hint_56(val: Any) -> Any:
        name = val[4]
        return (name, False)

    @staticmethod
    def _action_idx_hint_57(val: Any) -> Any:
        return (None, True)

    @staticmethod
    def _action_ident_list_58(val: Any) -> Any:
        next_i = val[3]
        return next_i

    @staticmethod
    def _action_ident_list_59(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_ident_60(val: Any) -> Any:
        plain = val
        return plain

    @staticmethod
    def _action_ident_61(val: Any) -> Any:
        backtick = val
        return backtick

    @staticmethod
    def _action_ident_62(val: Any) -> Any:
        double_quote = val
        return double_quote

    @staticmethod
    def _action_ident_pattern_63(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_backtick_pattern_64(val: Any) -> Any:
        raw = val
        return raw[1:-1]

    @staticmethod
    def _action_double_quote_pattern_65(val: Any) -> Any:
        raw = val
        return raw[1:-1]

    @staticmethod
    def _action_non_reserved_ident_66(val: Any) -> Any:
        id = val[1]
        return id

    @staticmethod
    def _action_string_literal_67(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_double_quote_literal_68(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_bracket_token_69(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_func_call_token_70(val: Any) -> Any:
        fn = val[0]
        args = val[1]
        return f"{fn}{args}"

    @staticmethod
    def _action_paren_token_71(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_non_ws_token_72(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_integer_num_73(val: Any) -> Any:
        raw = val
        return int(raw)
