#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: SearchQuery
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

from typing import Any

from core.structures.peg import (
    Choice,
    Class,
    Lit,
    NotPred,
    OneOrMore,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
    ZeroOrMore,
)
from search.query.query_parser import (
    QueryClause,
    _apply_search_field,
    _apply_search_modifier,
    _create_search_phrase,
    _fold_search_disjunction,
    _parse_search_plain_term,
    _resolve_search_field,
)

# User header code


class SearchQueryParser(Parser[Any]):
    """Packrat PEG Parser for SearchQuery grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_query = RuleRef("query")
        self._r_disjunction = RuleRef("disjunction")
        self._r_or_op = RuleRef("or_op")
        self._r_conjunction = RuleRef("conjunction")
        self._r_sep = RuleRef("sep")
        self._r_and_op = RuleRef("and_op")
        self._r_factor = RuleRef("factor")
        self._r_modifier = RuleRef("modifier")
        self._r_not_kw = RuleRef("not_kw")
        self._r_primary = RuleRef("primary")
        self._r_field_expr = RuleRef("field_expr")
        self._r_field_name = RuleRef("field_name")
        self._r_field_target = RuleRef("field_target")
        self._r_nested_parens = RuleRef("nested_parens")
        self._r_phrase_expr = RuleRef("phrase_expr")
        self._r_slop_suffix = RuleRef("slop_suffix")
        self._r_plain_expr = RuleRef("plain_expr")
        self._r_reserved_kw = RuleRef("reserved_kw")
        self._r_ws = RuleRef("ws")
        self._r_opt_ws = RuleRef("opt_ws")

        self._r_query.define(
            Seq(self._r_opt_ws, self._r_disjunction, self._r_opt_ws).map(
                self._action_query_0
            )
        )
        self._r_disjunction.define(
            Seq(
                self._r_conjunction,
                ZeroOrMore(
                    Seq(
                        self._r_opt_ws, self._r_or_op, self._r_ws, self._r_conjunction
                    ).map(self._action_disjunction_1)
                ),
            ).map(self._action_disjunction_2)
        )
        self._r_or_op.define(Reg("(?i)\\bOR\\b|\\|\\|?"))
        self._r_conjunction.define(
            Seq(
                self._r_factor,
                ZeroOrMore(
                    Seq(self._r_sep, self._r_factor).map(self._action_conjunction_3)
                ),
            ).map(self._action_conjunction_4)
        )
        self._r_sep.define(Choice(self._r_and_op, self._r_ws))
        self._r_and_op.define(Seq(self._r_opt_ws, Reg("(?i)\\bAND\\b|&&?"), self._r_ws))
        self._r_factor.define(
            Seq(Opt(self._r_modifier), self._r_primary).map(self._action_factor_5)
        )
        self._r_modifier.define(
            Choice(
                Lit("+").map(self._action_modifier_6),
                Lit("-").map(self._action_modifier_7),
                self._r_not_kw.map(self._action_modifier_8),
            )
        )
        self._r_not_kw.define(
            Seq(Reg("(?i)\\bNOT\\b"), self._r_ws).map(self._action_not_kw_9)
        )
        self._r_primary.define(
            Choice(
                self._r_field_expr,
                self._r_phrase_expr,
                self._r_plain_expr,
                self._r_nested_parens.map(self._action_primary_10),
            )
        )
        self._r_field_expr.define(
            Seq(self._r_field_name, Lit(":"), self._r_field_target).map(
                self._action_field_expr_11
            )
        )
        self._r_field_name.define(
            OneOrMore(Class("a-zA-Z_", inverted=False)).map(self._action_field_name_12)
        )
        self._r_field_target.define(
            Choice(self._r_nested_parens, self._r_phrase_expr, self._r_plain_expr)
        )
        self._r_nested_parens.define(
            Seq(
                Lit("("), self._r_opt_ws, self._r_disjunction, self._r_opt_ws, Lit(")")
            ).map(self._action_nested_parens_13)
        )
        self._r_phrase_expr.define(
            Seq(
                Lit('"'),
                ZeroOrMore(Class('"', inverted=True)),
                Lit('"'),
                Opt(self._r_slop_suffix),
            ).map(self._action_phrase_expr_14)
        )
        self._r_slop_suffix.define(
            Seq(Lit("~"), OneOrMore(Class("0-9", inverted=False))).map(
                self._action_slop_suffix_15
            )
        )
        self._r_plain_expr.define(
            Seq(
                NotPred(self._r_reserved_kw),
                OneOrMore(Class(' \\t\\r\\n"():', inverted=True)),
            ).map(self._action_plain_expr_16)
        )
        self._r_reserved_kw.define(Reg("(?i)\\b(AND|OR|NOT)\\b"))
        self._r_ws.define(OneOrMore(Class(" \\t\\r\\n", inverted=False)))
        self._r_opt_ws.define(ZeroOrMore(Class(" \\t\\r\\n", inverted=False)))

        self.root_parser: Parser[Any] = self._r_query

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_query_0(val: Any) -> Any:
        e = val[1]
        return e

    @staticmethod
    def _action_disjunction_1(val: Any) -> Any:
        conj = val[3]
        return conj

    @staticmethod
    def _action_disjunction_2(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        if not rest:
            return first
        return _fold_search_disjunction(first, rest)

    @staticmethod
    def _action_conjunction_3(val: Any) -> Any:
        next_fac = val[1]
        return next_fac

    @staticmethod
    def _action_conjunction_4(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        clauses = [first] if first else []
        for r in rest:
            if r:
                clauses.append(r)
        return clauses

    @staticmethod
    def _action_factor_5(val: Any) -> Any:
        mod = val[0]
        prim = val[1]
        return _apply_search_modifier(mod, prim)

    @staticmethod
    def _action_modifier_6(val: Any) -> Any:
        return "+"

    @staticmethod
    def _action_modifier_7(val: Any) -> Any:
        return "-"

    @staticmethod
    def _action_modifier_8(val: Any) -> Any:
        return "-"

    @staticmethod
    def _action_not_kw_9(val: Any) -> Any:
        return "-"

    @staticmethod
    def _action_primary_10(val: Any) -> Any:
        parens = val
        if isinstance(parens, list):
            return parens[0] if len(parens) == 1 else QueryClause(nested_clauses=parens)
        return parens

    @staticmethod
    def _action_field_expr_11(val: Any) -> Any:
        fld = val[0]
        target = val[2]
        resolved = _resolve_search_field(fld)
        return _apply_search_field(resolved, target)

    @staticmethod
    def _action_field_name_12(val: Any) -> Any:
        raw = val
        return "".join(raw)

    @staticmethod
    def _action_nested_parens_13(val: Any) -> Any:
        e = val[2]
        return e

    @staticmethod
    def _action_phrase_expr_14(val: Any) -> Any:
        s = val[1]
        slop = val[3]
        slop_val = int(slop) if slop else 0
        return _create_search_phrase("".join(s), slop_val)

    @staticmethod
    def _action_slop_suffix_15(val: Any) -> Any:
        n = val[1]
        return "".join(n)

    @staticmethod
    def _action_plain_expr_16(val: Any) -> Any:
        word = val[1]
        return _parse_search_plain_term("".join(word))
