#!/usr/bin/env python3
"""
Security Knowledge Ontology (SKO) Package.
Provides standardized entity schemas, relationship predicates, taxonomy mappings,
and fact triple extraction.
"""

from .core import (
    ASTNode,
    ASTVisitor,
    AxiomNode,
    ClassDeclaration,
    ClassNode,
    DatatypePropertyField,
    DatatypePropertyNode,
    Diagnostic,
    DiagnosticSeverity,
    InstanceNode,
    MetadataNode,
    ObjectPropertyField,
    ObjectPropertyNode,
    OntologyDocumentNode,
    OntologyInterpreter,
    OntologyParser,
    SemanticValidator,
    TurtleCodeGenerator,
    ontology_class,
)
from .extractor import OntologyExtractor
from .rule_registry import EdgeInferenceRuleRegistry
from .rule_schema import (
    ConfidenceTier,
    EdgeInferenceRule,
    EvidenceExtractionSpec,
    RuleConditionType,
)
from .schema import (
    AttackTechniqueEntity,
    BaseEntity,
    BenchmarkMetricEntity,
    DefenseMechanismEntity,
    DetectionRuleEntity,
    EntityType,
    IncidentEntity,
    PaperEntity,
    PoCArtifactEntity,
    PreconditionEntity,
    Predicate,
    PublicationVenueEntity,
    ResearchGapEntity,
    ResidualRiskEntity,
    SecurityOntologySchema,
    TargetAssetEntity,
    ThreatActorEntity,
    Triple,
    VulnerabilityEntity,
)
from .security import (
    ALL_SECURITY_CLASSES,
    SECURITY_PREFIXES,
    build_security_ontology_ast,
    export_security_ontology_turtle,
)
from .taxonomy import TaxonomyRegistry
from .turtle_engine import (
    URI,
    DatatypeProperty,
    Literal,
    ObjectProperty,
    OntologyClass,
    OntologyInstance,
    OntologyMetadata,
    RawTriple,
    RDFTerm,
    TurtleDocumentBuilder,
    build_full_spectrum_security_ontology,
    build_sample_enterprise_ontology,
    build_security_cti_ontology,
)

__all__ = [
    "EntityType",
    "Predicate",
    "BaseEntity",
    "PaperEntity",
    "ThreatActorEntity",
    "AttackTechniqueEntity",
    "VulnerabilityEntity",
    "TargetAssetEntity",
    "DefenseMechanismEntity",
    "BenchmarkMetricEntity",
    "IncidentEntity",
    "DetectionRuleEntity",
    "PoCArtifactEntity",
    "PreconditionEntity",
    "ResearchGapEntity",
    "ResidualRiskEntity",
    "PublicationVenueEntity",
    "Triple",
    "SecurityOntologySchema",
    "TaxonomyRegistry",
    "OntologyExtractor",
    "RuleConditionType",
    "ConfidenceTier",
    "EvidenceExtractionSpec",
    "EdgeInferenceRule",
    "EdgeInferenceRuleRegistry",
    "RDFTerm",
    "URI",
    "Literal",
    "OntologyMetadata",
    "OntologyClass",
    "ObjectProperty",
    "DatatypeProperty",
    "OntologyInstance",
    "RawTriple",
    "TurtleDocumentBuilder",
    "build_sample_enterprise_ontology",
    "build_security_cti_ontology",
    "build_full_spectrum_security_ontology",
    # Core AST & Interpreter
    "ASTNode",
    "ClassNode",
    "ObjectPropertyNode",
    "DatatypePropertyNode",
    "AxiomNode",
    "InstanceNode",
    "MetadataNode",
    "OntologyDocumentNode",
    "ontology_class",
    "ObjectPropertyField",
    "DatatypePropertyField",
    "ClassDeclaration",
    "OntologyParser",
    "Diagnostic",
    "DiagnosticSeverity",
    "SemanticValidator",
    "ASTVisitor",
    "OntologyInterpreter",
    "TurtleCodeGenerator",
    # Security DSL & Model
    "ALL_SECURITY_CLASSES",
    "SECURITY_PREFIXES",
    "build_security_ontology_ast",
    "export_security_ontology_turtle",
]
