#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: Turtle
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

from typing import Any

from core.structures.peg import (
    Choice,
    Lit,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
    ZeroOrMore,
)
from ontology.turtle_parser import (
    RDF_TYPE_IRI,
    TurtleDocument,
    TurtleTerm,
    _apply_turtle_statement,
    _extract_datatype_uri,
    _unescape_turtle_str,
)

# User header code


class TurtleParser(Parser[Any]):
    """Packrat PEG Parser for Turtle grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_document = RuleRef("document")
        self._r_statement = RuleRef("statement")
        self._r_directive = RuleRef("directive")
        self._r_at_prefix = RuleRef("at_prefix")
        self._r_sparql_prefix = RuleRef("sparql_prefix")
        self._r_at_base = RuleRef("at_base")
        self._r_sparql_base = RuleRef("sparql_base")
        self._r_prefix_id = RuleRef("prefix_id")
        self._r_iri_val = RuleRef("iri_val")
        self._r_triple_stmt = RuleRef("triple_stmt")
        self._r_subject = RuleRef("subject")
        self._r_predicate = RuleRef("predicate")
        self._r_object = RuleRef("object")
        self._r_po_list = RuleRef("po_list")
        self._r_po_pair = RuleRef("po_pair")
        self._r_object_list = RuleRef("object_list")
        self._r_iri_term = RuleRef("iri_term")
        self._r_full_iri = RuleRef("full_iri")
        self._r_prefixed_name = RuleRef("prefixed_name")
        self._r_a_kw = RuleRef("a_kw")
        self._r_bnode_term = RuleRef("bnode_term")
        self._r_named_bnode = RuleRef("named_bnode")
        self._r_anon_bnode = RuleRef("anon_bnode")
        self._r_literal_term = RuleRef("literal_term")
        self._r_quoted_str = RuleRef("quoted_str")
        self._r_full_str_lit = RuleRef("full_str_lit")
        self._r_str_suffix = RuleRef("str_suffix")
        self._r_lang_suffix = RuleRef("lang_suffix")
        self._r_dt_suffix = RuleRef("dt_suffix")
        self._r_curie_dt = RuleRef("curie_dt")
        self._r_bool_lit = RuleRef("bool_lit")
        self._r_float_lit = RuleRef("float_lit")
        self._r_int_lit = RuleRef("int_lit")
        self._r_ws = RuleRef("ws")

        self._r_document.define(
            Seq(self._r_ws, ZeroOrMore(self._r_statement), self._r_ws).map(
                self._action_document_0
            )
        )
        self._r_statement.define(
            Choice(self._r_directive, self._r_triple_stmt).map(self._action_statement_1)
        )
        self._r_directive.define(
            Choice(
                self._r_at_prefix,
                self._r_sparql_prefix,
                self._r_at_base,
                self._r_sparql_base,
            )
        )
        self._r_at_prefix.define(
            Seq(
                Lit("@prefix"),
                self._r_ws,
                self._r_prefix_id,
                self._r_ws,
                self._r_iri_val,
                self._r_ws,
                Lit("."),
                self._r_ws,
            ).map(self._action_at_prefix_2)
        )
        self._r_sparql_prefix.define(
            Seq(
                Lit("PREFIX"),
                self._r_ws,
                self._r_prefix_id,
                self._r_ws,
                self._r_iri_val,
                self._r_ws,
                Opt(Seq(Lit("."), self._r_ws)),
            ).map(self._action_sparql_prefix_3)
        )
        self._r_at_base.define(
            Seq(
                Lit("@base"),
                self._r_ws,
                self._r_iri_val,
                self._r_ws,
                Lit("."),
                self._r_ws,
            ).map(self._action_at_base_4)
        )
        self._r_sparql_base.define(
            Seq(
                Lit("BASE"),
                self._r_ws,
                self._r_iri_val,
                self._r_ws,
                Opt(Seq(Lit("."), self._r_ws)),
            ).map(self._action_sparql_base_5)
        )
        self._r_prefix_id.define(Reg("[a-zA-Z0-9_-]*:").map(self._action_prefix_id_6))
        self._r_iri_val.define(
            Seq(Lit("<"), Reg("[^>]*"), Lit(">")).map(self._action_iri_val_7)
        )
        self._r_triple_stmt.define(
            Seq(
                self._r_subject,
                self._r_ws,
                self._r_po_list,
                self._r_ws,
                Lit("."),
                self._r_ws,
            ).map(self._action_triple_stmt_8)
        )
        self._r_subject.define(Choice(self._r_iri_term, self._r_bnode_term))
        self._r_predicate.define(self._r_iri_term)
        self._r_object.define(
            Choice(self._r_iri_term, self._r_bnode_term, self._r_literal_term)
        )
        self._r_po_list.define(
            Seq(
                self._r_po_pair,
                ZeroOrMore(
                    Seq(self._r_ws, Lit(";"), self._r_ws, self._r_po_pair).map(
                        self._action_po_list_9
                    )
                ),
                Opt(Seq(self._r_ws, Lit(";"))),
            ).map(self._action_po_list_10)
        )
        self._r_po_pair.define(
            Seq(self._r_predicate, self._r_ws, self._r_object_list).map(
                self._action_po_pair_11
            )
        )
        self._r_object_list.define(
            Seq(
                self._r_object,
                ZeroOrMore(
                    Seq(self._r_ws, Lit(","), self._r_ws, self._r_object).map(
                        self._action_object_list_12
                    )
                ),
            ).map(self._action_object_list_13)
        )
        self._r_iri_term.define(
            Choice(self._r_full_iri, self._r_prefixed_name, self._r_a_kw)
        )
        self._r_full_iri.define(
            Seq(Lit("<"), Reg("[^>]*"), Lit(">"), self._r_ws).map(
                self._action_full_iri_14
            )
        )
        self._r_prefixed_name.define(
            Seq(
                Reg("[a-zA-Z0-9_-]*"), Lit(":"), Reg("[a-zA-Z0-9_.\\-%]+"), self._r_ws
            ).map(self._action_prefixed_name_15)
        )
        self._r_a_kw.define(Seq(Lit("a"), self._r_ws).map(self._action_a_kw_16))
        self._r_bnode_term.define(Choice(self._r_named_bnode, self._r_anon_bnode))
        self._r_named_bnode.define(
            Seq(Reg("_:[a-zA-Z0-9_.-]+"), self._r_ws).map(self._action_named_bnode_17)
        )
        self._r_anon_bnode.define(
            Seq(Lit("["), self._r_ws, Lit("]"), self._r_ws).map(
                self._action_anon_bnode_18
            )
        )
        self._r_literal_term.define(
            Choice(
                self._r_full_str_lit,
                self._r_bool_lit,
                self._r_float_lit,
                self._r_int_lit,
            )
        )
        self._r_quoted_str.define(
            Choice(
                Seq(Lit('"'), Reg('(?:[^"\\\\]|\\\\.)*'), Lit('"')).map(
                    self._action_quoted_str_19
                ),
                Seq(Lit("'"), Reg("(?:[^'\\\\]|\\\\.)*"), Lit("'")).map(
                    self._action_quoted_str_20
                ),
            )
        )
        self._r_full_str_lit.define(
            Seq(self._r_quoted_str, Opt(self._r_str_suffix), self._r_ws).map(
                self._action_full_str_lit_21
            )
        )
        self._r_str_suffix.define(Choice(self._r_lang_suffix, self._r_dt_suffix))
        self._r_lang_suffix.define(
            Seq(Lit("@"), Reg("[a-zA-Z]+(-[a-zA-Z0-9]+)*")).map(
                self._action_lang_suffix_22
            )
        )
        self._r_dt_suffix.define(
            Seq(Lit("^^"), Choice(self._r_iri_val, self._r_curie_dt)).map(
                self._action_dt_suffix_23
            )
        )
        self._r_curie_dt.define(
            Seq(Reg("[a-zA-Z0-9_.-]*"), Lit(":"), Reg("[a-zA-Z0-9_.-]+")).map(
                self._action_curie_dt_24
            )
        )
        self._r_bool_lit.define(
            Seq(Choice(Lit("true"), Lit("false")), self._r_ws).map(
                self._action_bool_lit_25
            )
        )
        self._r_float_lit.define(
            Seq(Reg("[+-]?[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?"), self._r_ws).map(
                self._action_float_lit_26
            )
        )
        self._r_int_lit.define(
            Seq(Reg("[+-]?[0-9]+"), self._r_ws).map(self._action_int_lit_27)
        )
        self._r_ws.define(Reg("(?:\\s+|#[^\\r\\n]*)*"))

        self.root_parser: Parser[Any] = self._r_document

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_document_0(val: Any) -> Any:
        stmts = val[1]
        doc = TurtleDocument()
        for stmt in stmts:
            if stmt:
                _apply_turtle_statement(doc, stmt)
        return doc

    @staticmethod
    def _action_statement_1(val: Any) -> Any:
        s = val
        return s

    @staticmethod
    def _action_at_prefix_2(val: Any) -> Any:
        p = val[2]
        u = val[4]
        return ("prefix", p[:-1], u)

    @staticmethod
    def _action_sparql_prefix_3(val: Any) -> Any:
        p = val[2]
        u = val[4]
        return ("prefix", p[:-1], u)

    @staticmethod
    def _action_at_base_4(val: Any) -> Any:
        u = val[2]
        return ("base", "", u)

    @staticmethod
    def _action_sparql_base_5(val: Any) -> Any:
        u = val[2]
        return ("base", "", u)

    @staticmethod
    def _action_prefix_id_6(val: Any) -> Any:
        id_str = val
        return id_str

    @staticmethod
    def _action_iri_val_7(val: Any) -> Any:
        raw = val[1]
        return raw

    @staticmethod
    def _action_triple_stmt_8(val: Any) -> Any:
        s = val[0]
        po = val[2]
        return ("triples", str(s.value), po)

    @staticmethod
    def _action_po_list_9(val: Any) -> Any:
        next_pair = val[3]
        return next_pair

    @staticmethod
    def _action_po_list_10(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        res = [first]
        if rest:
            res.extend(rest)
        return res

    @staticmethod
    def _action_po_pair_11(val: Any) -> Any:
        pred = val[0]
        objs = val[2]
        return (str(pred.value), objs)

    @staticmethod
    def _action_object_list_12(val: Any) -> Any:
        next_obj = val[3]
        return next_obj

    @staticmethod
    def _action_object_list_13(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        res = [first]
        if rest:
            res.extend(rest)
        return res

    @staticmethod
    def _action_full_iri_14(val: Any) -> Any:
        u = val[1]
        return TurtleTerm(u, "iri")

    @staticmethod
    def _action_prefixed_name_15(val: Any) -> Any:
        p = val[0]
        loc = val[2]
        return TurtleTerm(f"{p}:{loc}", "iri")

    @staticmethod
    def _action_a_kw_16(val: Any) -> Any:
        return TurtleTerm(RDF_TYPE_IRI, "iri")

    @staticmethod
    def _action_named_bnode_17(val: Any) -> Any:
        b = val[0]
        return TurtleTerm(b, "bnode")

    @staticmethod
    def _action_anon_bnode_18(val: Any) -> Any:
        return TurtleTerm("_:bnode_anon", "bnode")

    @staticmethod
    def _action_quoted_str_19(val: Any) -> Any:
        s = val[1]
        return s

    @staticmethod
    def _action_quoted_str_20(val: Any) -> Any:
        s = val[1]
        return s

    @staticmethod
    def _action_full_str_lit_21(val: Any) -> Any:
        s = val[0]
        suf = val[1]
        raw_text = _unescape_turtle_str(s)
        if not suf:
            return TurtleTerm(raw_text, "literal")
        tag, val = suf
        if tag == "@":
            return TurtleTerm(raw_text, "literal", language=str(val))
        if tag == "^^":
            return TurtleTerm(raw_text, "literal", datatype=_extract_datatype_uri(val))
        return TurtleTerm(raw_text, "literal")

    @staticmethod
    def _action_lang_suffix_22(val: Any) -> Any:
        lang = val[1]
        return ("@", lang)

    @staticmethod
    def _action_dt_suffix_23(val: Any) -> Any:
        dt = val[1]
        return ("^^", dt)

    @staticmethod
    def _action_curie_dt_24(val: Any) -> Any:
        p = val[0]
        loc = val[2]
        return f"{p}:{loc}"

    @staticmethod
    def _action_bool_lit_25(val: Any) -> Any:
        b = val[0]
        return TurtleTerm(
            b == "true", "literal", datatype="http://www.w3.org/2001/XMLSchema#boolean"
        )

    @staticmethod
    def _action_float_lit_26(val: Any) -> Any:
        num = val[0]
        return TurtleTerm(
            float(num), "literal", datatype="http://www.w3.org/2001/XMLSchema#decimal"
        )

    @staticmethod
    def _action_int_lit_27(val: Any) -> Any:
        num = val[0]
        return TurtleTerm(
            int(num), "literal", datatype="http://www.w3.org/2001/XMLSchema#integer"
        )
