#!/usr/bin/env python3
"""
Core Search Engine Package (Lucene Paradigm).
Embedded, zero-dependency IR engine providing Analysis, Inverted Index, VByte Compression,
BM25 Scoring, Complex Queries (Boolean, Phrase, Wildcard, Fuzzy, Boost), SpellChecker, and Sorter.
"""

from . import analysis, index, search, store
from .analysis import (
    Analyzer,
    CharFilter,
    CJKAnalyzer,
    CJKBigramTokenizer,
    HTMLStripCharFilter,
    LowerCaseFilter,
    MappingCharFilter,
    PorterStemFilter,
    StandardAnalyzer,
    StandardTokenizer,
    StopFilter,
    SynonymFilter,
    TokenFilter,
    Tokenizer,
)
from .index import (
    DeletedDocsBitset,
    DocValues,
    PostingEntry,
    PostingsList,
    Segment,
    StoredFields,
    TieredMergePolicy,
    decode_gap_vbyte,
    decode_vbyte,
    encode_gap_vbyte,
    encode_vbyte,
)
from .search import (
    BM25Similarity,
    BooleanClause,
    BooleanQuery,
    BoostQuery,
    FuzzyQuery,
    MatchAllDocsQuery,
    Occur,
    PhraseQuery,
    Query,
    ScoreDoc,
    Similarity,
    Sorter,
    SortField,
    SortOrder,
    SpellChecker,
    TermQuery,
    TopDocs,
    TopDocsCollector,
    WildcardQuery,
)
from .store import Directory, FSDirectory, IndexInput, IndexOutput, RAMDirectory

__all__ = [
    # Subpackages
    "analysis",
    "index",
    "search",
    "store",
    # Analysis
    "CharFilter",
    "HTMLStripCharFilter",
    "MappingCharFilter",
    "Tokenizer",
    "StandardTokenizer",
    "CJKBigramTokenizer",
    "TokenFilter",
    "LowerCaseFilter",
    "StopFilter",
    "PorterStemFilter",
    "SynonymFilter",
    "Analyzer",
    "StandardAnalyzer",
    "CJKAnalyzer",
    # Index & Compression
    "encode_vbyte",
    "decode_vbyte",
    "encode_gap_vbyte",
    "decode_gap_vbyte",
    "PostingEntry",
    "PostingsList",
    "DocValues",
    "StoredFields",
    "DeletedDocsBitset",
    "Segment",
    "TieredMergePolicy",
    # Search & Queries
    "Similarity",
    "BM25Similarity",
    "Occur",
    "Query",
    "BoostQuery",
    "MatchAllDocsQuery",
    "TermQuery",
    "PhraseQuery",
    "WildcardQuery",
    "FuzzyQuery",
    "BooleanClause",
    "BooleanQuery",
    "SpellChecker",
    "SortOrder",
    "SortField",
    "Sorter",
    "ScoreDoc",
    "TopDocs",
    "TopDocsCollector",
    # Storage
    "IndexOutput",
    "IndexInput",
    "Directory",
    "RAMDirectory",
    "FSDirectory",
]
