#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: PDFCMap
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

from typing import Any

from core.structures.peg import (
    Choice,
    Class,
    Lit,
    NotPred,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
    ZeroOrMore,
)
from pdf_engine.cmap_helpers import (
    _build_cmap_mapping,
    _decode_bfchar_pair,
    _decode_bfrange_array,
    _decode_bfrange_single,
)

# User header code


class PDFCMapParser(Parser[Any]):
    """Packrat PEG Parser for PDFCMap grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_cmap_file = RuleRef("cmap_file")
        self._r_cmap_item = RuleRef("cmap_item")
        self._r_bfchar_block = RuleRef("bfchar_block")
        self._r_opt_count = RuleRef("opt_count")
        self._r_bfchar_pair = RuleRef("bfchar_pair")
        self._r_bfrange_block = RuleRef("bfrange_block")
        self._r_bfrange_entry = RuleRef("bfrange_entry")
        self._r_bfrange_single_entry = RuleRef("bfrange_single_entry")
        self._r_bfrange_array_entry = RuleRef("bfrange_array_entry")
        self._r_hex_string = RuleRef("hex_string")
        self._r_dict_delim = RuleRef("dict_delim")
        self._r_any_hex_chunk = RuleRef("any_hex_chunk")
        self._r_other_token = RuleRef("other_token")
        self._r_token_chars = RuleRef("token_chars")
        self._r_integer = RuleRef("integer")
        self._r_beginbfchar_kw = RuleRef("beginbfchar_kw")
        self._r_endbfchar_kw = RuleRef("endbfchar_kw")
        self._r_beginbfrange_kw = RuleRef("beginbfrange_kw")
        self._r_endbfrange_kw = RuleRef("endbfrange_kw")
        self._r_ws = RuleRef("ws")
        self._r_ws_char = RuleRef("ws_char")

        self._r_cmap_file.define(
            Seq(
                self._r_ws,
                ZeroOrMore(
                    Seq(self._r_cmap_item, self._r_ws).map(self._action_cmap_file_0)
                ),
            ).map(self._action_cmap_file_1)
        )
        self._r_cmap_item.define(
            Choice(
                self._r_bfchar_block,
                self._r_bfrange_block,
                self._r_dict_delim,
                self._r_any_hex_chunk,
                self._r_other_token,
            )
        )
        self._r_bfchar_block.define(
            Seq(
                self._r_opt_count,
                self._r_beginbfchar_kw,
                self._r_ws,
                ZeroOrMore(
                    Seq(self._r_bfchar_pair, self._r_ws).map(
                        self._action_bfchar_block_2
                    )
                ),
                self._r_endbfchar_kw,
            ).map(self._action_bfchar_block_3)
        )
        self._r_opt_count.define(Opt(Seq(self._r_integer, self._r_ws)))
        self._r_bfchar_pair.define(
            Seq(self._r_hex_string, self._r_ws, self._r_hex_string).map(
                self._action_bfchar_pair_4
            )
        )
        self._r_bfrange_block.define(
            Seq(
                self._r_opt_count,
                self._r_beginbfrange_kw,
                self._r_ws,
                ZeroOrMore(
                    Seq(self._r_bfrange_entry, self._r_ws).map(
                        self._action_bfrange_block_5
                    )
                ),
                self._r_endbfrange_kw,
            ).map(self._action_bfrange_block_6)
        )
        self._r_bfrange_entry.define(
            Choice(self._r_bfrange_array_entry, self._r_bfrange_single_entry)
        )
        self._r_bfrange_single_entry.define(
            Seq(
                self._r_hex_string,
                self._r_ws,
                self._r_hex_string,
                self._r_ws,
                self._r_hex_string,
            ).map(self._action_bfrange_single_entry_7)
        )
        self._r_bfrange_array_entry.define(
            Seq(
                self._r_hex_string,
                self._r_ws,
                self._r_hex_string,
                self._r_ws,
                Lit("["),
                self._r_ws,
                ZeroOrMore(
                    Seq(self._r_hex_string, self._r_ws).map(
                        self._action_bfrange_array_entry_8
                    )
                ),
                Lit("]"),
            ).map(self._action_bfrange_array_entry_9)
        )
        self._r_hex_string.define(
            Seq(Lit("<"), Reg("[0-9A-Fa-f]+"), Lit(">")).map(self._action_hex_string_10)
        )
        self._r_dict_delim.define(
            Choice(Lit("<<"), Lit(">>")).map(self._action_dict_delim_11)
        )
        self._r_any_hex_chunk.define(
            Seq(Lit("<"), ZeroOrMore(Class(">", inverted=True)), Lit(">")).map(
                self._action_any_hex_chunk_12
            )
        )
        self._r_other_token.define(
            Seq(
                NotPred(self._r_beginbfchar_kw),
                NotPred(self._r_beginbfrange_kw),
                NotPred(self._r_endbfchar_kw),
                NotPred(self._r_endbfrange_kw),
                self._r_token_chars,
            ).map(self._action_other_token_13)
        )
        self._r_token_chars.define(Reg("[^ \\t\\r\\n%<>\\[\\]]+"))
        self._r_integer.define(Reg("[0-9]+"))
        self._r_beginbfchar_kw.define(Reg("(?i)beginbfchar\\b"))
        self._r_endbfchar_kw.define(Reg("(?i)endbfchar\\b"))
        self._r_beginbfrange_kw.define(Reg("(?i)beginbfrange\\b"))
        self._r_endbfrange_kw.define(Reg("(?i)endbfrange\\b"))
        self._r_ws.define(ZeroOrMore(self._r_ws_char))
        self._r_ws_char.define(
            Choice(
                Class(" \\t\\r\\n", inverted=False),
                Seq(Lit("%"), ZeroOrMore(Class("\\r\\n", inverted=True))),
            )
        )

        self.root_parser: Parser[Any] = self._r_cmap_file

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_cmap_file_0(val: Any) -> Any:
        it = val[0]
        return it

    @staticmethod
    def _action_cmap_file_1(val: Any) -> Any:
        items = val[1]
        return _build_cmap_mapping(items)

    @staticmethod
    def _action_bfchar_block_2(val: Any) -> Any:
        p = val[0]
        return p

    @staticmethod
    def _action_bfchar_block_3(val: Any) -> Any:
        pairs = val[3]
        return ("bfchar", pairs)

    @staticmethod
    def _action_bfchar_pair_4(val: Any) -> Any:
        src = val[0]
        dst = val[2]
        return _decode_bfchar_pair(src, dst)

    @staticmethod
    def _action_bfrange_block_5(val: Any) -> Any:
        r = val[0]
        return r

    @staticmethod
    def _action_bfrange_block_6(val: Any) -> Any:
        ranges = val[3]
        return ("bfrange", ranges)

    @staticmethod
    def _action_bfrange_single_entry_7(val: Any) -> Any:
        start = val[0]
        end = val[2]
        base = val[4]
        return _decode_bfrange_single(start, end, base)

    @staticmethod
    def _action_bfrange_array_entry_8(val: Any) -> Any:
        h = val[0]
        return h

    @staticmethod
    def _action_bfrange_array_entry_9(val: Any) -> Any:
        start = val[0]
        end = val[2]
        arr = val[6]
        return _decode_bfrange_array(start, end, arr)

    @staticmethod
    def _action_hex_string_10(val: Any) -> Any:
        raw = val[1]
        return raw

    @staticmethod
    def _action_dict_delim_11(val: Any) -> Any:
        return None

    @staticmethod
    def _action_any_hex_chunk_12(val: Any) -> Any:
        return None

    @staticmethod
    def _action_other_token_13(val: Any) -> Any:
        return None
