#!/usr/bin/env python3
"""
Auto-generated Packrat PEG Parser for grammar: BibTeX
Generated by DSN-25 Ahead-of-Time PEG Compiler. DO NOT EDIT DIRECTLY.
"""

from __future__ import annotations

from typing import Any

from core.structures.peg import (
    Choice,
    Class,
    Dot,
    Lit,
    NotPred,
    Opt,
    ParseContext,
    Parser,
    ParseResult,
    Reg,
    RuleRef,
    Seq,
    ZeroOrMore,
)
from pdf_engine.bibtex_helpers import _build_bibtex_entry, _collect_bibtex_entries

# User header code


class BibTeXParser(Parser[Any]):
    """Packrat PEG Parser for BibTeX grammar."""

    def __init__(self) -> None:
        self._init_rules()

    def _init_rules(self) -> None:
        self._r_file = RuleRef("file")
        self._r_item = RuleRef("item")
        self._r_entry = RuleRef("entry")
        self._r_entry_type = RuleRef("entry_type")
        self._r_cite_key = RuleRef("cite_key")
        self._r_field_list = RuleRef("field_list")
        self._r_field_assign = RuleRef("field_assign")
        self._r_field_name = RuleRef("field_name")
        self._r_field_value = RuleRef("field_value")
        self._r_braced_value = RuleRef("braced_value")
        self._r_quoted_value = RuleRef("quoted_value")
        self._r_plain_value = RuleRef("plain_value")
        self._r_comment_item = RuleRef("comment_item")
        self._r_string_def = RuleRef("string_def")
        self._r_preamble = RuleRef("preamble")
        self._r_skip_char = RuleRef("skip_char")
        self._r_ws = RuleRef("ws")

        self._r_file.define(
            Seq(self._r_ws, ZeroOrMore(self._r_item), self._r_ws).map(
                self._action_file_0
            )
        )
        self._r_item.define(
            Choice(
                self._r_entry,
                self._r_comment_item,
                self._r_string_def,
                self._r_preamble,
                self._r_skip_char,
            )
        )
        self._r_entry.define(
            Seq(
                Lit("@"),
                self._r_ws,
                self._r_entry_type,
                self._r_ws,
                Lit("{"),
                self._r_ws,
                self._r_cite_key,
                self._r_ws,
                Lit(","),
                self._r_ws,
                Opt(self._r_field_list),
                self._r_ws,
                Lit("}"),
            ).map(self._action_entry_1)
        )
        self._r_entry_type.define(Reg("[a-zA-Z]+").map(self._action_entry_type_2))
        self._r_cite_key.define(Reg("[^,\\s\\}]+").map(self._action_cite_key_3))
        self._r_field_list.define(
            Seq(
                self._r_field_assign,
                ZeroOrMore(
                    Seq(self._r_ws, Lit(","), self._r_ws, self._r_field_assign).map(
                        self._action_field_list_4
                    )
                ),
                Opt(Seq(self._r_ws, Lit(","))),
            ).map(self._action_field_list_5)
        )
        self._r_field_assign.define(
            Seq(
                self._r_field_name,
                self._r_ws,
                Lit("="),
                self._r_ws,
                self._r_field_value,
            ).map(self._action_field_assign_6)
        )
        self._r_field_name.define(Reg("[a-zA-Z0-9_-]+").map(self._action_field_name_7))
        self._r_field_value.define(
            Choice(self._r_braced_value, self._r_quoted_value, self._r_plain_value)
        )
        self._r_braced_value.define(
            Reg("\\{(?:[^{}\\\\]|\\\\.|(?:\\{[^{}]*\\}))*\\}").map(
                self._action_braced_value_8
            )
        )
        self._r_quoted_value.define(
            Reg('"(?:[^"\\\\]|\\\\.)*"').map(self._action_quoted_value_9)
        )
        self._r_plain_value.define(
            Reg("[a-zA-Z0-9_#]+").map(self._action_plain_value_10)
        )
        self._r_comment_item.define(
            Choice(
                Seq(
                    Lit("@"),
                    Reg("(?i)comment"),
                    self._r_ws,
                    Lit("{"),
                    ZeroOrMore(Class("}", inverted=True)),
                    Lit("}"),
                ).map(self._action_comment_item_11),
                Seq(Lit("%"), ZeroOrMore(Class("\\r\\n", inverted=True))).map(
                    self._action_comment_item_12
                ),
            )
        )
        self._r_string_def.define(
            Seq(
                Lit("@"),
                Reg("(?i)string"),
                self._r_ws,
                Lit("{"),
                self._r_ws,
                self._r_field_name,
                self._r_ws,
                Lit("="),
                self._r_ws,
                self._r_field_value,
                self._r_ws,
                Lit("}"),
            ).map(self._action_string_def_13)
        )
        self._r_preamble.define(
            Seq(
                Lit("@"),
                Reg("(?i)preamble"),
                self._r_ws,
                Lit("{"),
                ZeroOrMore(Class("}", inverted=True)),
                Lit("}"),
            ).map(self._action_preamble_14)
        )
        self._r_skip_char.define(
            Seq(NotPred(Choice(Lit("@"), NotPred(Dot()))), Dot()).map(
                self._action_skip_char_15
            )
        )
        self._r_ws.define(ZeroOrMore(Class(" \\t\\r\\n", inverted=False)))

        self.root_parser: Parser[Any] = self._r_file

    def parse(self, text: str) -> Any:
        """Parses input text and returns semantic value."""
        return self.root_parser.parse(text)

    def parse_at(self, ctx: ParseContext, pos: int) -> ParseResult[Any]:
        """Evaluates parser at given position."""
        return self.root_parser.parse_at(ctx, pos)

    @staticmethod
    def _action_file_0(val: Any) -> Any:
        items = val[1]
        return _collect_bibtex_entries(items)

    @staticmethod
    def _action_entry_1(val: Any) -> Any:
        t = val[2]
        k = val[6]
        f = val[10]
        return _build_bibtex_entry(t, k, f or [])

    @staticmethod
    def _action_entry_type_2(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_cite_key_3(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_field_list_4(val: Any) -> Any:
        nxt = val[3]
        return nxt

    @staticmethod
    def _action_field_list_5(val: Any) -> Any:
        first = val[0]
        rest = val[1]
        return [first] + rest

    @staticmethod
    def _action_field_assign_6(val: Any) -> Any:
        k = val[0]
        v = val[4]
        return (k, v)

    @staticmethod
    def _action_field_name_7(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_braced_value_8(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_quoted_value_9(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_plain_value_10(val: Any) -> Any:
        raw = val
        return raw

    @staticmethod
    def _action_comment_item_11(val: Any) -> Any:
        return None

    @staticmethod
    def _action_comment_item_12(val: Any) -> Any:
        return None

    @staticmethod
    def _action_string_def_13(val: Any) -> Any:
        return None

    @staticmethod
    def _action_preamble_14(val: Any) -> Any:
        return None

    @staticmethod
    def _action_skip_char_15(val: Any) -> Any:
        return None
